docs/conf.py
docs/source/pybamm.models.rst
pybamm/__init__.py
pybamm/models/components/electrolyte.py
pybamm/models/components/interface.py
pybamm/models/electrolyte_current.py
pybamm/models/reaction_diffusion.py
pybamm/operators.py
pybamm/parameters.py
pybamm/simulation.py
pybamm/solver.py
pybamm/variables.py
tests/test_electrolyte.py
tests/test_electrolyte_current.py
tests/test_interface.py
tests/test_parameters.py
tests/test_reaction_diffusion.py
tests/test_simulation.py

Reformat models to have a different class for each model and use components from sub-methods "Electrolyte", "Interface", etc. Will be improved further by Scott.
Add an "electrolyte current" model with MacInnes + Butler-Volmer.

Reformat Model Class

---

pybamm/expression_tree/domain.py
tests/test_expression_tree/test_independent_variable.py

Allow string input to domain (changes domain to list with single entry being the string)
Fixes #32

#32 allow string input to domain

---

pybamm/parameters/parameter_values.py
tests/test_parameters/test_parameter_values.py

Fix bug in parameter_values.process_symbols for Binary Operators.
Fixes #58

#58 fix bug in parameter processing

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
tests/test_discretisations/test_base_discretisations.py
tests/test_expression_tree/test_binary_operators.py
tests/test_expression_tree/test_symbol.py
tests/test_expression_tree/test_unary_operators.py

- Allow `BinaryOperator` to take a number as `left` and/or `right` (gets converted to `Scalar`)
- Implement `__neg__`, `__abs__`, `__pow__`
- Implement `__r*__` for binary operators
Fixes #45

Issue 45 overloaded binary ops

---

pybamm/parameters/parameter_values.py
tests/test_parameters/test_parameter_values.py

For processing of model parameters:
- change `ParameterValues.process_model` to take boundary conditions of the form `{"left": left bc, "right": right bc}`)
- add tests for `ParameterValues.process_model`
Fixes #65 

Issue 65 process parameters bcs

---

docs/source/expression_tree/concatenations.rst
docs/source/expression_tree/index.rst
pybamm/__init__.py
pybamm/discretisations/base_discretisation.py
pybamm/expression_tree/array.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/vector.py
tests/test_discretisations/test_base_discretisations.py
tests/test_expression_tree/test_concatenations.py
tests/test_expression_tree/test_symbol.py

To allow concatenation of more than just Scalars, made a new concatenation class `DomainConcatenation` that concatenates vectors (evaluated by child symbols) according to their domains, respecting both the ordering in KNOWN_DOMAINS, and the number of points within each domain. Just like the base `Concatenation`, it is assumed that the domains of the children are all distinct
As part of this work, added a `is_constant` function to `Symbol` that tests if evaluating that symbol depends on either y or t (this will also help with #54 and #55)
Fixes #80 

Issue 80 concat var scalar

---

pybamm/discretisations/base_discretisation.py
pybamm/expression_tree/array.py
pybamm/expression_tree/matrix.py
pybamm/expression_tree/symbol.py
tests/__init__.py
tests/test_discretisations/test_base_discretisations.py
tests/test_discretisations/test_finite_volume_discretisations.py

Fixes #91 
Have re-opened #91 to fix the case where there is both a `divergence` and a `gradient`:
```
Vector * Gradient(Variable) # should do node_to_edge
Vector * Divergence(Gradient(Variable)) # should not do node_to_edge
```
In doing so, realised there was an issue in `BaseDiscretisation.process_symbol` where, in the final `else`, detaching then reattaching `symbol.parent` switches around the order of `parent.children`:
```
symbol = Scalar * Vector 
symbol.children -> (Scalar, Vector)
disc.process_symbol(symbol)
symbol.children -> (Vector, Scalar)
```
This is a problem for recognising `symbol.id` in the boundary conditions

Issue 91 average diffusivity

---

pybamm/discretisations/meshes.py
pybamm/geometry/geometry.py
pybamm/parameters/standard_parameters.py
tests/test_geometry/test_geometry.py

The keys of the geometry dictionary are now independent variables. A set of tests have also been added to check that each key is an instance of `pybamm.IndependentVariable`
Fixes #132 

Changed geometry keys to indepedent variables and added tests for each

---

pybamm/discretisations/finite_volume_discretisations.py
pybamm/discretisations/meshes.py
tests/shared.py
tests/test_discretisations/test_finite_volume_discretisations.py

Mesh remains unchanged as previously discussed. Divergence is changed in case of negative or positive particles. No other changes to operators are required. 
A convergence test for divergence operator is provide.

Issue 9 add mesh and operators for spherical domian

---

pybamm/discretisations/base_discretisation.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/symbol.py
pybamm/parameters/parameter_values.py
tests/test_discretisations/test_base_discretisations.py
tests/test_expression_tree/test_concatenations.py
tests/test_expression_tree/test_symbol.py

- Use `deepcopy` instead of `copy` when processing parameters, discretising and unpacking a Concatenation. This should help to avoid some TreeErrors to do with corrupt internal tree data. Still use copy when creating the expression tree (in `Symbol.__init__`) for speed/memory
- Simplify `ParameterValues.process_symbol` and `BaseDiscretisation.process_symbol` accordingly
Fixes #136

Issue 136 copy symbol

---

docs/index.rst
docs/source/geometry/geometry.rst
docs/source/geometry/index.rst
docs/source/meshes/index.rst
docs/source/meshes/meshes.rst
docs/source/meshes/submeshes.rst
pybamm/__init__.py
pybamm/discretisations/base_discretisation.py
pybamm/discretisations/finite_volume_discretisations.py
pybamm/meshes/meshes.py
pybamm/meshes/submeshes.py
pybamm/models/base_model.py
tests/shared.py
tests/test_discretisations/test_base_discretisations.py
tests/test_discretisations/test_finite_volume_discretisations.py
tests/test_expression_tree/test_concatenations.py
tests/test_expression_tree/test_unary_operators.py
tests/test_models/standard_model_tests.py
tests/test_models/test_interface.py
tests/test_models/test_lead_acid.py
tests/test_models/test_simple_ode_model.py
tests/test_solvers/test_scikits_solvers.py
tests/test_solvers/test_scipy_solver.py

Mesh moved outside of discretisation and tests corrected
Fixes #133 

Issue 133 refactor meshing to occur outside discretisation

---

.gitignore
docs/source/expression_tree/unary_operator.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/unary_operators.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/test_spatial_methods/test_finite_volume.py

Added a new unary operator `SurfaceValue` used to get the surface value of a variable. This is required for certain expressions (e.g. Butler-Volmer). At present it just computes the surface value on the right (it assumed we need the value at the surface of a spherical particle). This is implemented by `surface_value` in finite_volume.py for finite volumes by taking slices of the state vector (see lines 261-264), but maybe it is better to create a new class similar to `NodeToEdge`?
Fixes #159 

Issue 159 surface vals

---

pybamm/discretisations/discretisation.py
pybamm/geometry/geometry.py
pybamm/models/base_model.py
pybamm/models/li_ion/single_particle_model.py
tests/__init__.py
tests/shared.py
tests/test_discretisations/test_base_discretisations.py
tests/test_expression_tree/test_concatenations.py
tests/test_expression_tree/test_unary_operators.py
tests/test_geometry/test_geometry.py
tests/test_models/standard_model_tests.py
tests/test_models/test_interface.py
tests/test_models/test_lead_acid.py
tests/test_models/test_li_ion.py
tests/test_models/test_simple_ode_model.py
tests/test_parameters/test_standard_parameters_lead_acid.py
tests/test_solvers/test_scikits_solvers.py
tests/test_solvers/test_scipy_solver.py
tests/test_spatial_methods/test_finite_volume.py

- Merge macroscale and microscale in `tests.shared`.
- Decouple the defaults in the models (means we have to do more work outside the model, but I think this is worth it)
- Change spatial_methods dict to take a "macroscale" input
Fixes #153 and #164

Issue 153 test statements

---

docs/source/expression_tree/unary_operator.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/unary_operators.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/test_discretisations/test_discretisation.py
tests/test_expression_tree/test_unary_operators.py
tests/test_spatial_methods/test_finite_volume.py

Node to calculate the definite integral, needed for some of the reduced-order models
Fixes #111

Issue 111 integral node

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
setup.py
tests/test_expression_tree/test_binary_operators.py
tests/test_expression_tree/test_symbol.py
tests/test_expression_tree/test_symbolic_diff.py
tests/test_expression_tree/test_unary_operators.py

Implement symbolic differentiation using simple calculus rules and autograd for the `Function` objects.
Requires implementing functions using `autograd.numpy` instead of `numpy`.
Fixes #189

Issue 189 symbolic differentiation

---

docs/source/expression_tree/unary_operator.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/unary_operators.py
pybamm/parameters/parameter_values.py
pybamm/solvers/ode_solver.py
pybamm/spatial_methods/finite_volume.py
tests/test_models/test_li_ion.py
tests/test_spatial_methods/test_finite_volume.py

Extend functionality of `SurfaceValue` to (i) allow extrapolation to left and right and (ii) work on any kind of symbol
Fixes #218

Issue 218 extrapolate left right

---

pybamm/discretisations/discretisation.py
pybamm/models/base_models.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
pybamm/solvers/scipy_solver.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/shared.py
tests/test_discretisations/test_discretisation.py
tests/test_spatial_methods/test_finite_volume.py
tests/test_spatial_methods/test_spatial_methods.py

Adds `mass_matrix` attribute to model which is processed during discretisation to give the correct mass matrix for a given spatial method
Fixes #215 

Issue 215 mass matrix

---

pybamm/__init__.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
tests/test_expression_tree/test_concatenations.py
tests/test_expression_tree/test_symbol.py

- expanded binary simplification
- added unary simplifications
- made sure DomainConcatenation simplification works
- for *all* nodes, if the expression evaluates to a constant scalar/vector/matrix, then it is simplified to an appropriate Scalar/Vector/Matrix node
Fixes #203 

#203 more binary and unary simplifications, including concatentaions

---

pybamm/__init__.py
pybamm/parameters/parameter_values.py
pybamm/spatial_methods/finite_volume.py
tests/test_models/test_lead_acid/test_lead_acid_newman_tiedemann.py
tests/test_models/test_lithium_ion/test_lithium_ion_dfn.py
tests/test_spatial_methods/test_finite_volume.py

Remove `NodeToEdge` and `BoundaryValueEvaluated` as they are overkill
Fixes #244

#244 remove unnecessary functions

---

pybamm/expression_tree/binary_operators.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py
tests/test_expression_tree/test_symbol.py

- add more simplifications to expression tree
1. given a term in the expression tree consisting of multiplications/divisions, pybamm will attempt to simplify it by grouping together those sub-terms that are constant, and return a value, and those that are not. Those that are constant are reduced to a single sub-term
2. given a term in the expression tree consisting of multiplications/divisions/matrix-multiplications, pybamm will attempt to simplify it by grouping together neighbouring sub-terms that are constant, and return a value. Note that this is different to 1, due to the presence of matrix-multiplications pybamm does not attempt to reorder the terms.
3. given a term in the expression tree consisting of additions/subtractions, pybamm will attempt to simplify it by grouping together …

Issue 233 add simplifications to solver

---

pybamm/models/lithium_ion/spm.py
pybamm/models/submodels/interface.py

Cleaned up the SPM output variables a bit so that long expressions do not need to be implemented explicitly within the SPM model file. Other output variables are provided within submodels
Fixes #242
- [] Tests added that prove fix is effective or that feature works

Issue 242 output vars to spm

---

docs/index.rst
docs/source/expression_tree/variable.rst
docs/source/expression_tree/vector.rst
docs/source/processed_variable.rst
pybamm/processed_variable.py
tests/test_processed_variable.py

Use `.__call__` instead of `.evaluate` to evaluate a processed variable
Fixes #227

#227 change evaluate to __call__

---

pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/unary_operators.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/test_discretisations/test_discretisation.py
tests/test_spatial_methods/test_finite_volume.py

Implements the indefinite integral for the cases which we require (i.e. integrate current to get potential). 
Fixes #175

Issue 175 indefinite integral

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/symbol.py
tests/test_expression_tree/test_matrix.py
tests/test_models/test_reaction_diffusion.py

Slightly modify `simplify_multiplication_division` to ensure that simplified tree is faster than the original tree:
- reverse the order of `fold_multiply` so that operations are performed in optimal order (but still simplified if constant)
- Catch sparse matrices as being constant
Fixes part of #264

Issue 264 matrix multiplication

---

pybamm/expression_tree/concatenations.py
tests/test_expression_tree/test_concatenations.py

Concatenation of StateVectors simplifies to a single StateVector
Fixes #270

#270 simplify concat of state vectors

---

tests/test_expression_tree/test_binary_operators.py
tests/test_expression_tree/test_matrix.py
tests/test_models/standard_model_tests.py
tests/test_models/test_lead_acid/test_lead_acid_newman_tiedemann.py
tests/test_models/test_lithium_ion/test_lithium_ion_dfn.py

Change `__init__` function for standard model tests for more flexibility
Fixes #274 

#274 simplify standard model tests

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/symbol.py
tests/unit/test_expression_tree/test_matrix.py

Fixes #295 
removed timing test in test_matrix.py as was failing occasionally. changed to simply checking that the simplified expression was identical (according to the id)

#295 allow mat-muls on the denominator

---

README.md
pybamm/__init__.py
pybamm/models/base_models.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
tests/unit/test_models/test_lead_acid/test_newman_tiedemann.py
tests/unit/test_models/test_lithium_ion/test_lithium_ion_dfn.py
tests/unit/test_models/test_submodels/test_electrode.py
tests/unit/test_models/test_submodels/test_electrolyte_current.py

Skip tests as appropriate so that pybamm can be used without installing scikits
Fixes #310 

Issue 310 scikits installation

---

pybamm/discretisations/discretisation.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
pybamm/parameters/parameter_values.py

Refactor `IndefiniteIntegral` to remove duplicate code
Fixes #307 

#307 remove duplicate code in integrals

---

pybamm/expression_tree/array.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/unary_operators.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py

Adapt Jacobian-specific functions to allow using the `known_evals` dict
Part of #315 

Use known_evals in Jacobian (#115)

---

pybamm/__init__.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/unary_operators.py
tests/unit/test_expression_tree/test_jac.py

- Compute Function jacobian elementwise 
- Remove `Diagonal` nodes and use elementwise multiplication/division instead 
- Remove `SparseStack.sparsify()` (no longer needed)
The `evaluate` hack from `Multiplication` is now used in `Division` as well, ideally will be removed by #320 
Part of #315 
Before:
```
In [1]: %timeit jac.evaluate(0,y0)                                                                                                            
61 ms ± 447 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [2]: %timeit jac.evaluate(0,y0,{})                                                                                                         
29 ms ± 219 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
In [3]: %timeit self.integrate( residuals, y0, t_eval, …
```

Issue 315 elementwise function jac

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
tests/unit/test_expression_tree/test_symbol.py

As discussed this morning, pre-assign children to get around slow anytree lookup
Fixes #319 

#319 cache children

---

pybamm/models/base_models.py
pybamm/models/lead_acid/loqs.py
pybamm/models/simple_ode_model.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py

Add a flag to the model to allow skipping the use of the jacobian (e.g. for ODE models, where the jacobian is almost full and inverting the matrix during an implicit time step is cheap, so we don't need the jacobian)
Part of #315 

#315 add flag to skip using jacobian for ODE models

---

pybamm/solvers/scikits_ode_solver.py
tests/unit/test_solvers/test_scikits_solvers.py

Fixes half (ode solver) of #322
Enables user to set `linsolver` for scikits_odes_solver. For the `dense` solver, the sparse jacobian changed to a dense array, for the iterative solvers ('spgmr', 'spbcgs', 'sptfqmr') the sparse matrix is used directly.
However, I found that using the iterative solvers generally made the solvers take significantly longer to run, so `dense` is currently left as the default
@rtimms, @tinosulzer: is an iterative solver the approach we want to take for the sparse jacobian? If so, do we need preconditioning? 
Note that I've only done this for the sundials ode solver, as scikits.odes only exposes this functionality for cvode. I would have to edit scikits.odes to get this working for ida
You can run all three at once, …

Issue 322 sparse

---

pybamm/discretisations/discretisation.py
pybamm/expression_tree/symbol.py
pybamm/parameters/parameter_values.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_parameters/test_parameter_values.py

Remove deepcopy operations from `ParameterValues` and `Discretisation` as they are slow.
Fixes half of #329 
Before:
After:

Issue 329 remove deepcopy param disc

---

docs/tutorials/add-spatial-method.rst
pybamm/discretisations/discretisation.py
pybamm/models/lead_acid/loqs.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/shared.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_spatial_methods/test_spatial_methods.py

Move `process_binary_operators` to the spatial method, speeds up the processing of the ODE models.
Fixes #331

Issue 331 process binary operators

---

tests/__init__.py
tests/unit/test_models/standard_model_tests.py
tests/unit/test_models/standard_output_tests.py
tests/unit/test_models/test_lead_acid/test_composite.py
tests/unit/test_models/test_lead_acid/test_loqs.py
tests/unit/test_models/test_lead_acid/test_newman_tiedemann.py
tests/unit/test_models/test_lithium_ion/test_lithium_ion_spm.py

Remove redundant tests (now that we do the output tests as standard), and change `standard_output_tests` back to object-oriented
@Scottmar93  see if you like this

Remove tests

---

.travis.yml
pybamm/discretisations/discretisation.py
pybamm/meshes/submeshes.py
pybamm/parameters/parameter_values.py
pybamm/solvers/scikits_dae_solver.py
setup.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_geometry/test_geometry.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

Fixes #191 
Key issue was that for python 3.5 (and lower) the `dict` class is unordered, so python is free to reorder things as it likes. We were assuming in a few places that the order of our `dicts` *was* fixed, so this was throwing errors. 
other issues were to do with scikits.odes:
1. there was a strange cython bug regarding multiple imports, which occured when we tried to import ida many times
2. need to make sure travis has the correct version of the python header files
3. scikits.odes actually depends on numpy v 1.16, so bumped this version in pybamm's requirements

Issue 191 python3.5

---

docs/source/expression_tree/broadcasts.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/broadcasts.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/vector.py
pybamm/parameters/parameter_values.py
pybamm/spatial_methods/spatial_method.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_expression_tree/test_broadcasts.py
tests/unit/test_expression_tree/test_concatenations.py
tests/unit/test_expression_tree/test_simplify.py
tests/unit/test_models/test_simple_ode_model.py
tests/unit/test_parameters/test_parameter_values.py

Switch to using explicit multiplication by a vector instead of `NumpyBroadcast`.
This speeds things up a bit as the vectors can then be simplified away, so we should think about doing something similar for concatenations.
Fixes part of #264 

Issue 264 simplify broadcast

---

.travis.yml
examples/scripts/SPMe.py
run-tests.py

modify run_tests.py to test both notebooks and example scripts:
usage:
```bash
./run_tests.py --examples
```
will run both notebooks and scripts
Fixes #384 

Issue 384 test scripts

---

pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/broadcasts.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/independent_variable.py
pybamm/expression_tree/parameter.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
pybamm/expression_tree/variable.py
pybamm/expression_tree/vector.py
pybamm/models/submodels/electrolyte_current.py
pybamm/settings.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
run-tests.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_concatenations.py
tests/unit/test_expression_tree/test_copy.py
tests/unit/test_expression_tree/test_evaluate.py
tests/unit/test_expression_tree/test_parameter.py
tests/unit/test_expression_tree/test_simplify.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_models/test_base_model.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_spatial_methods/test_spatial_methods.py

Add a test on node initialisation to check that the node can be evaluated without any shape errors.
Works even for nodes that can't be evaluated directly (creates a vector of the appropriate shape instead).
Will hopefully help with catching errors earlier when creating new models, but isn't flawless (there can still be errors in the discretisation, for example). 
Checking for shape on every node initialisation makes the models pretty slow, so I have added a settings class with a `debug_mode` attribute, which is `False` by default but can be set to `True` from anywhere. Not sure whether this is a good idea ...
Fixes #441

Issue 441 shape test

---

pybamm/processed_variable.py
tests/integration/test_models/standard_output_comparison.py
tests/integration/test_models/standard_output_tests.py
tests/integration/test_models/test_lead_acid/test_composite.py
tests/integration/test_models/test_lithium_ion/test_lithium_ion_dfn.py
tests/unit/test_processed_variable.py

Use `known_evals` to post-process all of the variables more efficiently.
This provides quite a big speed-up, since most of the variables are small variations on each other.
Fixes #451 

Issue 451 process variables

---

pybamm/discretisations/discretisation.py
pybamm/expression_tree/simplify.py
pybamm/parameters/parameter_values.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py
tests/unit/test_expression_tree/test_binary_operators.py

Move the logger.debug statements to be less noisy and more informative

put debug in more informative places

---

pybamm/expression_tree/simplify.py
tests/unit/test_expression_tree/test_simplify.py

Fix a bug in `simplify-add-subtract` that was causing `1 - (b+c)` to get simplified to `1 - (b-c)`

fix bug with subtraction of subtractions

---

.travis.yml
README.md
pybamm/__init__.py
pybamm/geometry/geometry.py
pybamm/meshes/meshes.py
pybamm/meshes/scikit_fem_submeshes.py
pybamm/models/lithium_ion/spm.py
pybamm/spatial_methods/scikit_finite_element.py
tests/__init__.py
tests/shared.py
tests/unit/test_meshes/test_scikit_fem_submesh.py
tests/unit/test_spatial_methods/test_scikit_finite_element.py

Add scikit-fem mesh and spatial method for 2D current collector submodels
To do: 
- implement 2D submodel in li-ion models (as separate issue)
Fixes #475 

#475 add scikit-fem mesh and spatial method

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/simplify.py
pybamm/expression_tree/vector.py
tests/unit/test_expression_tree/test_simplify.py

fix outer product bug. problem was that the outer product expects a particular domain, and the domains were getting wiped due to the new_copy in Statevector.
@rtimms: Other (integration) tests fail, is this expected for the issue-477-2plus-li-ion branch?
Fixes #486

Issue 486 divide outer bug

---

CONTRIBUTING.md
pybamm/models/full_battery_models/base_battery_model.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py

Basic functionality to process symbol within model. Maybe not super useful in current form, but can be updated as we go along.
Fixes #530 

Issue 530 debug within model

---

pybamm/models/submodels/electrolyte/base_electrolyte_conductivity.py

The variable "Electrolyte potential [V]" was returning the non-dimensional potential instead of the dimensional version 
Fixes #585 

#585 electrolyte bug

---

pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_update_parameters.py

Named scalars in the current function are now properly updated 
Fixes #592 

#592 fix current bug

---

pybamm/meshes/meshes.py
pybamm/parameters/parameter_values.py
tests/unit/test_meshes/test_meshes.py
tests/unit/test_meshes/test_scikit_fem_submesh.py

Fixes #568 
the `ParameterValues` member function `process_geometry` executes all the expressions in the provided geometry, but this fails in the case where the geometry does not have any parameters, and therefore should not need to be processed by `ParameterValues`. This causes problems in the mesh creation (in `Mesh.__init__()`), which assumes that all the expressions have been evaluated. 
I've moved the evaluation of the expressions to `Mesh.__init__()`.

Issue 568 no parameters

---

examples/scripts/DFN.py
examples/scripts/SPMe.py
pybamm/solvers/base_solver.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
pybamm/solvers/scipy_solver.py
pybamm/solvers/solution.py
tests/unit/test_quick_plot.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

I have added t_event and y_event to the object Solution that pick up the time and solution when the event happens. I have taken the format from Scikits and adapted the Scipy solver to provide a similar output. Also, I have changed `get_termination_reason` so now it evaluates t_event and y_event instead of the final time.
Fixes #590 
One test fails but that is not related to the changes I have done as it fails too in my master branch.

Issue 590 termination events

---

.gitignore
pybamm/discretisations/discretisation.py
pybamm/parameters/parameter_values.py
pybamm/solvers/base_solver.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_solvers/test_base_solver.py

Raise obvious error if an empty model is passed down the pipeline.
Fixes #578 

Issue 578 process empty model

---

pybamm/models/full_battery_models/base_battery_model.py
pybamm/solvers/base_solver.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
pybamm/solvers/scipy_solver.py
results/change_settings/change_solver_tolerances.py
results/change_settings/compare_var_pts.py
tests/integration/test_models/standard_model_tests.py
tests/unit/test_processed_variable.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

Allows the user to set `rtol` and `atol` separately. For the defaults I've selected 1e-3 for rtol and 1e-6 for atol. This is the same as other solvers (e.g. scipy.integrate or MATLABs ODE15s) and provides a pretty significant speedup vs 1e-8 for both. I've also reduced the default number of points in x, as again this speed things up quite a bit. Both of these result in a RMS voltage error of around 1e-4 compared with the previous defaults, but the default DFN now runs in around 3 seconds vs 23 seconds (on my computer at least).
I think for most users, this kind of error is ok out of the box (the plots are indistinguishable), particularly if they are new users and just want to quickly run some examples. Users now have more control over both solver tolerances, so I think this is an ok …

#644 set atol and rtol

---

pybamm/expression_tree/state_vector.py
tests/unit/test_expression_tree/test_state_vector.py

Reuse evaluation array when making a copy of a state vector
Fixes #653

#652 cache evaluation array

---

pybamm/expression_tree/unary_operators.py

Don't unnecessarily check that the slice size exceeds the child size when making a new copy of an Index node
Fixes #655 

#655 dont check size on new copy

---

.travis.yml

Change order of tests in travis to reduce total test time

reorder travis file

---

CHANGELOG.md
examples/scripts/compare_comsol/compare_comsol_DFN.py
pybamm/models/submodels/current_collector/effective_resistance_current_collector.py
pybamm/parameters/parameter_values.py
results/2plus1D/compare_lithium_ion_2plus1D.py
results/2plus1D/compare_spmecc.py
results/2plus1D/spm_2plus1D_tab_grid.py
results/2plus1D/spmecc.py
results/2plus1D/user_mesh_spm_1plus1D.py
tests/integration/test_models/standard_output_tests.py
tests/unit/test_parameters/test_dimensionless_parameter_values_lithium_ion.py
tests/unit/test_parameters/test_parameter_values.py

Add function to evaluate parameters more easily.
Fixes #668 

#668 add evaluate function

---

input/parameters/lithium-ion/cells/kokam_Marquis2019/parameters.csv

Remove duplicate parameter
Fixes #666 

#666 remove duplicate param

---

CHANGELOG.md
pybamm/__init__.py
pybamm/logger.py
pybamm/processed_variable.py
pybamm/quick_plot.py
tests/unit/test_logger.py
tests/unit/test_processed_variable.py

Add warning if processed variable is called outside range
Fixes #570 

Issue 570 processed var warning

---

.gitignore
examples/scripts/compare-dae-solver.py
examples/scripts/compare_lithium_ion.py
pybamm/processed_variable.py
pybamm/quick_plot.py
pybamm/solvers/algebraic_solver.py
pybamm/solvers/base_solver.py
pybamm/solvers/casadi_solver.py
pybamm/solvers/dae_solver.py
pybamm/solvers/idaklu_solver.py
pybamm/solvers/ode_solver.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
pybamm/solvers/scipy_solver.py
pybamm/solvers/solution.py
tests/unit/test_solvers/test_algebraic_solver.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

Add 'safe' mode to casadi for solving with events. This is hacky and make the solver slower.
Fixes #684 

Issue 684 casadi events

---

CHANGELOG.md
pybamm/spatial_methods/scikit_finite_element.py
tests/unit/test_processed_variable.py
tests/unit/test_spatial_methods/test_scikit_finite_element.py

Fixes a sign error when implementing Dirichlet BCs in the finite element method
EDIT: also fixes a bug where spatial variables were discretised to a vector of length N_y or N_z for y and z, respectively, instead of a vector of length N_y*N_z
Fixes #705 

#705 fix sign error

---

input/parameters/lithium-ion/anodes/graphite_mcmb2528_Marquis2019/graphite_mcmb2528_diffusivity_Dualfoil1998.py
input/parameters/lithium-ion/cathodes/lico2_Marquis2019/lico2_diffusivity_Dualfoil1998.py

Remove sto*0 in the solid diffusion coefficients. This was fixed by something in an earlier PR which makes binary operators preserve shape during simplify (specifically addition of a scalar and a matrix) 
Fixes #547 

#547 remove sto times zero

---

CHANGELOG.md
examples/scripts/DFN.py
pybamm/models/submodels/current_collector/set_potential_single_particle.py
pybamm/models/submodels/electrode/ohm/full_ohm.py
pybamm/models/submodels/electrolyte/base_electrolyte_diffusion.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/full_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/surface_potential_form/full_surface_form_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/surface_potential_form/leading_surface_form_stefan_maxwell_conductivity.py
pybamm/models/submodels/interface/lead_acid.py
pybamm/parameters/standard_parameters_lead_acid.py

Fix bug with temperature in initial conditions
Fixes #736 

#736 change T_ref to T_init

---

CHANGELOG.md
input/parameters/lithium-ion/cells/kokam_Marquis2019/parameters.csv
pybamm/discretisations/discretisation.py
pybamm/simulation.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_parameters/test_update_parameters.py
tests/unit/test_simulation.py

Allows users to optionally skip model checks during discretisation, as this can be slow for large systems. By default the checks are performed, and it is recommended to do the model checks when developing, testing etc.
Fixes #738 

#738 check model option

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/independent_variable.py
pybamm/geometry/standard_spatial_vars.py
pybamm/models/submodels/convection/base_convection.py
pybamm/models/submodels/convection/composite_convection.py
pybamm/models/submodels/convection/leading_convection.py
pybamm/models/submodels/electrode/base_electrode.py
pybamm/models/submodels/electrode/ohm/composite_ohm.py
pybamm/models/submodels/electrode/ohm/leading_ohm.py
pybamm/models/submodels/electrode/ohm/surface_form_ohm.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/base_higher_order_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/leading_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/surface_potential_form/full_surface_form_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/composite_stefan_maxwell_diffusion.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/first_order_stefan_maxwell_diffusion.py
pybamm/models/submodels/interface/kinetics/base_first_order_kinetics.py
pybamm/models/submodels/oxygen_diffusion/first_order_oxygen_diffusion.py
pybamm/models/submodels/particle/fickian/fickian_single_particle.py
pybamm/models/submodels/thermal/base_thermal.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/spatial_method.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_spm.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_processed_variable.py

Remove outers and primary broadcasts from some models and do it automatically instead.
Fixes #746 

Issue 746 broadcasting

---

tests/unit/test_models/test_base_model.py

Looks like the bug in warnings has now been fixed
Fixes #505 

#505 see if warnings bug is fixed

---

CHANGELOG.md
docs/source/expression_tree/unary_operator.rst
pybamm/discretisations/discretisation.py
pybamm/expression_tree/unary_operators.py
pybamm/models/submodels/thermal/x_lumped/x_lumped_2D_current_collectors.py
pybamm/models/submodels/thermal/xyz_lumped/xyz_lumped_2D_current_collector.py
pybamm/spatial_methods/scikit_finite_element.py
pybamm/spatial_methods/spatial_method.py
tests/unit/test_spatial_methods/test_base_spatial_method.py
tests/unit/test_spatial_methods/test_scikit_finite_element.py

Added the gradient operation in the finite element method. This has then been used to compute the ohmic heating in the current collector 
Fixes #765 

Issue 765 compute grad fem

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
pybamm/models/base_model.py
pybamm/solvers/casadi_solver.py
pybamm/solvers/dae_solver.py
pybamm/solvers/ode_solver.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_solvers/test_casadi_solver.py

Automatically computes the inverse of the mass matrix during discretisation so that the resulting system of DAEs can be provided in semi explicit form, which is required by the casadi solver
Fixes #762 

Issue 762 casadi mass

---

CHANGELOG.md
docs/source/expression_tree/binary_operator.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/operations/convert_to_casadi.py
pybamm/expression_tree/operations/evaluate.py
pybamm/expression_tree/operations/jacobian.py
pybamm/spatial_methods/spatial_method.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py
tests/unit/test_expression_tree/test_operations/test_evaluate.py
tests/unit/test_expression_tree/test_operations/test_jac.py
tests/unit/test_expression_tree/test_operations/test_jac_2D.py
tests/unit/test_expression_tree/test_operations/test_simplify.py
tests/unit/test_parameters/test_parameter_values.py

Remove Outer and Kron nodes as they are no longer needed
Fixes #774 

Issue 774 remove outer kron

---

CHANGELOG.md
pybamm/spatial_methods/finite_volume.py
tests/unit/test_spatial_methods/test_finite_volume/test_finite_volume.py

Adds the harmonic mean to the finite element method. This is then used in `process_binary_operators` so that fluxes are computed using the harmonic mean of the diffusivity (or conductivity etc.) 
Fixes #782 

#782 add harmonic mean

---

CHANGELOG.md
docs/source/models/lithium_ion/dfn.rst
docs/source/models/lithium_ion/spm.rst
examples/notebooks/README.md
pybamm/expression_tree/functions.py
pybamm/models/full_battery_models/lithium_ion/__init__.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/full_battery_models/lithium_ion/basic_spm.py
pybamm/models/submodels/particle/base_particle.py
pybamm/models/submodels/thermal/isothermal/isothermal.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_compare_basic_models.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_basic_models.py

Create a basic SPM and basic DFN in order to help introduce the battery models in a more user-friendly way.
Fixes #791 

Issue 791 complete models

---

.requirements-docs.txt
CHANGELOG.md
examples/notebooks/change-settings.ipynb
examples/notebooks/parameter-values.ipynb
examples/scripts/DFN.py
examples/scripts/compare_lead_acid_3D.py
pybamm/__init__.py
pybamm/models/base_model.py
pybamm/models/full_battery_models/base_battery_model.py
pybamm/parameters/parameter_values.py
pybamm/parameters/print_parameters.py
pybamm/util.py
setup.py
tests/integration/test_models/test_full_battery_models/test_lead_acid/test_asymptotics_convergence.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_simulation.py
tests/unit/test_util.py

Add fuzzy dict and raise errors if a parameter is updated that wasn't previously defined (so users don't think they've updated them when they haven't)
Fixes #790 
Fixes #662 

Issue 790 param not recognized

---

CHANGELOG.md

Adds changelog for #759 
Sorry, forgot to add this!

#759 add changelog

---

pybamm/__init__.py
pybamm/expression_tree/concatenations.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/submodels/porosity/constant_porosity.py
pybamm/parameters/standard_parameters_lithium_ion.py
tests/unit/test_expression_tree/test_concatenations.py

Allow porosity to vary in space
Fixes #802 

Issue 802 porosity

---

pybamm/expression_tree/symbol.py

Make visualise raise a logger error only if graphviz is not installed (so that graphviz is an optional dependency)
Fixes #803 

#803 make visualise fail only raise logger error

---

pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/full_battery_models/lithium_ion/basic_spm.py

The diffusion coefficient was missing from the boundary conditions in the basic models
Fixes #838 

#838 fix boundary condition

---

CHANGELOG.md
pybamm/solvers/base_solver.py
pybamm/solvers/casadi_solver.py
pybamm/solvers/idaklu_solver.py
pybamm/solvers/scikits_dae_solver.py
setup.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_idaklu_solver.py
tests/unit/test_solvers/test_scikits_solvers.py

Add the (now default) option to use casadi's rootfinder to initialize the DAEs
Fixes #804 

Issue 804 initialize casadi

---

pybamm/parameters/standard_parameters_lithium_ion.py

Fixes an inconsistency where solid diffusivity is defined as a function of `sto` in `inputs/parameters` and a function of `c` in `standard_parameters_lithium_ion`
Fixes #843 

#843 diffusion as function of sto

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

Fixes a bug where current data was being incorrectly scaled by the typical current
Fixes #851 

#851 fix scaling bug in current data

---

pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_conductivity_Landesfeind2019_EC_DMC_1_1.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_conductivity_Landesfeind2019_EC_EMC_3_7.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_conductivity_Landesfeind2019_EMC_FEC_19_1.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_conductivity_Landesfeind2019_base.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_diffusivity_Landesfeind2019_EC_DMC_1_1.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_diffusivity_Landesfeind2019_EC_EMC_3_7.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_diffusivity_Landesfeind2019_EMC_FEC_19_1.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Landesfeind2019/electrolyte_diffusivity_Landesfeind2019_base.py
tests/unit/test_parameters/test_parameter_sets/test_Landesfeind2020.py

Add new electrolyte functions for conductivity and diffusivity from Landesfeind 2019
Fixes # 859

Add new electrolyte functions from Landesfeind 2019

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

#917 fix function that returns float

---

examples/scripts/compare_comsol/compare_comsol_DFN.py
pybamm/input/parameters/lead-acid/electrolytes/sulfuric_acid_Sulzer2019/parameters.csv
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Kim2011/parameters.csv
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Marquis2019/parameters.csv
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_Nyman2008/parameters.csv
pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
pybamm/models/full_battery_models/lithium_ion/base_lithium_ion_model.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/base_higher_order_stefan_maxwell_conductivity.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/composite_stefan_maxwell_diffusion.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/first_order_stefan_maxwell_diffusion.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/full_stefan_maxwell_diffusion.py
pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/leading_stefan_maxwell_diffusion.py
pybamm/parameters/standard_parameters_lead_acid.py
pybamm/parameters/standard_parameters_lithium_ion.py
tests/unit/test_models/test_submodels/test_electrolyte/test_stefan_maxwell/test_diffusion/test_leading_stefan_maxwell_diffusion.py
tests/unit/test_parameters/test_standard_parameters_lead_acid.py

Make t_plus and (1 + dlnf/dlnc) functions of c_e
Fixes #825 

Issue 825 tplus

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
tests/unit/test_discretisations/test_discretisation.py

Store variable slices in the model after discretisation
Fixes #924 

store slices

---

CHANGELOG.md
pybamm/simulation.py

#934 google colab compatibility

---

CHANGELOG.md
pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_scikits_solvers.py

Fixes #941
- [] All tests pass: `$ python run-tests.py --unit`

#941 filter out discon events after the end of the solver time

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
pybamm/expression_tree/exceptions.py
pybamm/models/base_model.py
pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_base_solver.py

Automatically discretize a 0D model if it is passed to a solver without having been discretized
Fixes #944 

Issue 944 autodisc

---

pybamm/models/submodels/current_collector/potential_pair.py

Fixes an issue with initial conditions in the pouch cell models when not doing constant current.
Fixes #953 

#953-change-initial-conditions

---

CHANGELOG.md
pybamm/expression_tree/interpolant.py
tests/unit/test_parameters/test_parameter_values.py

Change interpolant id so that different interpolants have different ids
Fixes #961 

#961 fix interpolant ids

---

pybamm/solvers/algebraic_solver.py
pybamm/solvers/base_solver.py
pybamm/solvers/casadi_algebraic_solver.py
pybamm/solvers/casadi_solver.py
pybamm/solvers/idaklu_solver.py
pybamm/solvers/scikits_dae_solver.py
pybamm/solvers/scikits_ode_solver.py
pybamm/solvers/scipy_solver.py
tests/unit/test_solvers/test_algebraic_solver.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_casadi_algebraic_solver.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

- Allow passing extra options to solvers (Fixes #850)
- Allow symbolic inputs in initial conditions (Fixes #967)
- Reuses algebraic solvers to calculate initial conditions

Issue 850 solver options

---

CHANGELOG.md
pybamm/models/base_model.py
pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
pybamm/models/submodels/current_collector/effective_resistance_current_collector.py
tests/unit/test_models/test_submodels/test_current_collector/test_effective_current_collector.py

Makes `CasadiSolver` the default for DAE models
Fixes #977 

#977 make casadi solver default

---

CHANGELOG.md
pybamm/parameters_cli.py

The doctest in `parameters_cli.list_parameters` sometimes fails due to the output of `os.walk` being in different order than the expected output. Adding `sorted(package_dirs)` when printing the output ensures the consistency of the output. 
The output of the test before this bug fix was:
```bash
Warning, treated as error:
**********************************************************************
File "../pybamm/parameters_cli.py", line ?, in default
Failed example:
list_parameters(["lithium-ion", "anodes"])
Expected:
Available package parameters:
* graphite_Ecker2015
* graphite_Chen2020
* graphite_mcmb2528_Marquis2019
* graphite_UMBL_Mohtat2020
* graphite_Kim2011
Available local parameters:
Got:
Available package parameters:
* graphite_Chen2020
* graphite_Ecker2015
* graphite_Kim2011
* …
```

Doctests failing due to mismatch in unsorted output.

---

.github/workflows/test_on_push.yml
CHANGELOG.md

The cron job is incorrectly set. 
The scheduled job was set using the obscure cron syntax as `* 3 * * *` which aparently means `“At every minute past hour 3.”`  when the correct value should have been `0 3 * * *` , which is `“At 03:00.”` . 
Fixes # None

Schedule testing is running too often

---

.github/workflows/test_on_push.yml
CHANGELOG.md

Enable triggering of GitHub Actions on PR.
Fixes #1012

Trigger GitHub Actions on PR

---

pybamm/simulation.py
tests/unit/test_simulation.py

Add a case to the simulation to catch simulating an already discretised model
Fixes #1023 

#1023 add case for already discretised model

---

pybamm/expression_tree/variable.py
pybamm/simulation.py
pybamm/solvers/base_solver.py
pybamm/solvers/processed_variable.py
pybamm/solvers/solution.py
tests/integration/test_solvers/test_solution.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_solution.py

Some bug fixes to `Solution` and `ProcessedVariable` to allow plotting when solving a simulation with external variables
Fixes #1024 

#1024 fix external variables

---

CHANGELOG.md
pybamm/plotting/quick_plot.py

Fixes issue in notebooks where slider didn't update. Problem was the timescale in `plot` (the sliders update ok in notebook when the timescale is seconds). It worked in scripts as that called `slider_update` rather than `plot`
Fixes #1037

#1037 fix timescale

---

.github/workflows/build_wheels_and_publish.yml

Upload wheels to regular PyPI index instead of TestPyPI.

Upload wheels to regular pypi

---

setup.py

For mysterious reasons, the readme disappeared from the `setup.py`.
This adds it back as the `long_description` entry.

Fix description in setup script

---

CHANGELOG.md
pybamm/__init__.py
pybamm/plotting/quick_plot.py
tests/unit/test_quick_plot.py

Fixes a bug where 2D variables that depend on y and z are transposed in `QuickPlot`. 
This was introduced in PR #1020 where the way 2D (y,z) variables are processed was changed, and I missed updating in quickplot as the scripts I had been using for 2+1D models all did the plotting manually... sorry!
Fixes #1051 

#1051 fix 2D plot bug

---

CHANGELOG.md
examples/scripts/compare_lithium_ion.py
pybamm/expression_tree/array.py
pybamm/expression_tree/interpolant.py
pybamm/expression_tree/operations/convert_to_casadi.py
pybamm/expression_tree/symbol.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py

#1066 add numpy function sqrt, sin, cos and exp to convert_to_casadi

---

CHANGELOG.md
pybamm/plotting/quick_plot.py

Fixes plots of variables discretised using FEM (y,z) in quickplot 
Fixes #1077 

#1077 update quickplot for fem

---

CHANGELOG.md
pybamm/models/full_battery_models/base_battery_model.py
tests/integration/test_solvers/test_solution.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py
tests/unit/test_simulation.py

Update the default variable points
Fixes #1075 

#1075 update default var pts

---

CHANGELOG.md
pybamm/solvers/processed_variable.py
tests/unit/test_quick_plot.py

Fixed the interpolator for 2D processed variables so it can be evaluated at the boundaries of the domain.
Fixes #1087

Issue 1087 endpoints interpolate 2D

---

CHANGELOG.md
pybamm/models/submodels/interface/sei/interstitial_diffusion_limited.py

Fixes a bug in `interstitial_diffusion_limited.py`
Fixes #1096 

#1096 fix sei typo

---

CHANGELOG.md
examples/notebooks/Getting Started/Tutorial 3 - Basic plotting.ipynb
pybamm/simulation.py
tests/unit/test_simulation.py

Allows users to pass keyword arguments to `Simulation.plot()`. For a full list of possible keyword arguments see `QuickPlot`.
Also renames `quick_plot_vars`  to `output_variables` in `Simulation` to be consistent with `QuickPlot`
Fixes #1084 

#1084 allow kwargs to be passed to sim.plot

---

pybamm/solvers/jax_bdf_solver.py

#1105 use approximated step size for D and c calculation

---

CHANGELOG.md
examples/scripts/compare-dae-solver.py
pybamm/solvers/base_solver.py
pybamm/solvers/jax_bdf_solver.py
pybamm/solvers/jax_solver.py
tests/unit/test_solvers/test_jax_bdf_solver.py
tests/unit/test_solvers/test_jax_solver.py

- adds mass matrix support for jax bdf solver, so it can solve semi-explicit dae models
- also adds sensitivity support for ODE and semi-explicit DAE models using the adjoint method
- limitations: currently limited to support for index 1 semi-explicit dae models, but this includes spm, spme and dfn models (that I've tested)
- while doing this, the bdf solver has been substantially refactored to remove lax.cond operators (which are slow), which also has the benefit of making the code more readable
Fixes #1104 

Issue 1104 mass matrix for bdf

---

examples/scripts/DFN.py
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

Fix setting a FunctionParameter with an InputParameter
Fixes #1110 

#1110 fix bug

---

CHANGELOG.md
pybamm/simulation.py
pybamm/solvers/base_solver.py
tests/unit/test_simulation.py

If a solver sees a list of length 2 for t_eval, change it to linspace
Fixes #1108 

#1108 change t_eval list to linspace

---

examples/notebooks/Getting Started/Tutorial 4 - Setting parameter values.ipynb
examples/notebooks/change-input-current.ipynb
examples/scripts/drive_cycle.py
pybamm/simulation.py
tests/unit/test_simulation.py

Added examples in the corresponding notebooks on how to pass a custom drive cycle to PyBaMM. Given that it is a change in the examples only, I didn't add any line to CHANGELOG.
Fixes #1056

#1056 added examples on how to pass custom drive cycle

---

.github/workflows/build_wheels_and_publish.yml
.github/workflows/test_on_push.yml
docs/install/GNU-linux.rst
docs/install/windows.rst

Casadi now works with python 3.8, so pybamm should too. This PR updates the tests and install docs.

now works with python 3.8

---

CHANGELOG.md
pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py

Fixes the bug with the potential on half-cell models
Fixes #1132 

Fix half cell bug

---

pybamm/solvers/jax_bdf_solver.py

#1170 change jnp.max and min to maximum and minimum

---

examples/notebooks/Creating Models/2-a-pde-model.ipynb
examples/notebooks/Creating Models/3-negative-particle-problem.ipynb
examples/notebooks/Creating Models/4-comparing-full-and-reduced-order-models.ipynb

Change boundary condition type in "Creating Models" notebooks, which were incorrectly given as Dirichlet but are in fact Neumann.
Note that this change does not affect the final result of any of the notebooks; the fact that the result is independent of boundary condition type is probably a bug. See also #1174.
I have one failing test (test_add_rm_param) and one which errors (test_edit_param), but on my system this is the case prior to this PR too.

Fix boundary condition types

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_spatial_methods/test_finite_volume/test_finite_volume.py

The code now raises an error if the boundary condition at the origin in a sphere geometry is other than a no-flux condition.
Fixes #1174

Issue 1174 raise error bcs sphere other than no-flux

---

run-tests.py

Since roughly a couple of days ago (11/10/2020) all tests on Windows for python 3.7 and 3.8 have been failing because numpy cannot be imported
After investigating this i've found that, in the case of both python versions, tests are executed with the base python interpreter on the GitHub runner, and not the one corresponding to the virtual environment created by Tox.
Before running tests, Tox first create a virtual environment in which PyBaMM is installed.
Moreover, in `run-tests.py`, the test suite is ran inside a a separate Python process:
```python
print("Running {} tests with executable '{}'".format(folder, interpreter))
cmd = [interpreter, "-m", "unittest", "discover", "-v", tests]
p = subprocess.Popen(cmd)
```
It just happens that with the value of `interpreter` being `"python"`, the …

Enforce python interpreter in process spawned by test runner

---

CHANGELOG.md
examples/scripts/conservation_lithium.py

Added an example script for lithium conservation.
Fixes #1185

Added example conservation

---

CHANGELOG.md
pybamm/expression_tree/functions.py
pybamm/expression_tree/operations/convert_to_casadi.py
tests/unit/test_expression_tree/test_functions.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py

Added Erf and Erfc functions
Fixes #1183 

#1183 added erf and erfc

---

docs/install/install-from-source.rst
tox.ini

Just a couple of fixes regarding documentation
1. There was a misleading typo in the installation notes. When installing from source (using Tox), the development env. created by Tox on Windows is called `windows-dev` and not `dev`.
2. The `B` switch to `sphinx-autobuild` appears to have been deprecated and replaced by `--open-browser`.

Minor fixes regarding documentation

---

tox.ini

Install `scikits.odes` when running `tox -e coverage`.
Before merging it would be good that coverage installs all the dependencies required though.

Install scikits in coverage tox

---

build_manylinux_wheels/entrypoint.sh

While testing building Python 3.8 wheels for #1197 , I noticed that any python 3.7 command (including `pip`) inside the manyinux image would fail, preventing any GNU/Linux wheel to be built.
```
opt/_internal/cpython-3.7.7/bin/python3.7: error while loading shared libraries: libcrypt.so.2: cannot open shared object file: No such file or directory
```
see for instance https://github.com/tlestang/PyBaMM/runs/1259747579?check_suite_focus=true
After pulling my hair out for a while, I noticed that - on the GitHub runner - the `docker run`
command is ran with a `-e LD_LIBRARY_PATH` option, effectively overriding the value of `LD_LIBRARY_PATH` set by default in the image. This efault value includes `/usr/local/lib`, where `libcrypt.so.2` lives.
Strangely, this was not an issue before (the `-e` …

Set LD_LIBRARY_PATH in image's entry point

---

.github/workflows/build_wheels_and_publish.yml
build_manylinux_wheels/entrypoint.sh

Since version 2.4, PyBaMM doesn't offer a Python wheel for GNU/Linux machines.
This corresponds to the time when we enabled support for Python 3.8.
For the record, installing PyBaMM 2.4 from PyPI on a Linux machine is possible, but
the package is not importable:
```
>>> import pybamm
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/tmp/env/lib/python3.8/site-packages/pybamm/__init__.py", line 105, in <module>
from .expression_tree.operations.evaluate import (
File "/tmp/env/lib/python3.8/site-packages/pybamm/expression_tree/operations/evaluate.py", line 13, in <module>
import jax
ModuleNotFoundError: No module named 'jax'
```
Here's why:
On GNU/Linux, running
```
pip install pybamm
```
will send a request to PyPI to get the latest version of PyBaMM (2.4.post2 …

Build manylinux wheels for Python 3.8

---

pybamm/models/full_battery_models/base_battery_model.py

Some extra variables for the ecm model based on using pybamm in an external equivalent circuit model

Add ECM variables

---

examples/scripts/compare_comsol/compare_comsol_DFN.py
pybamm/models/base_model.py
pybamm/solvers/base_solver.py
pybamm/solvers/processed_variable.py
pybamm/solvers/solution.py
tests/unit/test_solvers/test_base_solver.py

Previously models would not evaluate timescales if they are functions of input parameters. If an input parameter doesn't change during a solution but was created for purposed of reusing models with different input parameters then it should result in consistent scaling and should be allowed. To address the problem the scaling are saved to the solution and used here for processed variables. A check is made when stepping that the inputs that affect scaling do not change
You can run all three at once, using `$ python run-tests.py …

Put evaluated timescale and length_scales on solution

---

examples/scripts/SPMe_step.py
pybamm/solvers/casadi_solver.py

Make sure when stepping that a None solution is not appended to when event is triggered
Fixes # 1212

Casadi solver step bugfix

---

.github/workflows/test_on_push.yml

This workaround allows the macos tests to work until the issue with GitHub actions. This change can be reverted once [this PR](https://github.com/actions/virtual-environments/pull/1808) is merged.

Workaround for macos brew update error

---

.github/workflows/build_wheels_and_publish.yml

PR #1214 only modified the test workflow, but the `brew update` issue is also affecting the publishing workflow in the same way.
This is basically a duplicate of #1214

Apply workaround for brew update in publishing workflow

---

.github/workflows/build_wheels_and_publish.yml
.github/workflows/test_on_push.yml
build_manylinux_wheels/entrypoint.sh
run-tests.py
setup.py

Enabling and triggering the build of Python 3.8 wheels for GNU/Linux platforms.
This is effectively applying to master the changes applied to develop with #1197 and #1198

[master] Add manylinux wheels for python 3.8

---

CHANGELOG.md
pybamm/input/parameters/lithium-ion/separators/separator_Ecker2015/parameters.csv

#1224 add missing parameters

---

CHANGELOG.md
pybamm/input/parameters/lithium-ion/separators/separator_Ecker2015/parameters.csv
pybamm/models/submodels/interface/sei/ec_reaction_limited.py
pybamm/models/submodels/interface/sei/reaction_limited.py

Avoid try-except block which was causing the EC SEI submodel to slow down because of the levenshtein ratio search
Fixes #1225 

Issue 1225 slow sei model

---

CHANGELOG.md
pybamm/simulation.py
tests/unit/test_simulation.py

Use evaluated timescale from solution when doing sim solve
Fixes #1217 

fix sim.t_eval when timescale is function of input

---

.github/workflows/build_wheels_and_publish.yml
.github/workflows/test_on_push.yml

The issue with `brew update` on GitHub Actions has been fixed so the workaround can be reverted. It works fine with the PR workflow, I assume it will be fine with the publish workflow.

Revert workaround macos errors

---

CHANGELOG.md
pybamm/plotting/quick_plot.py
tests/unit/test_quick_plot.py

Quickplot now uses timescale and lengthscale evals from the solution instead of evaluating them.
Fixes # 1233

make quickplot use scaling from solutions

---

pybamm/__init__.py
pybamm/expression_tree/operations/evaluate.py
pybamm/solvers/jax_solver.py
tests/unit/test_expression_tree/test_operations/test_evaluate.py

`EvaluatorJax` uses a custom COO sparse matrix class and implements mat-vec multiply, as an alternative to converting everything to dense matrices
Fixes #1235 

Issue 1235 jax sparse mat vec

---

examples/notebooks/models/thermal-models.ipynb

initial conditions in the text were written as prescribing the time derivative of the temperature instead of the temperature...

fix typo in initial conditions

---

build_manylinux_wheels/Dockerfile

Building of manylinux wheels inside the manylinux2010 image breaks because the package repos are off following CentOS 6 reaching its end of life on November, 30th. See https://github.com/pypa/manylinux/issues/836
This updates the Dockerfile, to use the manylinux2014 image instead, based on CentOS 7.

[>master] Switch to manylinux2014

---

CHANGELOG.md
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EC_DMC_1_1_Landesfeind2019/electrolyte_TDF_EC_DMC_1_1_Landesfeind2019.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EC_DMC_1_1_Landesfeind2019/electrolyte_transference_number_EC_DMC_1_1_Landesfeind2019.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EC_EMC_3_7_Landesfeind2019/electrolyte_TDF_EC_EMC_3_7_Landesfeind2019.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EC_EMC_3_7_Landesfeind2019/electrolyte_transference_number_EC_EMC_3_7_Landesfeind2019.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EMC_FEC_19_1_Landesfeind2019/electrolyte_TDF_EMC_FEC_19_1_Landesfeind2019.py
pybamm/input/parameters/lithium-ion/electrolytes/lipf6_EMC_FEC_19_1_Landesfeind2019/electrolyte_transference_number_EMC_FEC_19_1_Landesfeind2019.py
pybamm/models/full_battery_models/lead_acid/basic_full.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py
pybamm/models/submodels/electrolyte_diffusion/composite_diffusion.py
pybamm/models/submodels/electrolyte_diffusion/first_order_diffusion.py
pybamm/models/submodels/electrolyte_diffusion/full_diffusion.py
pybamm/models/submodels/electrolyte_diffusion/leading_order_diffusion.py
pybamm/parameters/lead_acid_parameters.py
pybamm/parameters/lithium_ion_parameters.py
tests/unit/test_models/test_submodels/test_electrolyte_diffusion/test_leading_order_diffusion.py

The transference number `t_plus` is now a function of both electrolyte concentration and temperature. For lead-acid, the temperature dependence is ignored, as it happened with the other parameters.
Fixes #1063 

Issue 1063 tplus temperature dependent

---

.github/workflows/test_on_push.yml

Looks like our issue with the MacOs tests evolved and now it doesn't randomly fail anymore. I have found that adding solves it 
`brew unlink gcc@8 gcc@9` (I hope it doesn't break anything down the line...).

Fix GitHub actions MacOS

---

pybamm/expression_tree/operations/evaluate.py
pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_scipy_solver.py
tox.ini

This defines the two methods `__getstate__` and `__setstate__` that can be used to control what is pickled when pickling a class
instance, as well as what happens when the object in unpickled.
In this case this is useful to avoid pickling the `_evaluate` attribute, which is a reference to a function that cannot be pickled.
This attribute is restored when unpicking by re-compiling the definition of the function `evaluate`. 
Note that this does _not_ make it possible to pickle model in "jax" format.
Fixes #1283 #734 
You can run all three at …

Enable pickling of models in "python" format

---

CHANGELOG.md
pybamm/solvers/casadi_solver.py
tests/unit/test_solvers/test_casadi_solver.py

Added a check before running `np.concatenate` to avoid the error.
Fixes #1320 

Issue 1320 casadi error extrap events

---

build_manylinux_wheels/Dockerfile

Building of manylinux wheels inside the manylinux2010 image breaks because the package repos are off following CentOS 6 reaching its end of life on November, 30th. See pypa/manylinux#836
This updates the Dockerfile, to use the manylinux2014 image instead, based on CentOS 7.

Switch to manylinux2014

---

examples/scripts/cycling_ageing_yang.py
pybamm/discretisations/discretisation.py
pybamm/logger.py
pybamm/models/full_battery_models/base_battery_model.py
pybamm/parameters/parameter_values.py
pybamm/simulation.py
pybamm/solvers/base_solver.py
tests/unit/test_logger.py

Add new logging levels and make the logging cleaner for when running an experiment. The output now looks like this:
```
2021-01-23 18:30:48,697 - [INFO] base_battery_model.build_model(632): Start building Doyle-Fuller-Newman model
2021-01-23 18:30:48,771 - [INFO] base_battery_model.build_model(659): Finish building Doyle-Fuller-Newman model
2021-01-23 18:30:48,791 - [INFO] replace_symbols.process_model(39): Start replacing symbols in Doyle-Fuller-Newman model
2021-01-23 18:30:48,844 - [INFO] replace_symbols.process_model(110): Finish replacing symbols in Doyle-Fuller-Newman model
2021-01-23 18:30:48,845 - [INFO] parameter_values.process_model(352): Start setting parameters for Doyle-Fuller-Newman model
2021-01-23 18:30:48,937 - [INFO] parameter_values.process_model(443): Finish setting …
```

#1332 add more logging levels

---

CHANGELOG.md
pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_scikits_solvers.py
tests/unit/test_solvers/test_scipy_solver.py

Return the solution as well as the termination reason in `get_termination_reason`. This is so that the updated solution (`solution = solution + event_sol`) which includes the event state gets returned by the solver.
Fixes #1343 

#1343 update get_termination_reason to return solution

---

setup.py

`pip install pybtex` installs an unnecessary `tests` directory which messes up running some of the tests in pybamm individually.
This change removes that directory when it is installed via setup.py

add lines to remove 'tests' from site-packages in setup.py

---

pybamm/solvers/base_solver.py

I previously updated the logger info so that when calling `solve` for a list of inputs it didn't print the termination reason (since it may be different for each set of inputs). At the same time I changed it so that it returned the sum of the integration, solve and total times. This was the wrong thing to do as it gives the impression that the call to `solve` to ~N times as long as it actually did (for a list on N inputs). I've reverted it back to just print a single set up, solve and total time (note all solutions get given the same solve time, see https://github.com/pybamm-team/PyBaMM/pull/1261). I also removed the integration time info from the logger in this case since it is also different for each set of inputs. Users can still access the integration time for each solution in the …

update logging info for solutions list

---

.github/workflows/benchmark_on_PR.yml

_This comes on top of #1334 (Nightly benchmarks with asv).
Better to first review and merge #1334 then review this PR._
This adds a new GitHub action workflow `Run benchmarks on PR` (`benchmark_on_PR.yml`) that runs each time a pull request is opened and reports any performance regression compared to the tip of the base branch of the PR.
This workflow uses [airspeed velocity](https://asv.readthedocs.io/en/stable/) to run the benchmark suite for both the new commit and the tip of the base branch for the PR. If any of the benchmark run results in a performance regression of more than 10% compared to the base commit, the workflow reports a failure. Here "performance" means wall-clock time. The value of 10% for the regression ratio is arbitrary, and can be tuned at will.
I manually tested …

Check for any performance regression on pull request

---

pybamm/CITATIONS.txt
pybamm/spatial_methods/spectral_volume.py

Added the automated reference for Spectral Volumes to CITATIONS.txt. I'm sorry for just realizing now that I forgot it initially.
Should have been part of the merge for issue #900.
Minor (no entry in CHANGELOG.md necessary).

Spectral volume reference

---

CHANGELOG.md
pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/submodels/electrolyte_conductivity/base_electrolyte_conductivity.py
pybamm/models/submodels/electrolyte_conductivity/full_conductivity.py
pybamm/models/submodels/electrolyte_conductivity/surface_potential_form/full_surface_form_conductivity.py
tests/unit/test_models/test_submodels/test_electrolyte_conductivity/test_full_conductivity.py
tests/unit/test_models/test_submodels/test_electrolyte_conductivity/test_surface_form/test_full_surface_form_conductivity.py

Added the electrolyte overpotential and ohmic losses to the full_conductivity model.
Fixes #1349 

Electrolyte overpotentials

---

.github/workflows/benchmark_on_PR.yml
.github/workflows/test_on_push.yml
tox.ini

Since 03/02/2021 the scheduled "PyBaMM" workflow fails on mac for all python versions.
See https://github.com/pybamm-team/PyBaMM/actions/runs/532703527
The logs indicate that CMake cannot find the fortran compiler, and therefore Sundials isn't compiled... and the installation of scikits.odes fails.
Until a solution is found, this disables the compilation of sundials, as well as the installation of scikits.odes, on macos.

Disable compilation of sundials and scikits.odes on mac

---

.all-contributorsrc
pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
pybamm/models/full_battery_models/lithium_ion/base_lithium_ion_model.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py
pybamm/models/submodels/current_collector/effective_resistance_current_collector.py

Changes the "current collector y" length scale from `L_y` to `L_z`. This is because both the y- and z-directions should be scaled with `L_z` when non-dimensionalising (otherwise there is an awkward extra factor of `L_y/L_z` in the 2D Laplacian for the current collector problem).
Fixes #1363 

Issue 1363 length scale bug

---

CONTRIBUTING.md

Add a section about running benchmarks with `asv` as well as adding new benchmarks.
Update the section on CI to mention GitHub actions instead of Travis CI

Update contibuting guidelines

---

.github/workflows/benchmark_on_push.yml

Merges are also push events and therefore the benchmark_on_push workflow also runs for merge commits.
So needed to add a condition to avoid fetching the develop branch when workflow runs for a merge commit on develop.

Make benchmark_on_push pass for merge commits on develop

---

examples/scripts/custom_model.py
pybamm/citations.py
pybamm/geometry/half_cell_geometry.py
pybamm/input/parameters/lithium-ion/negative_electrodes/graphite_Chen2020_plating/graphite_LGM50_diffusivity_Chen2020.py
pybamm/models/submodels/interface/lithium_plating/base_plating.py
pybamm/parameters/lithium_ion_parameters.py
pybamm/parameters/parameter_sets.py
pybamm/solvers/jax_bdf_solver.py
tests/integration/test_models/standard_model_tests.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_parameters/test_lead_acid_parameters.py
tests/unit/test_parameters/test_lithium_ion_parameters.py
tests/unit/test_parameters/test_parameter_values.py

I found various formatting and styling mistakes so I ran `black .` and `flake8`

run black and flake8

---

pybamm/models/full_battery_models/base_battery_model.py

To address #1377, this removes the OCV (difference between current OCV and initial OCV) from the definition of the `Local ECM resistance`. The `Change in measured open circuit voltage` variable is left untouched.
Fixes #1377
Same plot as in #1377, after change:

Remove OCV from ECM resistance definition

---

CONTRIBUTING.md
docs/index.rst

A simple documentation fix replacing ```Binder``` with ```Google Colab```. I searched in the documentation and there were only 2 such occurrences I could find. I could not find any configuration files for Google Colab, if there is one or if any changes are required in this PR, please let me know. Thank you! 
Fixes #1390 
Changed Docs ( CONTRIBUTING.md and docs/index.rst )

Replaced all occurrences of 'Binder' with 'Google Colab'

---

CHANGELOG.md
CONTRIBUTING.md
pybamm/simulation.py
tests/integration/test_experiments.py

Makes it so that simulations stop when an experiment becomes infeasible 
Fixes #1393 

#1393 end simulation when experiment infeasible

---

pybamm/models/full_battery_models/base_battery_model.py

1. Added description for 'operating mode' parameter in BaseBatteryModel class.
2. Deleted '\\' from some lines to format the displayed output. With '\\', the output was behaving weirdly as displayed in the screenshot below (The line, where "average"  is described, was breaking up with huge spaces in between).
Please let me know if you want any changes or additions in the PR. Thanks!
Fixes #1388 
Doc string addition

Added 'operating mode' to the doc string of BaseBatteryModel class

---

CHANGELOG.md
pybamm/models/submodels/electrode/base_electrode.py

Fixed the sign in the definition of positive electrode overpotential.
Fixes #1406

#1406 fixed bug with positive electrode ohmic losses

---

pybamm/models/base_model.py
pybamm/solvers/casadi_algebraic_solver.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Fix a bug in the function to update a model from initial conditions (wrong order for a 2D variable)
Fixes #1414 

#1414 fix bug in set_initial_conditions_from

---

pybamm/parameters/parameter_values.py

I didn't open an issue since this is such a tiny change: in the constructor of `ParameterValues`, if the `values` argument is neither `None` nor a string, the `path` argument that is fed to `ParameterValues.update` is set to `None`. However this is incorrect as that method expects it to be a string; passing `None` will lead to a `ValueError` in `os.path.join`.
This happened to me when creating a dictionary of parameter values where one value was `[function]/absolute/path/to/function`. With this fix, it works.

Wrong argument type in `ParameterValues.update`

---

CHANGELOG.md
pybamm/models/submodels/interface/lithium_plating/base_plating.py
pybamm/models/submodels/particle/fickian_many_particles.py
pybamm/models/submodels/particle/fickian_single_particle.py
tests/integration/test_models/standard_model_tests.py
tests/integration/test_models/standard_output_tests.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_dfn.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_spm.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_spme.py

Changed how `D` is evaluated at the boundary condition to ensure that mass is conserved. I also changed some of the `standard_output_tests` to catch when mass is not conserved (before it didn't) and fixed some others.
Fixes #1420 

Fixed bcs for the particle models

---

pybamm/solvers/idaklu_solver.py

Added warning to Idaklu solver if the model is converted to the format "casadi". 
A question - should I add
```py
if self.root_method != "CasadiAlgebraicSolver":
```
condition before adding the warning?
I also looked in the unit tests directory but couldn't find a suitable place for adding any sort of test for this warning (Please let me know where to put the test, if it is required)
Fixes #887 

Added warning for 'casadi' format

---

CHANGELOG.md
docs/index.rst
docs/source/batch_study.rst
docs/source/models/base_models/base_battery_model.rst
docs/source/models/index.rst
examples/notebooks/Getting Started/Tutorial 4 - Setting parameter values.ipynb
pybamm/__init__.py
pybamm/batch_study.py
pybamm/models/full_battery_models/base_battery_model.py
tests/unit/test_batch_study.py

Add class to compare different models and conditions
Fixes #906 

add BatchStudy class

---

pybamm/experiments/experiment.py
tests/unit/test_experiments/test_experiment.py

The experiment.py file is modified to read the operating conditions string which includes the type of driving cycle ('A', 'V', 'W').
This change is suggested by @tinosulzer in #1193. 

Type of Driving Cycle ('A', 'V', 'W') in Experiment Class

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
pybamm/plotting/plot.py
pybamm/plotting/plot2D.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_plotting/test_plot.py

`ParameterValues.evaluate()` can now return arrays so that you can evaluate parameter functions as 
```python3
import pybamm
params = pybamm.ParameterValues(chemistry=pybamm.parameter_sets.Chen2020)
i0 = params["Negative electrode exchange-current density [A.m-2]"]
x = pybamm.linspace(3000,6000,100)
params.evaluate(i0(1000,x,300))
```
Also, `plot` and `plot2D` now take and return the axis `ax` for easier customization
. 
Fixes #1465 

#1465 allow evaluate parameter to return arrays

---

docs/source/expression_tree/binary_operator.rst
pybamm/expression_tree/array.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/scalar.py
pybamm/parameters/base_parameters.py
pybamm/solvers/base_solver.py
tests/unit/test_expression_tree/test_array.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_scalar.py
tests/unit/test_expression_tree/test_symbol.py

- Add `to_equation` in Scalar, Binary Operators and Array
- Change `Heaviside` to `_Heaviside`
- Add tests

Add to_equation in Binary and Scalar

---

CHANGELOG.md
pybamm/models/full_battery_models/lithium_ion/__init__.py
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py
tests/unit/test_simulation.py

Add function to set initial soc in a simulation
Fixes #1511 

#1511 add function for initial soc

---

CHANGELOG.md
pybamm/models/base_model.py
pybamm/models/submodels/current_collector/effective_resistance_current_collector.py
pybamm/models/submodels/current_collector/quite_conductive_potential_pair.py
tests/unit/test_models/test_base_model.py

Remove the check "each variable in the algebraic eqn keys must appear in the eqn"
Fixes #1507 

#1507 remove algebraic equation check

---

pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/parameter.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
pybamm/expression_tree/variable.py
tests/unit/test_expression_tree/test_parameter.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_expression_tree/test_unary_operators.py
tests/unit/test_expression_tree/test_variable.py

- Add to_equation in FunctionParameter, Symbol, UnaryOperator, Gradient, Divergence and Variable
- Make to_equation SPM compatible
- Add tests

Add to_equation for SPM

---

pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py
pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_basic_models.py

Allows BasicDFNHalfCell to work with the Simulation class, and fixes a bug where an option `build` is no longer supported in the base_battery_model.

Issue 1504 half cell simulation

---

pybamm/expression_tree/printing/print_name.py
tests/unit/test_expression_tree/test_printing/test_print_name.py

Skip print_name setter for `new_copy`
Fixes #1540 

Skip print_name setter

---

CHANGELOG.md
examples/scripts/DFN.py
pybamm/models/submodels/active_material/base_active_material.py
pybamm/models/submodels/electrolyte_diffusion/base_electrolyte_diffusion.py
pybamm/models/submodels/particle/base_particle.py
pybamm/solvers/solution.py

#1547 fix esoh model in pouch cell

---

CHANGELOG.md

When running scripts through spyder on windows (at least this is what I tested) if you press run twice there is an importlib KeyError. The kernel had to be restarted to fix the issue. Adding empty __init__files to parameter subfolders fixes the issue
Fixes #1479

add empty inits to parameters subfolders

---

README.md
pybamm/CITATIONS.txt
pybamm/citations.py
pybamm/input/parameters/lithium_ion/cells/Enertech_Ai2020/parameters.csv
pybamm/models/submodels/current_collector/effective_resistance_current_collector.py
pybamm/models/submodels/current_collector/potential_pair.py
pybamm/models/submodels/electrolyte_conductivity/integrated_conductivity.py
pybamm/models/submodels/thermal/lumped.py
pybamm/models/submodels/thermal/pouch_cell/pouch_cell_1D_current_collectors.py
pybamm/models/submodels/thermal/pouch_cell/pouch_cell_2D_current_collectors.py
pybamm/models/submodels/thermal/x_full.py
pybamm/parameters/lithium_ion_parameters.py
pybamm/spatial_methods/finite_volume.py
tests/unit/test_citations.py

Fixed a couple of typos and updated three references that have now been published (Timms2021, Sulzer2021 and BrosaPlanella2021).
Fixes #1562
Very minor style fix, not included in the CHANGELOG

Update citations and fix typos

---

pybamm/simulation.py
tests/unit/test_simulation.py

Update the stored parameter_values dicts on the simulation when running experiments to set the initial soc
Fixes #1561

Get initial_soc working as simulation solve argument with experiments

---

pybamm/__init__.py
pybamm/expression_tree/operations/evaluate_python.py
setup.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_dfn.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_spm.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_spme.py
tests/unit/test_citations.py
tests/unit/test_expression_tree/test_operations/test_evaluate_python.py
tests/unit/test_solvers/test_jax_bdf_solver.py
tests/unit/test_solvers/test_jax_solver.py
tests/unit/test_solvers/test_scipy_solver.py

Skip jax when running ARM64 on Mac M1 (complicated install process, causes pybamm to crash)

skip jax on arm

---

docs/conf.py

Try removing scipy from intersphinx. I don't think we cross-ref scipy anywhere anyway
Fixes #1584 

#1584 comment out scipy for now

---

docs/source/models/submodels/external_circuit/function_control_external_circuit.rst
examples/scripts/DFN.py
pybamm/experiments/experiment.py
pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/submodels/external_circuit/__init__.py
pybamm/models/submodels/external_circuit/current_control_external_circuit.py
pybamm/models/submodels/external_circuit/function_control_external_circuit.py
pybamm/simulation.py
pybamm/solvers/base_solver.py
tests/integration/test_models/test_submodels/test_external_circuit/test_function_control.py
tests/unit/test_experiments/test_experiment.py
tests/unit/test_experiments/test_simulation_with_experiment.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_spm.py
tests/unit/test_models/test_submodels/test_external_circuit/test_function_control.py

Issue 1611 cccv

---

.github/workflows/build_sdist.yml

Add a workflow to build and publish PyBaMM's python source distribution on PyPI for Windows (.zip) and Unix (.tar.gz)

Build and publish python sdist on PyPI

---

vcpkg-configuration.json

The current `vcpkg-configuration.json` file causes the vcpkg install to fail. `vcpkg` looks for `sundials` inside the builtin registry instead of the alternative registry at [sundials-vcpkg-registry ](https://github.com/pybamm-team/sundials-vcpkg-registry).
Explicitly specifying the builtin registry to act as the default seems to fix this. In my explorations I also updated the sundials registry, particularly the version keyword used in the various configuration files for the registry and sundials port. See
- [8269dd7b755268e4e0a8e01eb32bb1f140c643d6](https://github.com/pybamm-team/sundials-vcpkg-registry/commit/8269dd7b755268e4e0a8e01eb32bb1f140c643d6)
- [4285b3a438da55e7ee081b5dbdd56a736dd41330](https://github.com/pybamm-team/sundials-vcpkg-registry/tree/4285b3a438da55e7ee081b5dbdd56a736d …

Update vcpkg configuration

---

.github/workflows/build_sdist.yml
.github/workflows/build_wheels.yml

Add multi line if condition to trigger the workflow from a merge event in the main branch
Fixes #1663 
See test workflow run [here](https://github.com/priyanshuone6/PyBaMM/runs/3587866795?check_suite_focus=true)
(It skipped the pypi event and only ran the testpypi event from a merge because I added the multi-line condition to testpypi)

Add multi-line if condition in workflow

---

setup.py

Add CMakeBuild.py to package data

Add CMakeBuild to package data

---

CHANGELOG.md
pybamm/util.py
tests/unit/test_parameters/test_parameter_values.py

This allows importing parameters via chemistry that is in the local directory. I don't think this fixes importing parameters from other folders via chemistry. This is a much more complicated issue (I believe), but this fix should be enough for the workshop.
Fixes #1673 

Issue 1673 import parameters chemistry error

---

CHANGELOG.md
pybamm/util.py
setup.py
tests/unit/test_parameters/test_parameter_values.py

Fix the `load_function` bug on main branch.
Fixes #1673 

Fix load function

---

FindSuiteSparse.cmake

Fixed typo.
```
deafult -> default
```

Fix typo in FindSuiteSparse.cmake

---

pybamm/simulation.py
pybamm/solvers/solution.py

The `clear_casadi_attributes()` method in the `Solution` class doesn't do anything. Apparently the method is supposed to clear Casadi objects for pickling but this is not necessary since the `Solution` object can already be pickled. So I removed the `clear_casadi_attributes()` method and references to the method.

Remove empty method

---

CHANGELOG.md
pybamm/expression_tree/functions.py
tests/unit/test_expression_tree/test_functions.py

Overrode the `sympy` operator for `Exponential` and `Arctan`. I think the only left are `Max` and `Min` but not sure if we want to override them by the `Max` and `Min` from `sympy`.
Fixes #1785

#1785 override sympy operators exp and atan

---

CHANGELOG.md
pybamm/expression_tree/concatenations.py
tests/integration/test_models/standard_model_tests.py
tests/unit/test_expression_tree/test_concatenations.py
tests/unit/test_expression_tree/test_operations/test_evaluate_python.py

Issue 1768 concat

---

examples/scripts/experiment_drive_cycle.py
pybamm/experiments/experiment.py
pybamm/simulation.py
pybamm/solvers/base_solver.py

PR Status: (Work in Progress)
This PR provides the functionality of solving the drive cycle using the experiment only if the first input of the experiment is the drive cycle. 
Issues in PR:
- When two consecutive drive cycles are given in the experiment, only the first one solves but the second one only returns 0 current. 
- If the drive cycle is not the first input of the experiment, the drive cycle part only returns 0 current. 
Possible Cause of this Issue: 
The driving cycles are given to the solver as interpolant. I think there is an issue with the timing of the interpolant which I am unable to overcome. For example, The US06 Drive cycle data have time range [0:600], When the drive cycle is the first input of the experiment is drive cycle (solution start time = 0), the cycle is solved …

Solve Drive Cycle (A,V,W) in Experiment

---

.github/workflows/test_on_push.yml
CONTRIBUTING.md
run-tests.py
tox.ini

- Removed the code for "slow books"
- Speed up the CI by running unit tests only once (using coverage) on `ubuntu-latest` with Python `3.9`
- Run integration and unit tests separately on `ubuntu-latest`
Speeds up the CI by 15-30 mins!

Run tests once using coverage on `ubuntu-latest` with Python 3.9

---

.github/workflows/build_wheels.yml
docs/requirements.txt
pybamm/CITATIONS.txt
requirements.txt
setup.py
tox.ini

- Bump sympy version and format whitespaces by replacing tab with spaces
In github
versus in vscode
https://github.com/github/VisualStudio/issues/1524#issuecomment-437797198
https://github.com/Microsoft/vscode/issues/62935#issuecomment-437795366

Bump versions and format whitespaces

---

CHANGELOG.md
pybamm/expression_tree/operations/convert_to_casadi.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py

Update the casadi interpolant to use "linear" or "bspline" and raise an error for "pchip".
Fixes #1481 

#1481 update casadi interpolant

---

CHANGELOG.md
pybamm/expression_tree/operations/evaluate_python.py
pybamm/solvers/jax_bdf_solver.py
pybamm/solvers/jax_solver.py
pybamm/util.py
tests/unit/test_citations.py
tests/unit/test_expression_tree/test_operations/test_evaluate_python.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_idaklu_solver.py
tests/unit/test_solvers/test_jax_bdf_solver.py
tests/unit/test_solvers/test_jax_solver.py

If `jax` is already installed in an environment where the user updates `pybamm` to develop, importing `pybamm` gives the following error (as `jaxlib` is not available on windows but `jax` is) -
```
raise ModuleNotFoundError(
ModuleNotFoundError: jax requires jaxlib to be installed. See https://github.com/google/jax#installation for installation instructions.
```
Fixes #1801 

Added a condition for `jaxlib` imports

---

.github/workflows/build_wheels.yml

This should make the workflow to publish the wheels work as before (see details [here](https://github.com/actions/download-artifact/tree/v2#compatibility-between-v1-and-v2)).

fixed downloading of wheels

---

CHANGELOG.md
pybamm/simulation.py
tests/unit/test_simulation.py

Fixed the bug with simulations that had both a drive cycle and an initial SoC condition.
Fixes #1842

Fix bug simulations with drive cycle and initial_soc

---

pybamm/models/full_battery_models/base_battery_model.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py

If no option is provided for "particle mechanics" or "stress-induced diffusion" then the default stress-induced diffusion option is set based on the default particle mechanics option. For example, if the user sets up a model with stress-driven LAM
```python3
model = pybamm.lithium_ion.SPM({"loss of active material": "stress-driven"})
```
then the default particle mechanics option is automatically changed to "swelling only". In <= v21.10 stress-induced diffusion was hardcoded, so was automatically included with particle mechanics. As of v21.11 "stress-induced diffusion" is a separate option, so wasn't included in the above example. After this PR stress-induced diffusion _will_ be included in the above model since the default mechanics option has changed to "swelling only".
In summary the …

default stress-induced diffusion 

---

.github/workflows/test_on_push.yml
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py

The tests are passing locally but are failing on GitHub Actions (I don't really know why). `cosh` function was behaving weirdly, others are working fine -
```
<ufunc 'sqrt'>
1.73205 1.73205 0
<ufunc 'tanh'>
0.995055 0.995055 0
<ufunc 'cosh'>
10.0677 10.0677 1.77636e-15
```
Another workaround would be to remove the `cosh` function completely from this test.
Fixes #1882

Add a workaround for the failing tests

---

CHANGELOG.md
pybamm/solvers/base_solver.py
pybamm/solvers/processed_variable.py
tests/unit/test_solvers/test_casadi_solver.py

During the solver setup, the list of inputs/sensitivities is sorted by string and then used to assign elements of the y-array to each sensitivity. This applies the same sorting of the list before extracting the sensitivities during the process variables stage. 
I haven't added a test because I couldn't think of a good way without having a full integration test (passing a full model through the pipeline and then checking that the sensitivities are independent of the order of the inputs dictionary). However, I can add it if you think this is worth it for this. 
Fixes #1886 
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to …

#1886 added fix within processed variable

---

pybamm/expression_tree/operations/replace_symbols.py
pybamm/models/base_model.py
pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
pybamm/models/full_battery_models/lithium_ion/base_lithium_ion_model.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py
pybamm/models/full_battery_models/lithium_ion/basic_spm.py
pybamm/models/submodels/interface/base_interface.py
pybamm/models/submodels/particle/no_distribution/fickian_diffusion.py
pybamm/models/submodels/particle/no_distribution/polynomial_profile.py
pybamm/models/submodels/particle/no_distribution/x_averaged_fickian_diffusion.py
pybamm/models/submodels/particle/no_distribution/x_averaged_polynomial_profile.py
pybamm/models/submodels/particle/size_distribution/fickian_diffusion.py
pybamm/models/submodels/particle/size_distribution/uniform_profile.py
pybamm/models/submodels/particle/size_distribution/x_averaged_fickian_diffusion.py
pybamm/models/submodels/particle/size_distribution/x_averaged_uniform_profile.py
pybamm/parameters/lead_acid_parameters.py
pybamm/parameters/lithium_ion_parameters.py
pybamm/parameters/parameter_values.py
pybamm/solvers/base_solver.py
tests/integration/test_models/test_full_battery_models/test_lead_acid/test_compare_outputs.py
tests/integration/test_solvers/test_idaklu.py
tests/unit/test_models/test_base_model.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py
tests/unit/test_parameters/test_lithium_ion_parameters.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_plotting/test_quick_plot.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_base_solver.py

Fixes #1889 
`model.timescale` cannot be changed any more. `model._timescale` can in theory but users really shouldn't. Instead, the "timescale" option can be passed to the model. The simulation results are independent of this (new test added for this).

#1889 fix some parameter bugs and add timescale option

---

CHANGELOG.md
pybamm/solvers/solution.py
tests/unit/test_solvers/test_solution.py

- Allow `Solution.save_data()` to return a string if filename is None
- add extra `to_format` of json
Fixes #1906 

I1906 solution json

---

.github/release_checklist.md
.github/workflows/url_checker.yml
docs/conf.py
scripts/update_version.py

- The documentation build is still failing (https://readthedocs.org/projects/pybamm/builds/15835390/) as pybamm is just cloned and not installed to build docs
- Fix version and automate conf.py

Fix failing build

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
pybamm/expression_tree/averages.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/input_parameter.py
pybamm/expression_tree/operations/jacobian.py
pybamm/expression_tree/operations/replace_symbols.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
pybamm/parameters/parameter_values.py
pybamm/solvers/base_solver.py
tests/unit/test_expression_tree/test_input_parameter.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_solvers/test_scikits_solvers.py

It seems like we can get away with not using `anytree` when creating expression trees, which saves a fair amount of overhead. Functionality like `render` still works fine, as long as the symbol has a `children` attribute.
`Symbol.new_copy` no longer needs to be used, but I have left the functions there in case we need to go back.
Let's give it a couple of releases to be sure, but if things are working well without `anytree` we can also:
- remove `Symbol.id` and implement `__eq__` and `__hash__` instead (previously, these were not implemented to avoid loops in anytree)
- Simplify `model.new_copy` to just make shallow copies
I'll open an issue for that if this PR is approved.
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGE …

Remove anytree

---

.github/workflows/create_release.yml
.github/workflows/update_license.yml
.github/workflows/update_version.yml

The workflows are running as scheduled and are creating pull requests on forks. I even checked @Saransh-cpp's fork to confirm (See https://github.com/Saransh-cpp/PyBaMM/pulls?q=is%3Apr).
It will now fail release related workflows on forks.

Fail release workflows on forks

---

.github/release_checklist.md
.github/workflows/build_wheels.yml
vcpkg-configuration.json
vcpkg.json

The `wheel` file is not building for `windows` on `GitHub Actions` (https://github.com/pybamm-team/PyBaMM/runs/5023662038?check_suite_focus=true). The error -
```
[DEBUG] Downloading https://mirror.bit.edu.cn/msys2/mingw/i686/mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirror.selfnet.de/msys2/mingw/i686/mingw-w64-i686-gcc-fortran-10.2.0-1-any.pkg.tar.zst
[DEBUG] Download failed -- retrying after 1000 ms.
[DEBUG] Download failed -- retrying after 2000 ms.
[DEBUG] Download failed -- retrying after 4000 ms.
[DEBUG] Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/mingw/i686/mingw-w64-i686-gcc-fortran-10. …
```

Fix release

---

tests/unit/test_expression_tree/test_functions.py

Fix failing test by using a different function than interp1d.
The coverage bug remains, looking for a solution in #1933 

#1932 fix failing test

---

.github/codecov.yml
tests/unit/test_expression_tree/test_symbol.py
tox.ini

Changes coverage settings so that coverage fails if tests fail
Fixes #1932 

make coverage fail if ci fails

---

docs/install/install-from-source.rst

Replaced `quick` tox command with `unit` in `Install from source (developer install)` docs
Fixes #1946
.

quick=>unit

---

.github/workflows/build_wheels.yml

The error -
```
-- Running vcpkg install - done
CMake Error at CMakeLists.txt:18 (project):
Generator
Visual Studio 16 2019
could not find any instance of Visual Studio.
```
I found this StackOverflow answer - https://stackoverflow.com/a/61045418/14746647 - which seems to work as the error above is gone (the workflow running in my fork - https://github.com/Saransh-cpp/PyBaMM/runs/5363685867?check_suite_focus=true). But now we have a new error -
```
+ Download https://downloads.python.org/pypy/pypy3.7-v7.3.3-win32.zip to C:\cibw\pypy3.7-v7.3.3-win32.zip
Traceback (most recent call last):
File "C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\runpy.py", line 196, in _run_module_as_main
return _run_code(code, main_globals, None,
File …
```

Fix building wheels on windows

---

.github/workflows/build_wheels.yml
CHANGELOG.md
scripts/replace-cmake/sundials-3.1.1/CMakeLists.txt
scripts/replace-cmake/sundials-4.1.0/CMakeLists.txt
scripts/replace-cmake/sundials-5.0.0/CMakeLists.txt

Removed support for Windows 32-bits from workflows. Additionally, all the `CMakeLists.txt` files had some conditions for 32-bit windows, and I am not sure if they should be removed. The tests are passing when these lines are removed but I'll revert the deletions if they are supposed to stay.
https://github.com/pybamm-team/PyBaMM/blob/9f8f2c3fe769c15b9c4f1dca98eb6dbe07a587d1/scripts/replace-cmake/sundials-4.1.0/CMakeLists.txt#L322-L331 
Fixes #1955 

Remove 32 bits support

---

.github/ISSUE_TEMPLATE/bug_report.yml

Explicitly ask for a MWE in the bug reports.

Update bug_report.yml to ask for MWE

---

pybamm/experiments/experiment.py
pybamm/simulation.py
tests/unit/test_experiments/test_experiment.py
tests/unit/test_experiments/test_simulation_with_experiment.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_basic_models.py
tests/unit/test_simulation.py

Some inputs to the experiment have been marked as "deprecated, get in touch if you're using these" for a while. Nobody has commented, so this PR gets rid of those inputs

remove deprecated stuff

---

pybamm/discretisations/discretisation.py
pybamm/expression_tree/operations/replace_symbols.py
pybamm/models/base_model.py
pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/full_battery_models/lead_acid/basic_full.py
pybamm/models/full_battery_models/lithium_ion/basic_dfn.py
pybamm/models/full_battery_models/lithium_ion/basic_spm.py
pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
pybamm/parameters/parameter_values.py
pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_lead_acid/test_basic_models.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_basic_models.py

Remove `model.new_empty_copy()` and simplify `model.new_copy()`.
Not sure why I made it so complicated in the first place, but this seems to work fine and be faster

simplify model copy

---

docs/tutorials/add-model.rst

The " quantity " was mispelled as "quanitity" in [add-model.rst](https://github.com/pybamm-team/PyBaMM/blob/develop/docs/tutorials/add-model.rst).

Fixing some docs bug

---

CHANGELOG.md

Fix the `>>>>> develop` typo on the CHANGELOG (need to do it through a PR as `develop` is protected).

fixed typo CHANGELOG

---

.github/workflows/build_wheels.yml
scripts/fix_casadi_rpath_mac.py
scripts/install_KLU_Sundials.py
vcpkg-configuration.json

Fixes the mac and windows wheels which were not working correctly

I2047 linux wheel

---

.gitignore
benchmarks/time_setup_models_and_sims.py
benchmarks/time_solve_models.py

Added benchmarks for `SPM`, `SPMe`, and `DFN` with all the parameter sets (except Sulzer2019 and Xu2019).
Some concerns -
- I could not solve the `DFN` model with `Mohtat2020` parameter sets for the benchmarks (commented code). I tried varying `dt_max` and used different solvers but nothing worked. Here is a reproducible example for the same-
```python
import numpy as np
import pybamm
import matplotlib.pyplot as plt
def prepare_model_Mohtat2020(model):
geometry = model.default_geometry
param = pybamm.ParameterValues("Mohtat2020")
param.process_model(model)
param.process_geometry(geometry)
var_pts = {"x_n": 20, "x_s": 20, "x_p": 20, "r_n": 30, "r_p": 30, "y": 10, "z": 10}
mesh = pybamm.Mesh(geometry, model.default_submesh_types, var_pts)
disc = pybamm.Discretisation(mesh, …
```

Benchmarks for model X parameter set combinations

---

.github/workflows/run_benchmarks_over_history.yml

Should fix the `run_benchmarks_over_history.yml` workflow. Running the test [here](https://github.com/pybamm-team/PyBaMM/runs/6773712245?check_suite_focus=true).

Update github actions version

---

benchmarks/unit_benchmarks.py

Created unit benchmarks (create an expression, parameterise a model, discretise a model, and solve a model) using this [example](https://github.com/Vaibhav-Chopra-GT/PyBaMM/blob/develop/examples/notebooks/Creating%20Models/3-negative-particle-problem.ipynb).
I tried developing these benchmarks using classes and inheritance, but `asv` runs `time_*` functions of the parent class in the child classes too. This results in benchmarks running multiple times.

add unit benchmarks

---

pybamm/plotting/quick_plot.py

Currently, the `create_gif` function throws a warning saying -
```
DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning dissapear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
```
This PR replaces `imageio` with `imageio.v2` to avoid any sudden breaking changes in the future and suppresses this warning for everyone!

Use `imageio.v2` to suppress warning

---

.github/workflows/benchmark_on_push.yml
.github/workflows/create_release.yml
.github/workflows/periodic_benchmarks.yml
.github/workflows/publish_pypi.yml
.github/workflows/run_benchmarks_over_history.yml
.github/workflows/test_on_push.yml
.github/workflows/update_license.yml
.github/workflows/update_parameter_sets_doc.yml
.github/workflows/update_version.yml
.github/workflows/url_checker.yml

- The `checkout` and `setup-python` actions are not using their latest major releases. 
- The `setup-python@v4` action requires the user to specify the `python` version

Update outdated action versions

---

CHANGELOG.md
pybamm/expression_tree/functions.py
pybamm/expression_tree/symbol.py
pybamm/models/base_model.py
pybamm/models/submodels/particle/base_particle.py
tests/unit/test_expression_tree/test_symbol.py

#2115 Boolean operator not implemented

---

CHANGELOG.md
pybamm/models/base_model.py
pybamm/models/submodels/electrolyte_diffusion/constant_concentration.py
pybamm/models/submodels/porosity/constant_porosity.py
pybamm/solvers/solution.py
tests/unit/test_models/test_base_model.py
tests/unit/test_plotting/test_quick_plot.py
tests/unit/test_solvers/test_scipy_solver.py

Some changes to help debugging events

make variables_and_events attribute and remove some events

---

pybamm/models/submodels/electrolyte_conductivity/surface_potential_form/full_surface_form_conductivity.py

Rescaling RHS of overpotential differential equation by 1/a to correct for proper non-dimensionalization for non-constant specific-surface areas (i.e., non-constant active material volume fractions and/or particle radii). 
Changes include:
- Updating full_surface_form_conductivity RHS to rescale RHS of
negative-electrode overpotential DE by a factor of 1/a, which
remains present upon non-dimensionalization
- 1/a scaling only affects DFN models with 'surface form' =
'differential' and any of the following:
- non-constant particle radii across electrodes
- non-constant active material volume fractions across electrodes
- loss of active material enabled
- other forms of non-constant specific surface areas 'a'
See Discussion #2142 for further details
Please add a line in the relevant section …

bugfix(double-layer cap scaling): rescaling overpotential RHS by 1/a

---

CHANGELOG.md
pybamm/expression_tree/interpolant.py
tests/unit/test_expression_tree/test_interpolant.py

fix shape for 2d interpolant

---

pybamm/plotting/plot_voltage_components.py

Previous y-max limit used the initial voltage, which assumes every experiment is a discharge one.
Changed plot settings to find the overall V max.

Change y-axis limits for charge experiment

---

pybamm/experiments/experiment.py
pybamm/meshes/one_dimensional_submeshes.py

- Fixed the failing (https://github.com/pybamm-team/PyBaMM/runs/7597766548?check_suite_focus=true) style test.
- The errors are right now printed as -
```
ValueError: Operating conditions must contain keyword 'for' or 'until' or 'Run'.
For example:     <---- extra spaces and line endings which should be removed
Discharge at 1C for 0.5 hours,     <---- extra spaces and line endings which should not be removed
Discharge at C/20 for 0.5 hours,
Charge at 0.5 C for 45 minutes,
Discharge at 1 A for 90 seconds,
Charge at 200mA for 45 minutes (1 minute period),
Discharge at 1 W for 0.5 hours,
Charge at 200 mW for 45 minutes,
Rest for 10 minutes (5 minute period),
Hold at 1 V for 20 seconds,
Charge at 1 C until 4.1V,
Hold at 4.1 V until 50 mA,
Hold at 3V until C/50,
Run US06 (A),
Run US06 (A) for …
```

Fix the failing style test + improve the format of printed errors

---

CHANGELOG.md
pybamm/callbacks.py
pybamm/simulation.py
pybamm/solvers/casadi_solver.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Fix a bug in callbacks for the Simulation class that was displaying the wrong error for experiments.
I keep fixing this in different branches, so hopefully doing it in its own branch will get in merged quicker.

fix bug in callbacks

---

CHANGELOG.md
pybamm/input/parameters/lithium_ion/seis/OKane2022/parameters.csv
pybamm/input/parameters/lithium_ion/seis/example/parameters.csv
pybamm/input/parameters/lithium_ion/seis/ramadass2004/parameters.csv
pybamm/input/parameters/lithium_ion/seis/yang2017_sei/parameters.csv
pybamm/models/submodels/interface/sei/base_sei.py
pybamm/models/submodels/interface/sei/sei_growth.py
pybamm/parameters/lithium_ion_parameters.py

A new parameter "Ratio of lithium moles to SEI moles" (short name z_sei) has been added. This variable was previously hardcoded to 1 for all SEI growth options except "ec reaction limited". As pointed out in issue #2065, z_sei=1 is incorrect for the two most common SEI compoints - LEDC and Li2CO3, both of which require z=2.
The SEI parameter sets have been updated accordingly. The new parameter z_sei is set to 2 by default for all parameter sets except OKane2022, which used the old code for which it was set to 1.
Fixes #2065 
You can run all …

Added new parameter z_sei to allow the user to set SEI valancy

---

requirements.txt
setup.py

This came up in a discussion with @brosaplanella (about hatch and migration from `setup.py` to `pyproject.toml`)
As long as we use the right lower bound, we will never encounter this issue again -
- https://bitbucket.org/pybtex-devs/pybtex/issues/129/pybtex-0222-installs-a-package-called
- https://bitbucket.org/pybtex-devs/pybtex/pull-requests/37

Lower pin `pybtex` and remove redundant lines

---

docs/requirements.txt
requirements.txt
setup.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py

Revert numpy to >= 1.16 since scikits.odes has released fixed version

unpin numpy since scikits is fixed

---

pybamm/models/submodels/particle/fickian_diffusion.py

Save the `rhs` and `rbc` of the Fickian diffusion models as variables, so that they can be plotted

save rhs and bc as variables for Fickian diffusion

---

CHANGELOG.md
docs/requirements.txt
docs/source/util.rst
pybamm/__init__.py
pybamm/batch_study.py
pybamm/spatial_methods/finite_volume.py
pybamm/spatial_methods/scikit_finite_element.py
pybamm/spatial_methods/spatial_method.py
pybamm/util.py
tests/unit/test_util.py

Function saves information about the commit, and if that is not available it returns the version number

add function to save which last pybamm commit

---

docs/source/solvers/idaklu_solver.rst
docs/source/solvers/index.rst
pybamm/solvers/idaklu_solver.py

I am not sure why this was not included in the docs at the first place

Add `IDAKLUSolver`'s API to the docs

---

CHANGELOG.md
pybamm/solvers/c_solvers/idaklu.cpp
pybamm/solvers/c_solvers/idaklu_casadi.cpp
tests/unit/test_solvers/test_idaklu_solver.py

fix bug in size of yS numpy array when simulation stops early
Fixes #2331 

#2331 fix bug in size of yS numpy array when simulation stops early

---

pybamm/simulation.py
tests/unit/test_simulation.py

- add option in build to initialize soc
- remove added dependency
- add test
move initial soc setting to its own function, which can be called from build
Fixes #2372 

Add option for initial soc in build

---

CHANGELOG.md
docs/source/util.rst
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/models/base_model.py
pybamm/util.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_models/test_base_model.py
tests/unit/test_util.py

Remove some functions that aren't used anywhere

remove unused functions

---

CHANGELOG.md
pybamm/util.py
tests/unit/test_models/test_base_model_generate_julia_diffeq.py
tests/unit/test_util.py

Currently `pybamm.have_julia()` returns True even if PyCall.jl is not configured this results in test failures as the tests assume they can call:
```python
from julia.api import Julia
Julia()
```
Which fails if Julia has not been configured. This commit fixes that.
- [] No style issues: `$ flake8`

fix: pybamm.have_julia is True when PyCall.jl uninstalled

---

.github/ISSUE_TEMPLATE/new_parameter_set.yml
.readthedocs.yml

RTD currently builds the docs without pybamm installed, causing build errors as #2396 added `import pybamm` to `conf.py`
Fixes #
RTD not building after #2396 

fix: build docs with pybamm installed

---

pybamm/parameters/parameter_sets.py
tests/unit/test_parameters/test_parameter_sets_class.py

- fix: lazily load parameter set entry points
- refactor: Avoid calling dunder methods in parameter_sets
Lazily load parameter sets instead of doing it on creation, reduces `import pybamm` by ~0.5s
Fixes #2436

Reduce pybamm.parameter_sets init time

---

CHANGELOG.md
docs/source/parameters/parameter_sets.rst
pybamm/parameters/parameter_sets.py
setup.py
tests/unit/test_parameters/test_parameter_sets_class.py

Fixed a typo in docs on adding a new parameter set and added emphasis on installing/reinstalling the parameter set package.
Typo found via: https://github.com/pybamm-team/PyBaMM/discussions/2452

Rename to entrypoint to `pybamm_parameter_sets`

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

Avoids trying to process children if a function parameter is an object that doesn't depend on its children
Fixes #2704

#403 add special case for constant function parameter

---

CMakeBuild.py
pybamm/solvers/c_solvers/idaklu/casadi_solver.cpp
pybamm/solvers/c_solvers/idaklu/common.hpp
pybamm/solvers/c_solvers/idaklu/options.cpp
pybamm/solvers/idaklu_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Fixes 22.11 build
lapack dense solver caused issues with building wheels (sundials not compiled with lapack), so this solver has been removed for this release

Fix build 22.11

---

CHANGELOG.md
examples/scripts/compare_lithium_ion.py
pybamm/input/parameters/ecm/example_set.py
pybamm/input/parameters/lithium_ion/Ai2020.py
pybamm/input/parameters/lithium_ion/Chen2020_composite.py
pybamm/input/parameters/lithium_ion/Ecker2015.py
pybamm/input/parameters/lithium_ion/NCA_Kim2011.py
pybamm/input/parameters/lithium_ion/OKane2022.py
pybamm/models/full_battery_models/equivalent_circuit/ecm_model_options.py
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
pybamm/parameters/parameter_values.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_initial_soc.py
tests/unit/test_models/test_full_battery_models/test_equivalent_circuit/test_thevenin.py
tests/unit/test_solvers/test_casadi_solver.py

In the standard parameter sets, create the interpolants from functions explicitly (instead of relying on the `ParameterValues` class to do it). This allows finer control of hyperparameters (e.g. interpolator).
Using "cubic" interpolator for OCV gives much faster performance than linear interpolator (e.g. 1s -> 0.5s solve time for Ai2020 on my laptop)
Fixes #2410 

explicitly create interpolants from functions

---

CHANGELOG.md
pybamm/citations.py
setup.py
tests/unit/test_citations.py

This looks like this right now -
Now that I think of it, it might be better to not show a warning on importing pybamm (would be too noisy). Rather, we could do -
```py
def __init__(self):
self._papers_to_cite = set()
self._all_citations: dict[str, str] = dict()
if "google.colab" not in sys.modules:
self.read_citations()
self._reset()
```
and then -
```py
def print_citations(filename=None, output_format="text"):
"""See :meth:`Citations.print`"""
if "google.colab" in sys.modules:
warnings.warn(
"""pybtex does not work with Google Colab due to a known bug -
https://bitbucket.org/pybtex-devs/pybtex/issues/148/.
Please manually cite all the references.""".replace(
"\n                ", " "
),
)
else:
pybamm.citations.print(filename, output_format)
```
Fixes #2524 
Please add a line in the …

Fix colab and pybtex issue

---

.github/workflows/periodic_benchmarks.yml
.github/workflows/run_benchmarks_over_history.yml
.github/workflows/test_on_push.yml
docs/install/install-from-source.rst

#2537 might take some time, given that there are a lot of breaking changes _and_ not all of them are documented well. Additionally, they have enabled `isolated_builds` to be always true, which I think is the reason for the failing ubuntu tests - 
The `macOS` and `windows` tests work with `v4` now, but the `ubuntu` tests don't.
This PR aims to temporarily fix the CI by upper-pinning `tox` (till the time `tox.ini` is migrated to `v4`).

Temporarily pin tox < 4

---

CHANGELOG.md
pybamm/experiments/experiment.py
tests/unit/test_experiments/test_experiment.py

Tags can be added to the end of an experiment as `[tag1,tag2]`. I have added the method `search_tag` which returns the list of cycles with a certain tag, which should help saving only certain cycles.
Fixes #2538 

Add tags to `Experiment`

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/test_on_push.yml
.gitignore
.pre-commit-config.yaml
CONTRIBUTING.md
pybamm/__init__.py
pybamm/discretisations/discretisation.py
pybamm/input/parameters/lead_acid/Sulzer2019.py
pybamm/input/parameters/lithium_ion/Ai2020.py
pybamm/input/parameters/lithium_ion/testing_only/negative_electrodes/graphite_Ai2020/graphite_entropy_Enertech_Ai2020_function.py
pybamm/solvers/casadi_solver.py
pybamm/util.py
pyproject.toml
tox.ini

Tried `ruff` locally, and it really is super fast!
I also tried migrating some of the metadata to `pyproject.toml`, but I ended up with a lot of errors (given that `pyproject.toml` support is still very new and maybe in the beta phase in `setuptools`.)
Some false alarm examples that are being ignored using `pyproject.toml` -
```
pybamm/parameters/__init__.py:5:5: F401 `.process_parameter_data.process_3D_data_csv` imported but unused
pybamm/solvers/jax_bdf_solver.py:293:9: E741 Ambiguous variable name: `I`
tests/__init__.py:15:101: E501 Line too long (106 > 100 characters)  # not a false alarm, but the import names can get lengthy sometimes in the __init__ files
pybamm/__init__.py:61:1: F403 `from .expression_tree.symbol import *` used; unable to detect undefined names …
```

Flake8 to ruff

---

CHANGELOG.md
pybamm/solvers/processed_variable.py

Removing hard-coded value of 1 for `first_length_scale` of r-R plots, which made the x axis of these plots be scaled by 1e5.
Fixes #2225 

Remove conditional for scaling of r-R plots

---

pybamm/experiments/experiment.py

#2703 remove warning if temperature not provided

---

CHANGELOG.md
examples/notebooks/models/composite_particle.ipynb
pybamm/models/submodels/interface/open_circuit_potential/current_sigmoid_ocp.py

The existing version of current_sigmoid_ocp is only valid for the negative electrode and gives the wrong result for hysteresis in the positive electrode. Fortunately, adding an extra four lines of code fixes this.

Changed current_sigmoid_ocp to be valid for both electrodes

---

pybamm/models/submodels/particle/fickian_diffusion.py
pybamm/models/submodels/particle_mechanics/base_mechanics.py

Save diffusivity variables that were missed when using a particle size distribution and add an x-averaged surface displacement variable.

save diffusivity variables

---

docs/conf.py
docs/source/_static/pybamm.css
docs/source/_static/versions.json
scripts/update_version.py

This updates the version switcher styling on readthedocs and configures a `.json` file for the version switcher dropdown
Fixes #2766 

Fix version switcher on readthedocs

---

CHANGELOG.md
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py

Implements integral of VdQ to calculate theoretical maximum energy. Useful for defining battery efficiency. Submitted PR due to discussion with @tinosulzer 
- [ x] New feature (non-breaking change which adds functionality)

Method to calculate theoretical efficiency

---

CHANGELOG.md
pybamm/input/parameters/lead_acid/Sulzer2019.py
pybamm/input/parameters/lithium_ion/Ai2020.py
pybamm/input/parameters/lithium_ion/Chen2020.py
pybamm/input/parameters/lithium_ion/Chen2020_composite.py
pybamm/input/parameters/lithium_ion/Ecker2015.py
pybamm/input/parameters/lithium_ion/Marquis2019.py
pybamm/input/parameters/lithium_ion/Mohtat2020.py
pybamm/input/parameters/lithium_ion/NCA_Kim2011.py
pybamm/input/parameters/lithium_ion/OKane2022.py
pybamm/input/parameters/lithium_ion/ORegan2022.py
pybamm/input/parameters/lithium_ion/Prada2013.py
pybamm/input/parameters/lithium_ion/Ramadass2004.py
pybamm/input/parameters/lithium_ion/Xu2019.py
pybamm/input/parameters/lithium_ion/testing_only/negative_electrodes/graphite_Ai2020/parameters.csv
pybamm/input/parameters/lithium_ion/testing_only/positive_electrodes/lico2_Ai2020/parameters.csv
pybamm/parameters/bpx.py
pybamm/parameters/lead_acid_parameters.py
pybamm/parameters/lithium_ion_parameters.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_compare_outputs_two_phase.py

I'm pretty sure these parameters can be hard-coded based on battery chemistry (lithium-ion, lead-acid, etc). Let me know if you have a counter-example

remove stoich and ne params, hardcode instead

---

CHANGELOG.md
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
pybamm/solvers/solution.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py

Add theoretical energy to summary variables

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
tests/unit/test_discretisations/test_discretisation.py

If variable bounds contain an `InputParameter` set the bound to +/- inf.
Fixes #2793

`InputParameter` in variable bounds

---

CHANGELOG.md
pybamm/CITATIONS.txt
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py

https://arxiv.org/abs/2303.07088

add new esoh variables from dVdQ paper

---

CHANGELOG.md
pybamm/simulation.py

When a starting_solution was provided to Solution.solve(), the method attempted to pass a sub-field of the starting_solution to make_cycle_solution(), instead of the required list of Solver objects.
Fixes #2788 ([Bug]: Solution last_state can't be used as a starting solution)

Fix use of last-state as starting-solution in Simulation.solve()

---

CHANGELOG.md
pybamm/solvers/casadi_solver.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_dfn.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_casadi_algebraic_solver.py

Quick fixes so that the tests pass again.
There are still lots of improvements to be made to the casadi integrator, but these are the most urgent
Work towards. #2858 

Issue 2858 casadi

---

CHANGELOG.md
pybamm/solvers/idaklu_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Partially fixes #2789 and unblocks #2858 

#2789 add "all" to sensitivities for idaklu solver

---

pybamm/simulation.py
requirements.txt
setup.py
tests/unit/test_experiments/test_simulation_with_experiment.py

s/b self evident. tqdm is a very low overhead progress bar (80ns per iteration according to their docs). My motivation for this is running very long cycling experiments (take many hours) it's nice to know something is happening, and setting logging to info is messy and is giving me a lot more information than I really need. Note that tqdm is the same package that liionpack uses for its progress bar. 

add (optional) progress bar for cycling experiments

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

Fixes a small bug when inputting parameters as a dictionary

remove chemistry from parameter set dict

---

pybamm/models/submodels/interface/open_circuit_potential/single_ocp.py

fix bulk ocp for a half cell

---

CHANGELOG.md
docs/source/user_guide/installation/install-from-source.rst

The (Mac recommended) `brew` install procedure for sundials does not link the cmake args that are required by `tox -e dev`. Here, we simplify the developer installation procedure for Mac, bringing it in-line with that for linux, by using `tox -e pybamm-requires` to download, compile and install the SuiteSparse and SUNDIALS libraries.
Fixes #2897 
_(documentation change only)_
~~[ ] No style issues: `$ pre-commit run` (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CONTRIBUTING.md#installing-and-using-pre-commit) for …

Remove brew-sundials from the recommended developer installations

---

CHANGELOG.md
pybamm/solvers/solution.py
tests/unit/test_solvers/test_solution.py

I keep doing this manually and it might be useful here instead

save step and cycle number from a solution

---

CHANGELOG.md
pybamm/solvers/base_solver.py
pybamm/solvers/c_solvers/idaklu/casadi_solver.cpp
pybamm/solvers/c_solvers/idaklu/casadi_sundials_functions.cpp
pybamm/solvers/idaklu_solver.py
tests/integration/test_models/standard_model_tests.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_dfn.py
tests/unit/test_solvers/test_idaklu_solver.py

1. feed initial conditions for the sensitivity vectors to the idaklu solver (before was just initialised to 0)
2. call idagetsens after idacalcic to get the corrected initial conditions for sensitivity vectors
3. make the FD h a bit smaller to reduce numerical errors in sensitivity validation for models
Fixes #2858

I2858-init-cond-sundials

---

scripts/install_KLU_Sundials.py

Explicitly raise error in parent process while installing SUNDIALS and SuiteSparse

---

CHANGELOG.md
pybamm/parameters/bpx.py

Fixes a bug where parameter sets imported from BPX using `create_from_BPX` were incompatible with the "lumped" thermal model. 
- Added current collector domains when assigning thermal properties
- Corrected notation of units from BPX to match PyBaMM
- Assigned arbitrary values for current collector thickness and conductivity
Fixes # [2860](https://github.com/pybamm-team/PyBaMM/issues/2860)

Add current collector domains and correct units

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

This PR updates the version on the GitHub Actions steps so that coverage is generated with Python 3.11 via `tox -e coverage`. This was discussed on an earlier PR (#2867) and should work fine since `Jax` was updated recently (#2927)

Use Python 3.11 for generating coverage in CI

---

docs/conf.py
docs/requirements.txt
docs/source/user_guide/installation/GNU-linux.rst
docs/source/user_guide/installation/index.rst
docs/source/user_guide/installation/install-from-source.rst
docs/source/user_guide/installation/windows.rst
setup.py
tox.ini

Adds the [sphinx-inline-tabs](https://github.com/pradyunsg/sphinx-inline-tabs) Sphinx extension to save space on installation instructions and remove redundant steps in the documentation for developer and user workflows.

Add inline-tabs for Sphinx docs

---

docs/conf.py

Adds a link to download Jupyter notebooks in the PyBaMM documentation such that they can be run offline by users.

Add an option to download Jupyter notebooks from readthedocs

---

docs/Makefile
noxfile.py
run-tests.py
sphinx_extend_parent.py

Adds the `-j` command line flag with its value set to `auto` to distribute the build procedure over multiple processes. Helps speed up the build since processing the Jupyter notebooks takes time (#3043)

Enable multithreaded documentation builds

---

docs/conf.py
docs/requirements.txt
docs/source/_static/pybamm.css
docs/source/user_guide/index.md
setup.py

This PR adds and configures support for [sphinx-hoverxref](https://sphinx-hoverxref.readthedocs.io/en/latest/index.html), which enables hovering over classes, methods, and other links to directly display their results within the same page

Add floating window tooltips for cross-references in the docs

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

This PR caches `nox` test environments in order to speed up the CI. Environments are matched with a key that corresponds to relevant files that are subject to change, and the Python version (including the subversion) to avoid mismatch constraints. It also refactors the unit tests to run in a single step for Linux, macOS, and Windows; closes #3095 

Cache `nox` environments and refactor unit tests in CI

---

.github/workflows/run_periodic_tests.yml

A quick fix to quick the failing doctests step in the scheduled nightly tests, after #3043 

Fix scheduled tests

---

docs/source/user_guide/installation/install-from-source.rst

Make nox -s dev run like nox -s dev --verbose to so that all commands run is shown.

Document other useful `nox` commands

---

benchmarks/time_sims_experiments.py
benchmarks/time_solve_models.py

#2954 turn off benchmark: ORegan2022 DFN solver with the casadi model

---

docs/sphinxext/inheritance_diagram.py

A quick fix after #3074 and #3097 to declare the `inheritance_diagram.py` extension safe for parallel reads and writes, in order to suppress warnings that arise when running the doctests in the CI which are treated as errors.

Fix failing doctests

---

.github/workflows/run_periodic_tests.yml

This updates the `run_periodic_tests.yml` workflow to include the self-hosted m-series runner.
Fixes #2884 

Add self-hosted actions to periodic tests

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

added else statement to inform user of an invalid parameter set
Added else statement to inform user of an invalid parameter set in parameter_values.py
In response to #3063 - Raise error for unknown parameter sets
Fixes # (3063)

Raise error for unknown parameter_values

---

CHANGELOG.md
pybamm/models/full_battery_models/equivalent_circuit/thevenin.py

Add standard variables to Thevenin() class

---

.github/workflows/test_on_push.yml

A follow-up to #3079 and fixes the failing Windows tests with Python 3.11 on #3108. This PR ensures that the Python version (including sub-versions and patch releases) from the outputs of the `setup-python` action is used to build the cache keys and invalidates previously built caches when there is a version change (i.e., from Python 3.11.3 to Python 3.11.4), making the caching more robust. See https://github.com/actions/setup-python/issues/330#issuecomment-1126638275 for more details.
You can run unit and doctests together at once, using `$ …

Ensure `setup-python` outputs are always included in `nox` cache keys

---

noxfile.py

Adds descriptive docstrings for `nox` sessions, which can be listed with the `nox --list` or `nox -l` commands, and some general improvements. Closes #3048

Add docstrings for `nox` sessions

---

CHANGELOG.md
pybamm/simulation.py

Fix simulation with c_rate drive cycles

---

.pre-commit-config.yaml
CONTRIBUTING.md
docs/source/api/parameters/parameter_sets.rst
docs/source/user_guide/fundamentals/index.md
docs/source/user_guide/getting_started.md
pybamm/solvers/idaklu_solver.py

This PR aims to add [`blacken-docs`](https://github.com/adamchainz/blacken-docs) as pre-commit hook to auto format python code in docs.

Add `blacken-docs` as pre-commit hook for code-blocks in docs

---

.readthedocs.yaml

According to the [documentation](https://docs.readthedocs.io/en/stable/guides/enable-offline-formats.html). This PR will build PyBaMM's documentation in more formats and make it available for download for subsequent versions.

Enable downloadable PDF, EPUB, and zipped HTML formats on Read the Docs

---

examples/scripts/cycling_ageing.py
noxfile.py
pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py

The theoretical energy calculation was using `param.p.prim.Q_init` in all cases, when it should have been using the value of "Q_p" from the solution of the esoh solver, which can change from the initial value as the cell degrades

fix energy calculation

---

pybamm/models/submodels/interface/kinetics/base_kinetics.py

Fix half-cell bug introduced in #3207 
Fixes #3128 

#3128 fix half cell models

---

.readthedocs.yaml

Removes PDF builds from the Read the Docs configuration, closes #3240

Temporarily disable PDF documentation builds

---

.github/workflows/need_reply_remove.yml
.github/workflows/needs_reply.yml

Should be `repository_owner` and not `repository-owner` - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

Fix need_reply workflows

---

.readthedocs.yaml
docs/_static/pybamm.css
docs/sphinxext/inheritance_diagram.py

The SVG images generated by the `sphinxext/inheritance_diagram.py` extension create multiple PDFs upon LaTeX output with Sphinx's LaTeXBuilder. This PR makes them render on HTML output only, which is in-line with documentation for other projects that display inheritance diagrams for API components.
Closes #3240 

Re-enable PDF builds for Read the Docs

---

CONTRIBUTING.md
docs/source/user_guide/installation/install-from-source.rst
noxfile.py
run-tests.py

See relevant discussions on Slack and on #3264. This PR adds a new `--scripts` argument to the `run-tests.py` parser and a new `nox` session for running the examples scripts tests with the `nox -s scripts` command.
> [!Note]  
> This PR should be merged in conjunction with #3264

Split Jupyter notebooks tests and example scripts tests into separate `nox` sessions

---

CHANGELOG.md
pybamm/expression_tree/binary_operators.py
tests/unit/test_expression_tree/test_binary_operators.py

Fixes shape error with `Heaviside`
Fixes #3298 

Issue 3298 heaviside shape

---

.github/workflows/benchmark_on_push.yml

Pin `asv==0.5.1` to fix failing benchmarks

---

noxfile.py

The "with" keyword in the ```nox -s docs``` session causes an AttributeError in older versions of Nox. This change makes the nox session backwards compatible.
Fixes #3319
Closest category is "bug fix", however, this is just a minor compatibility issue.

Remove with clause in docs session for backwards compatibility

---

docs/source/examples/notebooks/getting_started/tutorial-6-managing-simulation-outputs.ipynb
docs/source/user_guide/installation/install-from-source.rst
docs/source/user_guide/installation/windows.rst

Minor updates to the documentation pages.
Changes:
- Fixes a broken link between the windows installation page and the windows WSL installation page. The broken link was caused by having the incorrect name for the windows WSL page.
- Removes a note about using chocolatey from the MacOS install from source tab. I left the note in the Linux install from source tab for the use-case where a windows installation is done with Cygwin. I can remove the note from both MacOS and Linux if desired.
- Tutorial 6 now uses a temporary folder to write the pickle files. I feel it is cleaner to write output to a specific folder rather than the current working directory. Since this is my opinion and it does add a small amount of complexity, I can remove this change if it is unwanted.
Documentation and …

Documentation suggestions for the installation and tutorials

---

.github/workflows/lychee_url_checker.yml
.lycheeignore
docs/conf.py

Closes #3328; ensures that users of the example notebooks can download the correct notebook from GitHub according to the latest version, stable versions starting from 23.5, and on PR builds. The Google Colab badge now points to the correct renditions of the notebooks, rather than the `develop` branch.

Issue 3328 correctly point notebook download URLs according to versions

---

benchmarks/different_model_options.py

Current benchmarks do not include current collector models, so x-lumped and lumped end up solving the same model (plus x-lumped was failing). I have removed the x-lumped from the list of options.
Fixes #3357

Remove x-lumped in benchmarks

---

.github/workflows/benchmark_on_push.yml
.github/workflows/periodic_benchmarks.yml

The scheduled benchmarks suite was failing to run because the version was not pinned to 0.5.1. This PR resolves both benchmarks workflows and allows the benchmarks to run

Fix periodic benchmarks and remove version cap on `asv`

---

pybamm/expression_tree/operations/evaluate_python.py
pybamm/solvers/jax_bdf_solver.py
pybamm/solvers/jax_solver.py

This adds:
-  `FP32` support for Jax on Metal with GPU compilation (M-series GPU's don't support `FP64`)
-   Logic for parallelised GPU implementation on Metal
This fixes #3274; however, there are errors in the Jax GPU tests when ran on apple-silicon. I'll open a seperate issue for those though.

Jax on Metal w/ GPU support

---

.github/workflows/benchmark_on_push.yml
.github/workflows/periodic_benchmarks.yml

Removes the `packaging` dependency from the explicit list of packages on two Github actions activities, since it's already included within `asv[virtualenv]`.
Fixes #3383
- [ N/A ] Code is commented, particularly in hard-to-understand areas
- [  N/A ] Tests added that prove fix is effective or that feature works

Remove redundant `packaging` dependency install

---

.github/workflows/publish_pypi.yml
CHANGELOG.md
build_manylinux_wheels/install_sundials.sh

Drops support for 32-bit wheels on Linux platforms due to NumPy's recent BLAS requirement and uses an updated method, i.e., `python -m build` for building the source distribution

Drop support for i686 manylinux

---

tests/unit/test_batch_study.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_parameters/test_lead_acid_parameters.py
tests/unit/test_parameters/test_lithium_ion_parameters.py
tests/unit/test_plotting/test_quick_plot.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_solution.py

The unit tests leave a large number of files behind in the git repo. This change will make the tests use temporary directories when creating files.
I used the tempfile module in python. There are a few other ways to do this, and I believe the preferred method is to use pytest. However, since pytest does not appear to be used, I went with tempfile as the easy solution.
Minor fix in the tests. 

tests: Use temporary directories in unit tests

---

.all-contributorsrc

There's a typo in the .all-contributorsrc which causes the bot to fail. This hopefully fixes it.

Fix typo .all-contributorsrc

---

.github/release_reminder.md
.github/wheel_failure.md
.github/workflows/publish_pypi.yml

Build wheels on the 1st and 15th of every month

---

CHANGELOG.md
pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

#3428 exchange-current density error

---

CMakeLists.txt
pybamm/solvers/c_solvers/idaklu/CasadiSolverOpenMP.cpp
pybamm/solvers/c_solvers/idaklu/casadi_functions.hpp
pybamm/solvers/c_solvers/idaklu/casadi_sundials_functions.cpp
vcpkg-configuration.json

Windows wheels were failing to build. This was due to differences in c++ compiler specifications across operating systems. Additional compiler flags have been added to harmonise build specifications across operating systems going forwards.
Fixes #3431 

Fix failing windows wheel builds

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

Uses `pipx` to run `nox` in the workflows (since it is installed by default on GitHub Actions runners) so that `nox` can be found as a command-line application without Python executable invocation
See https://github.com/pybamm-team/PyBaMM/pull/3406#issuecomment-1763497185, #3452,  #3408

Fix Windows unit and integration tests failures

---

CHANGELOG.md
pybamm/models/full_battery_models/base_battery_model.py
pybamm/models/full_battery_models/lithium_ion/__init__.py
pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
pybamm/parameters/parameter_values.py
pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_simulation.py

Adds methods to use initial soc with half-cell models
Also fixes a spelling mistake I saw, lolz.
@tinosulzer it sounds like is redoing much of this anyway, so this could be considered a hot fix for now given that it may be overwritten soon.
I'd love it if this got into 23.9 as a bug fix so that I don't have to pin to some weird branch waiting for the next version, but understand if that's not possible. If I need to branch off 23.9 to make that happen, I would be happy to do so.
Fixes #3224 
You can run integration tests, unit …

make initial soc work with half cell models

---

docs/source/examples/notebooks/solution-data-and-processed-variables.ipynb

The notebook **solution-data-and-processed-variables.ipynb** left some files behind [outputs.csv, outputs.mat, outputs.pickle]. These files were missed in #3377 
Minor fix, does not break anything.

Remove notebook outputs from main directory

---

.github/workflows/docker.yml

This PR uses QEMU to build images for aarch64/arm64 platforms besides amd64, and fixes the error in https://github.com/pybamm-team/PyBaMM/pull/3316#discussion_r1349778849 about an improper tag for one of the images by using a build-matrix setup to create images. Related to #3312.

Multi-architecture Docker images and parallel builds

---

.github/release_workflow.md
.github/workflows/publish_pypi.yml

Make testpypi the default option (precaution) + update tag instructions

---

pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
pybamm/simulation.py

There was a slight bug in #3456 that caused `initial_soc` to error when using a drive cycle for half-cell models. This PR fixes that bug. 

fix esoh bug

---

CHANGELOG.md
pybamm/experiment/experiment.py
pybamm/simulation.py
pybamm/step/_steps_util.py
tests/unit/test_experiments/test_experiment.py

Fixes a bug in which identical steps but with different end times could not be distinguished, and thus crashed the simulation by using a wrong end time.
It is a hacky fix, a more robust one should be implemented as part of the refactor in #3176.

Fix bug with identical steps with different end times

---

pybamm/models/submodels/interface/base_interface.py
pybamm/models/submodels/particle/base_particle.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_newman_tobias.py

Fixes a bug when using exchange-current or diffusivity hysteresis with composite electrodes.

Fix hysteresis option bug

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml
setup.py

Fix `pipx` + `nox` + `pip` dependency resolution bug in macOS workflows

---

noxfile.py

The `nox -s dev` session should also install upgraded versions of `pip`, `setuptools`, and `wheel` before attempting to install PyBaMM. This fixes a few installation errors with `casadi` headers not being found by CMake when using `nox` to install PyBaMM. Related to #3529.

Fix installation bug with `nox`

---

noxfile.py

A small PR to fix the `nox -s dev` session. It was not installing PyBaMM in editable mode due to a missing `-e` command-line flag.

Fix `nox -s dev` bug

---

docs/source/user_guide/installation/index.rst
pyproject.toml

Sync lower bounds with conda package

---

pybamm/models/submodels/interface/open_circuit_potential/base_ocp.py
pybamm/models/submodels/thermal/base_thermal.py

Summing the irreversible and reversible heating terms over the phases in the BaseThermal class as detailed in https://github.com/pybamm-team/PyBaMM/issues/3543#issuecomment-1836406296. To do so, the entropic change dUdT variables are stored for each phase in the BaseOpenCircuitPotential class.
Fixes #3543

Fix Issue 3543 - Thermal model not working for a composite electrode particle model with two (or more) phases

---

CHANGELOG.md
pybamm/models/submodels/particle/base_particle.py
pybamm/models/submodels/particle_mechanics/base_mechanics.py
pybamm/parameters/lithium_ion_parameters.py

For many chemistries, notably high-nickel NMCs and graphite, the volume change associated with intercalation is a strong function of stoichiometry. Here, I have taken the r-averaged value for Ω and used it to calculate total stress. This accounts for the change without violating the initial model assumptions.
This is the same as #2943 but it was easier to start over than just update that one
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also …

Make mechanical properties a function of stoichiometry and sometimes temperature

---

.github/workflows/publish_pypi.yml
.github/workflows/release_reminder.yml
.github/workflows/run_benchmarks_over_history.yml
.github/workflows/run_periodic_tests.yml
.github/workflows/validation_benchmarks.yml
.github/workflows/work_precision_sets.yml

Added conditions to PyBaMM-specific workflows so that they always be skipped in forks. Used the same condition found on `update_license.yml`.
Changed the branch of the PR.
Fixes #3592

Added conditions to workflows to be skipped

---

noxfile.py

Closes #3639. This is a minimal and temporary fix for now, I will chase this down soon and try to fix the issue for the `pybtex` repository upstream when I get time.

i3639 Fix Python 3.12 tests

---

.github/dependabot.yml
pyproject.toml

Looks much better now:
```
saransh@saranshs-air PyBaMM % python3 -m pipx run "sp-repo-review[cli]" .
General:
• Detected build backend: setuptools.build_meta                                                                                                    
• Detected license(s): BSD License                                                                                                                 
├── PY001 Has a pyproject.toml ✅
├── PY002 Has a README.(md|rst) file ✅
├── PY003 Has a LICENSE* file ✅
├── PY004 Has docs folder ✅
├── PY005 Has tests folder ✅
├── PY006 Has pre-commit config ✅
└── PY007 Supports an easy task runner (nox or tox) ✅
PyProject:
├── PP002 Has a proper build-system table ✅
├── PP003 Does not list wheel as a build-dep ✅
├── PP301 Has pytest in pyproject ✅
├── …
```

Fix multiple configurations and adhere to scientific python guidelines

---

pyproject.toml

Ignore internal nbmake warnings - fix notebook tests

---

.github/workflows/publish_pypi.yml

A small fix because the `actions/upload-artifact@v4` GitHub Action now requires unique artifact names.
Fixes #3676

Use distinct names for macOS and Linux wheel artifacts

---

pybamm/solvers/jax_bdf_solver.py

Replaced `jax` with `jax.extend` in import.
Fixes #3644

Fixed Deprecation warnings of `jax_bdf_solver`

---

pybamm/experiment/experiment.py

1. Improved error handling by raising TypeError when a str is passed to Experiment instead of list of strings
2. Added type hinting for better readability.
Fixes #3623

Improved error handling and added type hinting in Experiment

---

scripts/install_KLU_Sundials.py

Introduce a TOML-style comment block at the top of the `install_KLU_Sundials.py` script. This block contains essential metadata, including the required Python version and a list of dependencies. This addition aligns the script with the PEP 723 guidelines, enhancing readability and portability for script runners and developers.
The metadata includes:
- The Python version requirement (<=3.9)
- Dependencies required for the script (wget, cmake)
- Additional information like the repository and documentation links
This enhancement facilitates easier script sharing and collaboration, providing a standardized way to specify and access script dependencies and supported Python versions. It also lays the groundwork for potential future tooling that could automate environment setup and dependency …

Add PEP 723 support for SuiteSparse and SUNDIALS installation script

---

docs/source/user_guide/installation/gnu-linux-mac.rst
docs/source/user_guide/installation/windows.rst

I missed this while working on the changes in #3550 and #3531 – sorry!

Fix docs about Jax solver compatibility with Python versions

---

CHANGELOG.md
docs/source/user_guide/installation/gnu-linux-mac.rst
pybamm/install_odes.py

This was a small detail that was missed; the `pip install` invocation inside a script should be done with a `sys.executable` (i.e., `python`/`python3`/`python3.X`) because some users' systems do not have `pip` added to the `PATH` environment variable explicitly – such as non-`virtualenv`-based virtual environments or those using system package managers such as `apt-get` or `brew` to manage Python dependencies This change makes it more robust and possible to work outside a virtual environment (say, if someone does not wish to use one for their own purposes, even though we strongly recommend that).
I added a `--verbose` command-line flag with the lowest level of verbosity possible just so that some output can be seen in the terminal, even on successful installations.
`wget` and `cmake` were …

Make `pybamm_install_odes` a bit more robust

---

CHANGELOG.md
pybamm/simulation.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Fixed a bug where if the first step(s) in a cycle are skipped then the cycle solution started from the model's initial conditions instead of from the last state of the previous cycle.
Fixes #3690 

#3690 fix issue with skipped steps

---

pybamm/models/submodels/interface/sei/sei_growth.py

The SEI thickness decreased at some intervals when the 'electron-migration limited' model was used. It has been corrected by considering only negative contributions to eta_sei in the j_sei, using the Heaviside function.
Fixes #3613 
- [x ] No style issues: `$ pre-commit run` (or `$ nox -s pre-commit`) (see [CONTRIBUTING.md](https://github.com/pybamm-team/PyBaMM/blob/develo …

Fixed a bug where the SEI thickness decreased at some intervals when using the 'electron-migration limited' model.

---

.github/CODEOWNERS

Minor update to save us from notifications

Don't notify CODEOWNERS on editing the CHANGELOG

---

.github/workflows/run_periodic_tests.yml

Fix doctests failures in scheduled tests

---

pybamm/install_odes.py

See discussion on #3785. This command exits with a warning if a cached wheel is not present, it does not raise an error and therefore should be safe to add within a subprocess.
We already purge any cached wheels in CI when running the scheduled tests for this entry point – this PR ensures it is done for users running it locally.

Purge `scikits.odes` cached wheels when using `pybamm_install_odes`

---

.github/workflows/run_periodic_tests.yml

The M-series self-hosted runner was using a cached, un-repaired `scikits.odes` wheel which had been linked to the Homebrew rendition of SUNDIALS (which isn't a problem though) instead of the one we regularly use in CI. Apple has a history of [sanitising runtime search paths](https://hynek.me/articles/macos-dyld-env/), which caused the SUNDIALS dynamic libraries to not be found at runtime by the Python extension modules for `scikits.odes`. 
This PR ensures that the build-time dependencies for PyBaMM are always re-compiled on each run, the `SUNDIALS_INST` variable is set, and that `scikits.odes` is built from source every time.
The M-series build passed here: https://github.com/pybamm-team/PyBaMM/actions/runs/7713296977/job/21022885593
You can run integration tests, unit tests, and doctests …

Resolve broken `scikits.odes` installation on self-hosted M-series runner

---

.github/workflows/publish_pypi.yml
CHANGELOG.md

GitHub Actions M1 runners are free for open-source repositories now – I have configured the PyPI workflow to add a job for these runners.
> [!IMPORTANT]
> The wheels can be tested on M-series hardware via the following link: https://github.com/pybamm-team/PyBaMM/actions/runs/7721068374/
Closes #3772, related to #3462

Build M-series (arm64) macOS wheels on GitHub Actions hosted runners

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

This PR configures the workflows to include tests for the new GitHub Actions M1 runners.

Add macOS M1 runner testing configuration for PRs and scheduled tests

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml
noxfile.py

i3808 missing Fortran compiler config for macOS M1 runner

---

docs/conf.py

This issue aims to fix broken `Open in Colab` badges on docs.pybamm.org
Fixes #3817 

Fix broken `Open in Colab` badges linked to example notebooks

---

CHANGELOG.md
pybamm/models/submodels/current_collector/potential_pair.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py

Fix a bug where you couldn't use voltage or power control with pouch cell models
Fixes #3828 

#3828 fix pouch cell voltage control

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

Trying to fix the codecov error in the tests.
Fixes #3843

Fix codecov

---

CHANGELOG.md
docs/source/user_guide/installation/index.rst
pybamm/expression_tree/array.py
pybamm/expression_tree/binary_operators.py
pybamm/expression_tree/concatenations.py
pybamm/expression_tree/functions.py
pybamm/expression_tree/independent_variable.py
pybamm/expression_tree/operations/latexify.py
pybamm/expression_tree/parameter.py
pybamm/expression_tree/scalar.py
pybamm/expression_tree/symbol.py
pybamm/expression_tree/unary_operators.py
pybamm/expression_tree/variable.py
pybamm/models/base_model.py
pybamm/type_definitions.py
pyproject.toml
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_concatenations.py
tests/unit/test_expression_tree/test_functions.py
tests/unit/test_expression_tree/test_independent_variable.py
tests/unit/test_expression_tree/test_parameter.py
tests/unit/test_expression_tree/test_printing/test_sympy_overrides.py
tests/unit/test_expression_tree/test_symbol.py
tests/unit/test_expression_tree/test_unary_operators.py
tests/unit/test_expression_tree/test_variable.py

Fix broken import of PyBaMM raised by type hinting.
Fixes #3836 

Make `typing-extensions` and `sympy` required dependencies to fix PyBaMM import

---

examples/scripts/experimental_protocols/cccv.py
pybamm/solvers/processed_variable.py

This speeds up simulations by 5x because xarray.DataArray initialization is slow
Before (560ms, 2% time spent solving the model):
After (130ms, 10% time spent solving the model):
Test code (this example is a "worst-case scenario" for overheads where solving the simulation is very quick, it highlights the other parts of the code that are slow):
```python
import pybamm
import matplotlib.pyplot as plt
pybamm.set_logging_level("NOTICE")
experiment = pybamm.Experiment(
[
(
"Discharge at 1C for 1 minute",
"Rest for 1 minute",
),
]
* 10
)
model = pybamm.lithium_ion.SPM()
parameter_values = pybamm.ParameterValues("Chen2020")
sim = pybamm.Simulation(
model,
experiment=experiment,
parameter_values=parameter_values,
solver=pybamm.CasadiSolver("fast with events"),
)
sim.solve()
```
There are still …

delay xarray.DataArray initialization

---

pybamm/util.py
tests/unit/test_util.py

The logic for this was the wrong way round. We need to check if "particle diffusivity" fails and change it to "electrode diffusivity"

fix deprecation warning and check for electrode/particle diffusivity

---

docs/source/user_guide/installation/install-from-source.rst

#3883 updates to install from source

---

.github/workflows/benchmark_on_push.yml
.github/workflows/periodic_benchmarks.yml
.github/workflows/run_periodic_tests.yml

Stop the benchmarks from running on PRs. The reasons for this are the frequent failures and the long runtime. Benchmarks are still run daily and for main/develop
Related: #3662

Disable benchmarks on PRs

---

pyproject.toml

Minor update to remove the remaining references to the extra [latexify] in the project
Fixes #3887 
Fixes an install warning.

Remove reference to latexify extras

---

CHANGELOG.md
pybamm/plotting/plot_voltage_components.py

Before, it showed nothing because of propagation of nans

fix plot_voltage_components to work when time doesn't start at 0

---

.github/workflows/publish_pypi.yml
.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

This PR addresses a small future-proofing change – in June 2024, the `macos-latest` label on GitHub Actions runners will point to the ARM macOS images (`macos-14`) rather than the Intel ones. This won't affect building the wheels, as on both images `cibuildwheel` correctly sets `MACOSX_DEPLOYMENT_TARGET` to 10.9 on amd64 and 11.0 on arm64 for use by `setuptools.build_meta` when tagging the wheel.
There is an issue with Homebrew when using the `macos-13` images, but the `macos-12` ones work for now.
You can run integration tests, unit tests, …

`macos-latest` ➡️ `macos-12`

---

pybamm/solvers/casadi_algebraic_solver.py
pybamm/solvers/casadi_solver.py

Fixes the lychee CI check. I replaced the tiny-urls with the integrator and root finder links in the current documentation.
Only documentation.

Replace casadi links

---

CHANGELOG.md
pybamm/expression_tree/interpolant.py
tests/unit/test_expression_tree/test_interpolant.py

Allow evaluation of an `Interpolant` object with a number

Float interpolant

---

pybamm/models/full_battery_models/lithium_ion/basic_dfn_half_cell.py

Fixes a bug in the `BasicDFNHalfCell` model where the counter electrode thickness and conductivity are incorrectly taken from the working electrode.

Fix Li foil thickness and conductivity in basic DFN half-cell model

---

docs/source/user_guide/installation/install-from-docker.rst
scripts/Dockerfile

Changed the pybamm userID to 1000 and groupID to 0 (root).
Related to #3312 

Added pybamm user id to 1000 and set its group to root

---

pybamm/util.py
pyproject.toml

Gets the Jax tests up and running again so we can working fixing the problem
Related #3959 

Fix Jax tests

---

CHANGELOG.md
tests/unit/test_solvers/test_jax_bdf_solver.py
tests/unit/test_solvers/test_jax_solver.py

Jax tests checked runtime, which is inconsistent in the CI suite. This should keep the same coverage, but stop checking the runtime. Note: the changelog is also updated since that was missed in #3961 
Fixes #3925
Only test code.

Remove time check from Jax tests to improve stability

---

pybamm/solvers/base_solver.py

This is the practice of contribute to the PyBaMM (creating PR and updating docstring). I edited docstring in  function solve and step in pybamm/solvers/base_solver.py.
These have been mentioned in the #3392 (API Docs - Small fixes suitable for first time contributors)
I have made changes following the suggestion in the #3392 API Docs - Small fixes suitable for first time contributors: pybamm.BaseSolver.solve and pybamm.BaseSolver.step

Docs base solver

---

pybamm/plotting/quick_plot.py

Practise contributing to issue for Hackathon:
In the file pybamm.plotting.quick_plot.py, added "optional" keyword to "step" argument in dynamic_plot function. Removed round brackets around optional keywords in the arguments "number_of_images", "duration", "output_filename" in create_gif function.
Related #3392 - Improve documentation
Documentation Update

docstring fixes to pybamm.plotting.quick_plot

---

CHANGELOG.md
examples/scripts/multiprocess_inputs.py
pybamm/solvers/base_solver.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_compare_outputs_two_phase.py

This PR updated the multiprocess pool to be constructed with context `fork` for `darwin` and `linux` platforms. It also adds an example and updates integration tests to use the list of dictionaries input functionality which should ensure this get tested in script formation.
Fixes #3974 

Standardise BaseSolver.solve() multiprocessing context to `fork`

---

asv.conf.json

i3991 use Python-3.12 compatible `pybind11` to fix benchmarks

---

pybamm/experiment/experiment.py

The Arg in pybam.experiment has been updated. 
This is one of the issue listed in #3392 

update Arg pybamm.Experiment.period

---

docs/source/api/util.rst
pybamm/__init__.py
pybamm/util.py
tests/unit/test_util.py

Minor removal of code and some cleanup of IDE warnings
Fixes #3982
Removes old code

Remove RMSE function

---

pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_base_solver.py

Convert's the global `mp.set_start_method` context to an individual pool context.
Fixes #3997 

Update multiprocessing context to be Pool specific

---

CONTRIBUTING.md
pybamm/citations.py
tests/unit/test_util.py

The goal of this PR is to solve two problems.
- Remove optional dependencies present in the base version of PyBaMM, so that `pybamm` can be imported without optional dependencies installed
- Fix error detection: when an optional dependency is present in non-optional modules, we need to detect these errors and report them.
Fixes #3940

Fix optional dependencies error detection and remove `pybtex` hidden dependency

---

.github/workflows/docker.yml
CHANGELOG.md
docs/source/user_guide/installation/install-from-docker.rst
scripts/Dockerfile

The `Dockerfile` is reduced to include all the solvers by default, the documentation for `install from source (docker)` and `docker.yml` workflow file have been updated to push only one single docker image tagged `pybamm:latest` to dockerhub with all the solvers contained in them by default, i.e `IDAKLU` and `JAX`.
Fixes #3666 

Reduced the number of docker images by one `pybamm:latest`

---

.github/workflows/periodic_benchmarks.yml
.github/workflows/publish_pypi.yml
.github/workflows/run_benchmarks_over_history.yml

Addresses one out of two parts of issue #3489 – resolves artifacts names and how they are downloaded to fix the rule `GH104 Use unique names for upload-artifact`. They are now all downloaded in one folder for the benchmarks and the wheel builder workflows.

Use unique artifact names

---

CHANGELOG.md
pybamm/discretisations/discretisation.py
tests/unit/test_discretisations/test_discretisation.py

Don't remove independent variables if they appear in events.
Fixes #4018 

#4018 check indepedent vars in events

---

pybamm/__init__.py
pybamm/models/submodels/thermal/base_thermal.py
pybamm/models/submodels/thermal/isothermal.py
pybamm/models/submodels/thermal/lumped.py
pybamm/plotting/plot_thermal_components.py
tests/unit/test_plotting/test_plot_thermal_components.py

Similar to `plot_voltage_components`, breaks down the temperature / heating into components.
This currently is oriented towards the lumped thermal model.

add plot_thermal_components

---

CHANGELOG.md
pybamm/batch_study.py
pybamm/discretisations/discretisation.py
pybamm/simulation.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_idaklu_jax.py
tests/unit/test_solvers/test_idaklu_solver.py

Been meaning to do this for a while due to hard-to-fix bugs such as #2528 . #4019 was good motivation.
To set the setting to True (which can speed up the simulation, especially during the rest period), do
```python
pybamm.Simulation(..., discretisation_kwargs={"remove_independent_variables_from_rhs": True)
```
Fixes #2528 

change remove independent variables setting to False by default

---

docs/conf.py

This is a fix to some issues that were highlighted in recent bug reports (#4034, #4035) where I feel that the versioning warning admonition displayed by Read the Docs is not prominent enough or does not display properly on other devices. Since the example notebooks are very frequently used based on insights from the analytics that can be derived from our analytics hosting service, this is an improvement over #3333 and will display a `sphinx`/`docutils` admonition before the notebook headings and subsequent sections.
This is how it looks like:
Locally, this can be verified with the command with the relevant in-line environment variable:
```bash
READTHEDOCS_VERSION="latest" nox -s docs
```
Please add a line in the relevant section of …

Display a warning for individual notebook pages on latest versions of the documentation

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

See new releases at https://github.com/actions/python-versions/releases – Python 3.8 and Python 3.9 builds should be available for macOS arm64 (`macos-14` tag) now.
xref: https://github.com/actions/setup-python/issues/808

Enable testing on Python 3.8, 3.9 for macOS arm64

---

pybamm/plotting/plot_thermal_components.py
tests/unit/test_plotting/test_plot_thermal_components.py

Temperature components were confusing.
New plot:

switch thermal component plot to cumulative heating

---

pyproject.toml
vcpkg-configuration.json

Fixes #4044
Wheels are building: https://github.com/pybamm-team/casadi-vcpkg-registry/pull/1
Workflow run logs: https://github.com/agriyakhetarpal/PyBaMM/actions/runs/8950718520/job/24586326296
https://github.com/pybamm-team/casadi-vcpkg-registry has been updated and the baseline has been updated accordingly.

CasADi 3.6.5

---

docs/source/examples/notebooks/models/MSMR.ipynb

Fixes a typo in the MSMR notebook where it was written that `f=RT/F` instead of `f=F/RT`. This is correct in the code.

fix typo in f = F/RT

---

CHANGELOG.md
MANIFEST.in

Current source distributions do not have the CMakelists.txt shipped in them, so the users cannot build it. 
Fixed by adding CMakeLists.txt in Manifest.in

included `CMakeLists.txt`

---

.github/workflows/publish_pypi.yml

Adds what was missing to be done in #3783 – this should ensure that we get some extra non-UCRT DLLs in a `wheel.libs` folder inside the Windows wheel. This is not required but would be good to have because we use MSVC (Visual Studio 17 2022) as our compiler and not Clang/MinGW (which use UCRT) and therefore we should provide DLLs like `MSVCP140.dll` that have a tendency of not being present on many systems, in order to boost compatibility (this is mostly because of the absence of the MSVC Redistributable runtime components on quite a few systems). For most systems running Windows 10 and above, these files are generally present. …

Use `delvewheel` to repair wheels on Windows, add MSVCRT DLLs

---

.github/workflows/run_periodic_tests.yml
noxfile.py

The documentation built on CI fails with an error. It was found that we still need to install setuptools before docs/doctests sessions to avoid erroring out. 
Also, the scheduled jobs are parallelized for faster CI
Fixes #4082 

Issue 4082 Documentation CI Fix

---

.github/workflows/publish_pypi.yml
.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml
.gitignore
.lycheeignore
docs/source/user_guide/installation/install-from-source.rst
scripts/install_KLU_Sundials.py

This reverts commit becb1a4a4b137452d7e490b314fcd5801e3a9137 because this is causing `-9` exit code errors on macOS devices. @kratman and I are investigating a complete fix for this. In the time being, it would be better to revert the breaking change which is the source of the failures. Related to #4091.

Temporarily revert changes from #4092

---

noxfile.py

CI tests are failing in python3.12 on [this](https://github.com/pybamm-team/PyBaMM/actions/runs/9290109029/job/25567375568?pr=4098) workflow action under `unit/coverage` tests. Looking at the `noxfile` there was a temporary fix included for python3.12 in this [commit](https://github.com/pybamm-team/PyBaMM/commit/5f35628f21d44a4152419b7d8215a40f201709bc#diff-f7a16a65f061822bcc73b8296f4dc837353d379d8d9cc5307982cb6941442835) which I included in other `nox.sessions` as well. Though it is a temporary fix, I tested it on my [branch](https://github.com/santacodes/PyBaMM/actions/runs/9292250506/job/25572739026) and it seems to be working.
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the …

Fixed Python3.12 failing CI tests

---

pybamm/util.py

Set minimum JAX version to `0.4.14` instead of `0.4`
Fixes #4127 

#4127 Set minimum `JAX==0.4.27`

---

.github/workflows/test_on_push.yml

Coverage was not working properly, this should fix it

Fix coverage workflow

---

.github/workflows/publish_pypi.yml
asv.conf.json
noxfile.py

Bump to pybind11 v2.12.0 to introduce upcoming NumPy v2 compatibility – it shouldn't be needed for our case because we don't build against the NumPy-C API but just to be sure, I tested the solvers against NumPy v2.0.0rc2 because the IDAKLU-Jax solver uses quite a few NumPy array in its implementation.
`pybind11` is scheduled to be a build-time dependency through #3564, earlier through #3560.

`pybind11` v2.12.0

---

docs/source/examples/notebooks/change-settings.ipynb
docs/source/examples/notebooks/models/lead-acid.ipynb
pybamm/experiment/step/steps.py

The function
```
def string(string, **kwargs):
```
used the same name for the argument as the function.
I slightly improved this by changing the argument to "text" instead.
```
def string(text, **kwargs):
```

Rename string(string) to avoid a scope issue

---

.github/ISSUE_TEMPLATE/config.yml

The redirect link while creating a new issue and selecting `I am unsure where to go` is broken and leads [here](https://pybamm.org/contact) which returns `Error 404: Page Not Found`.
Fixes #4181 

Fixed broken contact link

---

pyproject.toml

Temporary pin for the numpy version
Related #4183

Pin numpy to less than 2.0.0

---

pybamm/expression_tree/unary_operators.py
tests/unit/test_expression_tree/test_unary_operators.py
tests/unit/test_spatial_methods/test_finite_volume/test_finite_volume.py

This fixes the edge case for #2837 / removes the need to use x-average

move secondary broadcast outside of gradient

---

CHANGELOG.md
pybamm/experiment/step/base_step.py
pybamm/experiment/step/steps.py
tests/unit/test_simulation.py

Adds functionality to pass in arbitrary functions of time as the argument for a `pybamm.step`
Fixes https://github.com/pybamm-team/PyBaMM/issues/4187

Add functions of time in experiment step 

---

pybamm/models/full_battery_models/base_battery_model.py
tests/unit/test_models/test_full_battery_models/test_base_battery_model.py

Adds an OptionError if the option `SEI on cracks` is True but `particle mechanics` does not contain cracks. This issue only occurs if both options are set explicitly in the model's additional options - the user's `particle mechanics` option overrides the defaults which automatically set the mechanics to "swelling and cracking" if `SEI on cracks` is true.
Fixes #4119

Bug fix for cracking options

---

tests/unit/test_batch_study.py

When debugging some tests, it went into some classes that are defined at the top level of `test_ batch_study.py`, which made it harder (and a bit slower) to debug. Moving the setup into the test to avoid this - likely a temporary solution anyway before we migrate to pytest

Fix batch study test

---

tests/unit/test_expression_tree/test_functions.py
tests/unit/test_expression_tree/test_unary_operators.py

SymPy updated and seems to no longer recognize PyBaMM symbols as strings.
It gets to this block (N.B. warning text was edited for readability):
```
if not isinstance(a, str):
try:
a = str(a)
except Exception as exc:
raise SympifyError(a, exc)
sympy_deprecation_warning("The string fallback in sympify() is deprecated.")
```
Then fails due to an exception. Even if it did convert to a string, it would have caused a deprecation warning.
Failing tests looked like this:
```
a = pybamm.Symbol("a", domain="test")
self.assertEqual(pybamm.Arcsinh(a).to_equation(), sympy.asinh(a))
```
There seemed to be two options:
1.  Add a `pybamm.Symbol._sympy_()` method. This would be basically identical to `pybamm.Symbol.to_equation()`, and would not be a good test.
2. Explicitly put the expected string into …

Fixes for sympy update

---

docs/source/examples/notebooks/getting_started/tutorial-5-run-experiments.ipynb
pybamm/callbacks.py
pybamm/experiment/step/base_step.py
pybamm/experiment/step/steps.py
pybamm/simulation.py
tests/unit/test_callbacks.py
tests/unit/test_experiments/test_experiment_steps.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Fixes #4224
- ~~longer default duration (1000 hours)~~ 
- default duration is 2 / C-rate hours for C-rate steps
- warning if step finishes due to hitting the default duration
Currently working on adding a warning if maximum duration is reached

Issue 4224 duration bug

---

CHANGELOG.md
pybamm/solvers/c_solvers/idaklu/Expressions/Base/ExpressionSet.hpp
pybamm/solvers/c_solvers/idaklu/Expressions/Casadi/CasadiFunctions.hpp
pybamm/solvers/c_solvers/idaklu/Expressions/IREE/IREEFunctions.hpp
pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.hpp
pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl
pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP_solvers.hpp
pybamm/solvers/c_solvers/idaklu/Options.cpp
pybamm/solvers/c_solvers/idaklu/Options.hpp
pybamm/solvers/c_solvers/idaklu/idaklu_solver.hpp
pybamm/solvers/c_solvers/idaklu/sundials_functions.inl
pybamm/solvers/idaklu_solver.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/unit/test_solvers/test_idaklu_solver.py

Adds more user-configurable options to the IDA solver following the list in the IDA guide.
Some code cleanup to enforce early returns.

Add more `idaklu` solver options (number 2)

---

docs/source/user_guide/installation/gnu-linux-mac.rst

Minor fixes that are on develop, found during the release.
I also found some changelog errors, but I did those directly on the release branch and they will be addressed in a sync PR post-release.

Fixes for mistakes found during the release process

---

pybamm/models/submodels/electrolyte_conductivity/surface_potential_form/composite_surface_form_conductivity.py

Fixes a bug where a factor of electrode surface area to volume ratio is missing in the rhs of the `CompositeDifferential` conductivity model.
In particular, this fixes the missing semi-circle when simulating EIS with SPMe. This got missed in https://github.com/pybamm-team/PyBaMM/pull/4139

fix bug in composite surface form model

---

CHANGELOG.md
pybamm/solvers/c_solvers/idaklu.cpp
pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl
pybamm/solvers/c_solvers/idaklu/Solution.hpp
pybamm/solvers/c_solvers/idaklu/python.cpp
pybamm/solvers/idaklu_solver.py
pybamm/solvers/solution.py
tests/unit/test_solvers/test_idaklu_solver.py

This is an alternative to #4150 (old pull request will be closed)
Simulations using the IDAKLU solver with output variables specified which terminated with an event rather than the final time step would crash trying to find the termination event.
Termination events are found in the Solution class by using the state vector of the final time-step to evaluate each potential termination event and find the minimum (the event which caused the termination). When output variables are specified in the IDAKLU solver only those variables are output in `y_out`, not the entire state vector, so the events could not be evaluated outside the solver.
This PR edits the IDAKLU solver to add an additional return value containing the state vector for the final timestep only ('y_term') when output variables …

3937 events with idaklu output variables - solver edit

---

pybamm/simulation.py

A small PR to remove usage of the simulation class properties, within the class.

Update simulation class private members

---

tests/unit/test_util.py

I caught this while running `nox -s unit` and also in CI [here](https://github.com/pybamm-team/PyBaMM/actions/runs/10285560857/job/28464203323).
Instead of checking the compatibility of the JAX solver the test was checking if JAX solver was present and logging `JAX is not installed`, when it should log something like `JAX is compatible` when the check passes inside the `skipif` marker of pytest.
```bash
SKIPPED [1] tests/unit/test_solvers/test_idaklu_jax.py:91: Both IDAKLU and JAX are available
SKIPPED [1] tests/unit/test_util.py:91: The JAX solver is not installed
```
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, …

Fixed JAX solver compatibility test

---

CONTRIBUTING.md

The ruff repository was transferred to [astral-sh](https://github.com/astral-sh/ruff).

Fixed `ruff` link in `CONTRIBUTING.md`

---

src/pybamm/parameters/bpx.py
tests/unit/test_parameters/test_bpx.py

Removed check_already_exists from parameter sets created from BPX parameter sets.
Fixes #4339

Remove "check_already_exists" from BPX

---

src/pybamm/parameters/parameter_values.py

Default value for  `target_soc` argument in `create_from_bpx` static method is set to `1`.  As the function does not have type hints, `target_soc` data type is inferred as `int` while it is `float`. This causes our linters to fail.
This PR just changes the default value to `1.0` to mitigate linting issues.

changed default value to float

---

CHANGELOG.md
src/pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl

Fixed a memory issue with output variables reported in #4375
Fixes #4375

Fix IDAKLU segfault with output variables

---

CHANGELOG.md
benchmarks/different_model_options.py
benchmarks/time_solve_models.py
benchmarks/work_precision_sets/time_vs_abstols.py
benchmarks/work_precision_sets/time_vs_mesh_size.py
benchmarks/work_precision_sets/time_vs_no_of_states.py
benchmarks/work_precision_sets/time_vs_reltols.py
tests/integration/test_solvers/test_idaklu.py
tests/unit/test_solvers/test_idaklu_solver.py

This PR updates the IDAKLU tests and benchmarks to use the updated `t_eval` and `t_interp` arguments. This will speed up the github actions a bit and better reflect the performance of the `IDAKLUSolver` in benchmarks.

Update IDAKLU time stepping in tests and benchmarks

---

CHANGELOG.md
docs/source/api/util.rst
examples/scripts/compare_dae_solver.py
src/pybamm/__init__.py
src/pybamm/expression_tree/operations/evaluate_python.py
src/pybamm/solvers/idaklu_jax.py
src/pybamm/solvers/idaklu_solver.py
src/pybamm/solvers/jax_bdf_solver.py
src/pybamm/solvers/jax_solver.py
src/pybamm/util.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_mpm.py
tests/integration/test_solvers/test_idaklu.py
tests/unit/test_citations.py
tests/unit/test_experiments/test_simulation_with_experiment.py
tests/unit/test_expression_tree/test_operations/test_evaluate_python.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_idaklu_jax.py
tests/unit/test_solvers/test_idaklu_solver.py
tests/unit/test_solvers/test_jax_bdf_solver.py
tests/unit/test_solvers/test_jax_solver.py
tests/unit/test_solvers/test_scipy_solver.py
tests/unit/test_util.py

Minor change to the function names so the logic reads:
```
if pybamm has something
```
instead of 
```
if pybamm have something
```

Rename have_x to has_x to improve how logic reads

---

.github/workflows/publish_pypi.yml
pyproject.toml
vcpkg-configuration.json

I was going to split these into two PRs, but I decided that it would be fine to do it in the same one:
- This removes a workaround previously used to repair the wheels for Intel macOS devices. We will now have better compatibility with macOS version 10.13 and later. The M-series wheels still have something broken, so I will need to reach out to CasADi upstream again.
- For Windows, I bumped CasADi to version 3.6.6 in our registry at https://github.com/pybamm-team/casadi-vcpkg-registry and updated the baseline for our `vcpkg` configuration.
You …

Fix CasADi libs workaround for macOS wheels, update to CasADi 3.6.6 for Windows wheels

---

CHANGELOG.md
src/pybamm/settings.py
src/pybamm/simulation.py
src/pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_idaklu_solver.py
tests/unit/test_solvers/test_scipy_solver.py

I removed a few unnecessary checks for minimum `dt` values to proceed with the simulation.
I also removed the `start_step_offset = 1e-9` heuristic setting. For large `t_start` values, you can get floating point arithmetic errors like `t == t + 1e-9` that cause duplicate `t` values in the solution. I replaced `start_step_offset` with `np.nextafter(t, np.inf)`, which prevents these errors by giving the next largest floating point number. cc @valentinsulzer 
You can run integration tests, unit tests, and doctests together at once, using `$ python …

Remove unnecessary `dt` checks

---

CHANGELOG.md
src/pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.hpp
src/pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl
src/pybamm/solvers/idaklu_solver.py

In `IDA`, we can compute an analytical solution for consistent initialization/reinitialization of ODEs, which avoids an expensive call to `IDACalcIC`. This change gives a modest speed improvement to all the ODE models solved by the `IDAKLUSolver` and will give a bigger speedup to those with a dense `t_eval` vector. For example,
```python
import pybamm
import numpy as np
model = pybamm.lithium_ion.SPM()
solver = pybamm.IDAKLUSolver()
sim = pybamm.Simulation(model, solver=solver)
t_eval = np.linspace(0, 3600, 10000)
sol = sim.solve(t_eval)
print(sol.integration_time)
```
- New `integration_time`: **367 ms**
- Old `integration_time`: **514 ms**
- Speedup: **1.4x**
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to …

Faster (re)initialization of ODEs in `IDA`

---

CHANGELOG.md
src/pybamm/solvers/base_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Fixes #4439 
Similarly to #3937 this is caused by code searching for variables in the full state vector which aren't present due to the reduced set produced when output_variables are specified.

Fix IDAKLU output_variables to work with extrapolation events

---

src/pybamm/parameters/parameter_values.py
tests/unit/test_parameters/test_parameter_values.py

Defined `__iter__ `and `__contains__ `method to `pybamm.ParameterValues` which would allow `in` to work in logical test and for-loop contexts. 
Fixes #4438 

Added __iter__ and __contains__ method to pybamm.ParameterValues

---

src/pybamm/solvers/c_solvers/idaklu/observe.hpp

This was an issue caught here: https://github.com/pybamm-team/pybammsolvers
In the standalone repo, wheels are built as part of the tests and were failing on windows. This fixed the issue.

Fix a type issue for windows

---

docs/conf.py

I could not reproduce this in docker or locally (MacOS), but I saw this fix on another project.
Fixes #4495 

Fix doc failures in notebooks

---

.gitignore
src/pybamm/CITATIONS.bib
src/pybamm/solvers/jax_bdf_solver.py
src/pybamm/solvers/jax_solver.py

It looks like the https://github.com/google/jax moved to https://github.com/jax-ml/jax
This should fix the link checking.
Fix for link checkers

Fix Jax links

---

tests/unit/test_parameters/test_process_parameter_data.py

Refactored the parameter processing test cases to use `pytest` fixtures and `pytest.mark.parametrize` to reduce code duplication and improve test maintainability.
Related to #4502 

refactor: use pytest fixtures to reduce repetition in tests

---

CHANGELOG.md
src/pybamm/expression_tree/unary_operators.py
tests/unit/test_expression_tree/test_unary_operators.py

`_from_json` in `pybamm.Sign` was previously labelled as NotImplemented; #4394 identified this as a mistake as the `pybamm.Sign` class should be able to be de/serialised. This PR adds that functionality in.

Add _from_json functionality for pybamm.sign

---

.github/workflows/publish_pypi.yml
.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml
noxfile.py
pyproject.toml
src/pybamm/util.py

The macos-12 runner is being deprecated in December. This switches to the macos-13 runner

Removing the macos-12 runner

---

CHANGELOG.md
CONTRIBUTING.md
noxfile.py
src/pybamm/__init__.py

Quick fixes for the issues with CasADI and IREE.
Related #4524
Related #4521 
The CasADI fix should work for MacOS and Linux builds, but does not fix Windows issues.

Fix CasADI path and disable IREE for MacOS

---

src/pybamm/__init__.py
src/pybamm/discretisations/discretisation.py
src/pybamm/expression_tree/coupled_variable.py
src/pybamm/models/base_model.py
tests/unit/test_expression_tree/test_coupled_variable.py

Adds CoupledVariable from #3908. Does not really do integration work which will be required to use this for submodels.

CoupledVariable

---

src/pybamm/models/submodels/thermal/base_thermal.py

Implements reaction heating in half cell models for the negative electrode
Fixes #4324

add reaction heating

---

CONTRIBUTING.md
src/pybamm/discretisations/discretisation.py
src/pybamm/expression_tree/averages.py
src/pybamm/expression_tree/binary_operators.py
src/pybamm/expression_tree/operations/convert_to_casadi.py
src/pybamm/expression_tree/unary_operators.py
src/pybamm/expression_tree/vector.py
src/pybamm/meshes/one_dimensional_submeshes.py
src/pybamm/meshes/scikit_fem_submeshes.py
src/pybamm/models/base_model.py
src/pybamm/simulation.py
src/pybamm/solvers/casadi_algebraic_solver.py

I noticed some of the longer f-strings printed out with large indents. This PR is to clean that up a bit. There are still some triple quoted strings that could be cleaned up, but these are the easy ones to catch.

Cleanup formatting in error messages

---

src/pybamm/parameters/parameter_values.py

Quick fix to make pop() return a value
Fixes #4569 

Make ParameterValues.pop return a value

---

src/pybamm/expression_tree/operations/convert_to_casadi.py

Instead of using the casadi plugin system, use direct bspline function for 1D and 2D cubic interpolation.
I didn't implement 3D cubic interpolation because (a) scipy has no functions for bspline interpolation in 3D, and (b) we only test 3D linear interpolation so didn't think it was neccessary.
Fixes #4570

bug: use direct casadi bspline function for 1D & 2D cubic interp

---

src/pybamm/__init__.py
src/pybamm/parameters/parameter_values.py
src/pybamm/telemetry.py

A couple minor bug fixes before the release
Fixes #4580
Fixes #4578 

Misc. bug fixes

---

pyproject.toml
vcpkg-configuration.json

I updated https://github.com/pybamm-team/casadi-vcpkg-registry/ to build CasADi 3.6.7, and this PR updates the baseline to account for that change – so that we build our extension module against CasADi 3.6.7.

Update baseline for CasADi 3.6.7 bump

---

src/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py

When setting initial stoichiometries using a voltage, allow the initial voltage to be outside the voltage limits by `tol`. This is useful for example when setting the initial voltage to match some data where, say, the voltage is 4.2000001V and the upper voltage limit is 4.2V. Right now, this throws an error but clearly, that is an acceptable initial voltage to within a sensible user-specified tolerance. 
You can run integration tests, unit tests, and doctests together at once, using `$ python run-tests.py --quick` (or `$ nox -s …

allow tol in initial voltage for setting stoichiometries

---

CHANGELOG.md
noxfile.py
pyproject.toml

Adds some missing dependencies to the `pyproject.toml` file.

Fix dependenices

---

src/pybamm/expression_tree/unary_operators.py

This PR updates the documentation on the integral operator to describe how the coordinate system used affects the integral calculation (#4595).
The differential element used in the integral calculation changes depending on the coordinate system used, see Issue #4595 for a full description. 
As described in the issue, this is my first contribution to an open-source project. I tried running the tests, and they failed due to various problems with the Chayambuka2022 data set. I'm not really too sure what to do about that - as you can see it has nothing to do with my PR. 
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to document the change (include PR #) - note reverse order of PR #s. If necessary, also add to the …

Update documentation on Integral operator (#4595)

---

CHANGELOG.md
src/pybamm/plotting/quick_plot.py
tests/unit/test_plotting/test_quick_plot.py

This reverts commit b50d4a95c2639a4e10644332145d33d14e7b7594.
Fixes #4620

Revert "Modifies `QuickPlot.plot` ..."

---

CHANGELOG.md
src/pybamm/simulation.py
tests/unit/test_simulation.py

The `set_parameters` method in `Simulation` was deprecated, but it was still used internally, which caused warnings.

Remove internal use of deprecated `set_parameters` method

---

tests/unit/test_simulation.py

Addressing @kratman's comments following automerge of https://github.com/pybamm-team/PyBaMM/pull/4638

 Remove internal use of deprecated `set_parameters` method #2

---

src/pybamm/experiment/step/base_step.py
tests/unit/test_experiments/test_base_step.py

Small patch to handle exponents in units. There is probably more that can be done to improve the value/unit parsing, but this fixes the bug for now.
Fixes #4608

Add function for splitting units and add a test

---

CHANGELOG.md
docs/source/examples/notebooks/models/pouch-cell-model.ipynb
examples/scripts/compare_comsol/compare_comsol_DFN.py
src/pybamm/expression_tree/symbol.py
src/pybamm/models/base_model.py
tests/unit/test_solvers/test_processed_variable.py
tests/unit/test_solvers/test_processed_variable_computed.py

bug: make sure symbol always has required mesh attribute

---

.github/workflows/publish_pypi.yml
pyproject.toml
scripts/Dockerfile
setup.py

From https://github.com/conda-forge/pybamm-feedstock/pull/70. This allows us to simplify a few things, though it is only temporary until the time we migrate from the current system.
cc: @Saransh-cpp

Drop dependence on `wheel` at build time

---

.github/workflows/validation_benchmarks.yml

Migrates `.github/workflows/validation_benchmarks.yml` from `mvasigh/dispatch-action` to `peter-evans/repository-dispatch`. There are some minor differences in syntax between these two GHAs, which should all be handled by this PR
Fixes #4643 

changed dispatch-action for repository-dispatch (#4643)

---

.all-contributorsrc
.github/workflows/test_on_push.yml
README.md
all_contributors.md

An attempt to make the all-contrib bot skip required checks.

Make bot ignore auto-updated files

---

CHANGELOG.md
docs/source/user_guide/installation/gnu-linux-mac.rst
docs/source/user_guide/installation/index.rst
docs/source/user_guide/installation/install-from-docker.rst
docs/source/user_guide/installation/windows.rst

Update conda installation docs to reflect the new changes in the distribution (`pybamm-base` and `pybamm`).
Fixes #4653 
Fixes #4630

docs: update conda installation + minor fixes

---

src/pybamm/util.py
tests/unit/test_util.py

When the `parameters` dictionary is called with a key of `Primary: Some parameter [some unit]`, pybamm directs the user to use the dimensional version of that parameter. This is inconsequential but I find it annoying.
this PR simply corrects that logic. 

Fix incorrect error message

---

.all-contributorsrc

Makes all-contributors PRs run CI. This will allow us to have required checks and we can start to explicitly require tests to pass.
Fixes #4671 

Disable skipCI for all-contribs

---

CHANGELOG.md
src/pybamm/expression_tree/symbol.py
tests/unit/test_expression_tree/test_symbol.py

Add `post_order` method to symbol to return an iterable that steps through the tree in post-order fashion

add post_order

---

pyproject.toml

There are some breaking changes for BPX coming, so I am pinning this version until they are sorted out. It still may be a problem in the releases since the pin was a minimum before this change.

Temporary pin for BPX

---

docs/source/user_guide/installation/index.rst

Adding the missing dependencies to docs.
Fixes #4631

Adding list of missing dependencies to docs

---

src/pybamm/models/full_battery_models/base_battery_model.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_mpm.py

enables plating for particle size distribution models.
pending #4687 

Plating particle size distribution

---

docs/source/user_guide/installation/index.rst

This PR adds a warning admonition in the documentation to notify users about potentially outdated dependencies listed in the `requirements` section. The change helps to ensure that users are aware that the dependencies listed may not be up-to-date and should be verified.
Fixes #4705

Added a warning admonition to the list of dependencies in the installation guide

---

.github/workflows/discussion_autoresponder.yml
README.md
docs/index.rst

This PR introduces a commit that adds an autoresponder to GitHub discussions, which redirects users to the [Discourse forum](https://pybamm.discourse.group/). The changes include the addition of the discussion_responder.yml GitHub Action to manage automatic responses to new discussions, updates to the documentation to guide users toward the Discourse forum for further discussion, and the inclusion of a link to the Discourse forum in the README.md file.
Fixes: #4647 
https://github.com/user-attachments/assets/05b433a5-e320-4e86-b5fe-e72f26217686
https://github.com/user-attachments/assets/4549d268-37e2-4f1c-bf26-fd646c2946ae

Added GitHub Discussion Autoresponder and Updated Links to Discourse in Docs and README

---

CHANGELOG.md
src/pybamm/solvers/c_solvers/idaklu/IDAKLUSolverOpenMP.inl
src/pybamm/solvers/c_solvers/idaklu/Options.cpp
src/pybamm/solvers/c_solvers/idaklu/Options.hpp
src/pybamm/solvers/idaklu_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Add `dt_min` option for `IDAKLUSolver`

---

src/pybamm/solvers/processed_variable.py

Small cleanup with the new `pybammsolvers` package

Clean up `ProcessedVariable` `idaklu` import

---

docs/source/api/util.rst
examples/scripts/minimal_example_of_lookup_tables.py
src/pybamm/__init__.py
src/pybamm/models/base_model.py
src/pybamm/parameters/parameter_sets.py
src/pybamm/util.py
tests/unit/test_parameters/test_parameter_sets_class.py
tests/unit/test_util.py

Checking for outdated deprecation warnings before the 25.1 release. I did some other minor cleanup seen along the way as well.

Deprecation warning and function cleanup before 25.1

---

src/pybamm/solvers/solution.py
tests/integration/test_solvers/test_idaklu.py

Fixes misc bugs relating to the use of the `output_variables` option with the IDAKLU solver and Experiments.
Partly addresses #4743 

Bugfix: IDAKLU output variables with Experiments

---

src/pybamm/models/submodels/interface/sei/sei_growth.py
src/pybamm/simulation.py

#4394 introduced a bug in ec-reaction limited sei, this reverts the problematic change
@kratman lets do a patch release
@kawaMANMI can you take a look at this and make sure it doesn't break your code. also please try and be careful with stuff like this
Fixes #4773 

fix ec reaction bug

---

.clang-format

Missed this file. It has been moved to pybammsolvers now
Fixes #4779 

Remove missed file

---

CONTRIBUTING.md
noxfile.py
src/pybamm/input/parameters/lithium_ion/Ai2020.py
src/pybamm/input/parameters/lithium_ion/Marquis2019.py
src/pybamm/input/parameters/lithium_ion/Mohtat2020.py
src/pybamm/input/parameters/lithium_ion/Ramadass2004.py

Linkchecker broke on this website. So instead of using the link, I changed the footnote to reference the program author and program name

Replace CChem link with attribution to John Newman

---

src/pybamm/solvers/summary_variable.py
tests/unit/test_solvers/test_summary_variables.py

Adds cycle number as a key for summary variables (#4765 )
I didn't do the "all summary variables" part as I wasn't sure what the best name for that function was

add cycle number as a key

---

CHANGELOG.md
src/pybamm/models/full_battery_models/base_battery_model.py
src/pybamm/models/submodels/active_material/loss_active_material.py
src/pybamm/models/submodels/particle_mechanics/base_mechanics.py
src/pybamm/models/submodels/particle_mechanics/crack_propagation.py
src/pybamm/models/submodels/particle_mechanics/swelling_only.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_mpm.py

Adds support for particle size distributions combined with particle mechanics.

---

docs/source/api/meshes/one_dimensional_submeshes.rst

This PR just adds the SymbolicUniform1DSubMesh to the docs reference, which I forgot to do in #4665 

add symbolic mesh to docs reference

---

tests/unit/test_experiments/test_simulation_with_experiment.py
tests/unit/test_expression_tree/test_binary_operators.py
tests/unit/test_expression_tree/test_interpolant.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py
tests/unit/test_expression_tree/test_operations/test_evaluate_python.py
tests/unit/test_expression_tree/test_operations/test_jac.py
tests/unit/test_expression_tree/test_operations/test_jac_2D.py
tests/unit/test_expression_tree/test_state_vector.py
tests/unit/test_parameters/test_current_functions.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_plotting/test_plot_thermal_components.py
tests/unit/test_plotting/test_quick_plot.py
tests/unit/test_serialisation/test_serialisation.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_algebraic_solver.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_casadi_algebraic_solver.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_idaklu_solver.py
tests/unit/test_solvers/test_processed_variable.py
tests/unit/test_solvers/test_processed_variable_computed.py
tests/unit/test_solvers/test_scipy_solver.py
tests/unit/test_solvers/test_solution.py
tests/unit/test_spatial_methods/test_finite_volume/test_extrapolation.py
tests/unit/test_spatial_methods/test_finite_volume/test_grad_div_shapes.py
tests/unit/test_spatial_methods/test_finite_volume/test_integration.py
tests/unit/test_spatial_methods/test_scikit_finite_element.py
tests/unit/test_spatial_methods/test_spectral_volume.py

This PR refactors the testing methods in the codebase(unit tests directory) by replacing the`np.testing.assert_array_almost_equal` method with `np.testing.assert_allclose` for better precision and flexibility in comparison.
Related to #4488 

chore: switch to `np.testing.assert_allclose` for better precision in unit tests

---

CHANGELOG.md
src/pybamm/solvers/summary_variable.py
tests/unit/test_solvers/test_summary_variables.py

Adds a function to return a dictionary of all the summary variables + cycle number from the SummaryVariables class
Fixes #4765

Add 'get_summary_variables' function to SummaryVariables

---

CHANGELOG.md
src/pybamm/models/base_model.py
src/pybamm/models/full_battery_models/lithium_ion/base_lithium_ion_model.py
src/pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_base_lithium_ion_model.py
tests/unit/test_simulation.py

Creates a 'cal_esoh' property in the model class, set to False for the BaseModel, and True for the lithium ion BaseModel.
Allows the logic for whether eSOH variables should be calculated to be stored in the model, while allowing `Simulation.solve()` to override the model setting (i.e. set calc_esoh to False) as is the current behaviour.
Fixes #4619

Creates a 'calc_esoh' property in the BaseModel

---

CHANGELOG.md
docs/source/api/experiment/experiment_steps.rst
src/pybamm/experiment/step/__init__.py
src/pybamm/experiment/step/step_termination.py
tests/unit/test_experiments/test_experiment_step_termination.py
tests/unit/test_experiments/test_experiment_steps.py

I noticed today that to use a step for c-rate you call `pybamm.step.CRate` but to create a termination you use `pybamm.step.CrateTermination`. This is inconsistent,  so this pr fixes it.

rename CrateTermination to CRateTermination because the step is CRate

---

CHANGELOG.md
src/pybamm/plotting/quick_plot.py

When the time axis changes scale (e.g., from seconds to hours or days), minor floating-point arithmetic issues at the initial and final times can cause interpolation outside the timespan. As a result, the spatial variables could return `NaN` at the initial and final time points

Fix plotting interpolation bug with spatial variables

---

docs/conf.py

I needed an old version of the docs, and I noticed this:
No release after from 24.1 onwards has documentation.
I traced the problem here:
```
Traceback (most recent call last):
File "/home/docs/checkouts/readthedocs.org/user_builds/pybamm/envs/v25.1.1/lib/python3.12/site-packages/sphinx/config.py", line 529, in eval_config_file
exec(code, namespace)  # NoQA: S102
^^^^^^^^^^^^^^^^^^^^^
File "/home/docs/checkouts/readthedocs.org/user_builds/pybamm/checkouts/v25.1.1/docs/conf.py", line 338, in <module>
github_download_url = f"https://github.com/pybamm-team/PyBaMM/{append_to_url}"
^^^^^^^^^^^^^
NameError: name 'append_to_url' is not defined
```
IDE inspections also highlight this problem:
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/dev …

Fix docs for releases

---

CHANGELOG.md
src/pybamm/callbacks.py
src/pybamm/experiment/step/base_step.py
src/pybamm/simulation.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Adds an option to skip experiment steps. This is useful in CCCV if you start with too high of an initial SOC to run the CC step.

add option to skip experiment steps

---

docs/source/examples/notebooks/models/half-cell.ipynb
src/pybamm/simulation.py

This is an issue that I highlighted during our presence at the PyBaMM conference around a week ago: in #3494 (which closed #3415), I introduced a bug wherein a NumPy random seed was set when using the `CasadiSolver` to solve a simulation. It is discouraged to add a random seed in library/module code – it breaks reproducibility by overriding randomness that may have been set by user-level code in researchers' scripts and simulations (it is acceptable for test code, though).
As the PR was supposed to fix stochastic behaviour for the hall-cell model, I have moved the random seed to the notebook instead which used to fail at that time in the repository's development. Usually, this should be present for all notebooks, but one should be enough for now to keep the diff minimal.
Another potential …

Fix a bug where the usage of the CasADi solver breaks reproducibility

---

CHANGELOG.md
src/pybamm/models/submodels/active_material/loss_active_material.py

Moved particle concentration inside the x-average when calculating the LLI due to LAM variables. This will improve accuracy when using DFN.

Moved concentration inside average when calculating LLI due to LAM

---

CHANGELOG.md
src/pybamm/models/base_model.py
src/pybamm/solvers/idaklu_solver.py
tests/unit/test_discretisations/test_discretisation.py
tests/unit/test_solvers/test_casadi_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

For more info, see: https://github.com/pybamm-team/PyBaMM/pull/4878#discussion_r1972113603
This is a minor bug that practically only affects FEM simulations using the `IDAKLUSolver`
I will make a followup PR in `pybammsolvers` to address a related issue there: https://github.com/pybamm-team/pybammsolvers/issues/31

Fix IDAKLU bug with non-identity inverse mass matrices

---

benchmarks/different_model_options.py
benchmarks/time_solve_models.py
src/pybamm/expression_tree/array.py
src/pybamm/expression_tree/binary_operators.py
src/pybamm/expression_tree/concatenations.py
src/pybamm/expression_tree/discrete_time_sum.py
src/pybamm/expression_tree/functions.py
src/pybamm/expression_tree/independent_variable.py
src/pybamm/expression_tree/input_parameter.py
src/pybamm/expression_tree/interpolant.py
src/pybamm/expression_tree/matrix.py
src/pybamm/expression_tree/scalar.py
src/pybamm/expression_tree/state_vector.py
src/pybamm/expression_tree/symbol.py
src/pybamm/expression_tree/unary_operators.py
src/pybamm/expression_tree/vector.py
src/pybamm/models/event.py
src/pybamm/solvers/idaklu_jax.py
src/pybamm/solvers/processed_variable_time_integral.py
src/pybamm/type_definitions.py

This PR updates the type hints by replacing np.ndarray with npt.NDArray from numpy.typing. It was necessary because using npt.NDArray is the recommended way to define NumPy arrays in type hints.
Fixes #4512

Replace np.ndarray with npt.NDArray for improved type hinting

---

.pre-commit-config.yaml
pyproject.toml

Added `repo-review` pre-commit hook

---

docs/index.rst

Modifies `docs/index.rst` to use `button-ref` instead of `button-link`, ensuring the Contributor's Guide button links to `source/user_guide/contributing.html`
Fixes: #4911 

Fix broken link to Contributor's Guide in documentation

---

pyproject.toml
src/pybamm/expression_tree/concatenations.py

This PR removes `UP007` from ignored rules in `pyproject.toml` and updates type annotations to use `str | None` instead of `Optional[str]`.  
Fixes: #4924  

Enable UP007 rule for modern type annotations

---

pyproject.toml

Temporary pin as CasADi 3.7.0 was released today and causes segfaults with Python as we don't support the new changes yet here and in https://github.com/pybamm-team/pybammsolvers. Noticed in #4935.

Temporarily pin casadi<3.7.0

---

.github/workflows/docker.yml

Removed `linux/arm64` from platforms in the Docker workflow to fix build failures

---

docs/conf.py
docs/source/user_guide/installation/index.rst
pyproject.toml

I added this extension in 2023 via #3083, and it has been available on the RTD dashboard for a while now. As of 03/04/2025, it is deprecated and users are advised to switch to the server-side one – I'll enable it in the settings. The CSS customisations for the extension I had added to `pybamm.css` have been kept, as the extension doesn't support dark mode well yet.
xref: 
- https://github.com/readthedocs/sphinx-hoverxref/issues/312#issuecomment-2775944738
- https://about.readthedocs.com/blog/2024/07/addons-by-default/
- …

Drop `sphinx-hoverxref` extension

---

CHANGELOG.md
src/pybamm/expression_tree/parameter.py
src/pybamm/spatial_methods/finite_volume.py
tests/integration/test_models/test_full_battery_models/test_lithium_ion/test_compare_basic_models.py
tests/unit/test_experiments/test_experiment.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Removes a regularization factor of `1e-16` in the diffusion coefficient harmonic mean. I believe this term was included when pybamm still used normalized variables, but now it's unnecessary and causes noticeable error.
Minor things:
- Changes harmonic mean functional form to reduce the number of diffusion variables in codegen
- Reduces the size of a magic number in `FunctionParameter` from `1e-16` to `1e-300`
Fixes https://github.com/pybamm-team/PyBaMM/issues/4976
- The documentation …

Remove harmonic mean regularization

---

CHANGELOG.md
src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
src/pybamm/solvers/algebraic_solver.py
tests/unit/test_solvers/test_algebraic_solver.py
tests/unit/test_solvers/test_base_solver.py

Previously, the `AlgebraicSolver` would only declare success if the absolute tolerance of the residuals were below the `tol` threshold. However, the scipy solvers would frequently terminate if other thresholds were hit, such as `xtol` or `gtol`, and `AlgebraicSolver` may erroneously throw an error even after a successful solve
This PR:
- tightens `xtol` and `gtol` from `1e-8` to `1e-12` to reflect the fact that we desire `all(abs(f(x)) < tol)`
- updates the success criterion to terminate either if the solver successfully exits or `all(abs(f(x)) < tol)` is satisfied
- also changes the default solver in `ElectrodeSOHHalfCell` to trust-region instead of a minimizer
Please add a line in the relevant section of [CHANGELOG.md](https://github.com/pybamm-team/PyBaMM/blob/develop/CHANGELOG.md) to …

Update `AlgebraicSolver` tolerances + default `ESOH` solver method

---

CHANGELOG.md
src/pybamm/meshes/one_dimensional_submeshes.py
tests/unit/test_meshes/test_one_dimensional_submesh.py

Fixes a bug with `Exponential1DSubMesh` when the left edge is non-zero.
Fixes #4988 

Fix exponential mesh bug

---

CHANGELOG.md
src/pybamm/plotting/quick_plot.py

Fixes an issue where updating the slider of a quickplot could produce `NaN` values at the beginning or end of a timespan due to slight extrapolation because of floating point arithmetic issues.
For example, try running this simulation and moving the slider to the final time:
```python
import pybamm
model = pybamm.lithium_ion.SPM()
parameter_values = pybamm.ParameterValues("Chen2020")
parameter_values.update({"Current function [A]": 0})
solver = pybamm.IDAKLUSolver()
sim = pybamm.Simulation(model, parameter_values=parameter_values, solver=solver)
tf = 3600.04
sol = sim.solve([0, tf])
sol.plot()
```
Please confirm the following …

Fix `QuickPlot` extrapolation bug

---

src/pybamm/models/base_model.py

Previously, this was shown every time an ODE/DAE simulation was created. This made some doc examples look messy since they had numerous `Simulation` calls.

Only warn about default solver change once

---

CHANGELOG.md
src/pybamm/solvers/base_solver.py
src/pybamm/solvers/casadi_solver.py
src/pybamm/solvers/idaklu_solver.py
src/pybamm/solvers/jax_solver.py
src/pybamm/solvers/scipy_solver.py
tests/unit/test_solvers/test_base_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Let's you enable `"error"`, `"warn"`, or `"ignore"` on extrapolation events.

Add a solver option to change `on_extrapolation` behavior

---

CHANGELOG.md
src/pybamm/solvers/processed_variable.py

Speeds up initial sensitivitiy calculation in ProcessedVariable. The diagcat and vertcat is done once instead of every timestep
I did a simple test using the DFN model and one input paramter (current), before the change the timings were (over 10 runs)
```
(env-pybammsolvers) ➜  PyBaMM git:(develop) ✗ python test.py
Time taken to compute sensitivities: 0.05452 seconds
Time taken to compute sensitivities: 0.04619 seconds
Time taken to compute sensitivities: 0.04333 seconds
Time taken to compute sensitivities: 0.04116 seconds
Time taken to compute sensitivities: 0.04146 seconds
Time taken to compute sensitivities: 0.04142 seconds
Time taken to compute sensitivities: 0.04156 seconds
Time taken to compute sensitivities: 0.04135 seconds
Time taken to compute sensitivities: 0.04133 seconds
Time …
```

perf: speed up time loop in processed var init sens

---

.gitignore
pyproject.toml

I noticed in a different project that the hatch-vcs throws an error for builds outside of a git repo (such as downloading tarballs). This adds an invalid version number for any of those builds, but uses hatch-vcs if built from a git repo.

Add fallback version

---

docs/source/examples/notebooks/getting_started/tutorial-1-how-to-run-a-model.ipynb

This link frequently fails in the CI, and it just tells people how to run Jupyter notebooks

Remove flaky Jupyter link

---

CHANGELOG.md
src/pybamm/experiment/step/base_step.py
src/pybamm/experiment/step/steps.py
tests/unit/test_experiments/test_experiment_steps.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Fixes a bug that ignored the default duration of drive cycles for `CRate` steps and a bug that overwrote custom `period` arguments for drive cycles.
Fixes https://github.com/pybamm-team/PyBaMM/issues/5086 and https://github.com/pybamm-team/PyBaMM/issues/5087

Drive cycle: infer `duration` from data by default + fix `period` argument

---

src/pybamm/solvers/processed_variable_time_integral.py
tests/unit/test_simulation.py
tests/unit/test_solvers/test_solution.py

an addendum to #5063, which fixes explicit time integral so that the return value is the integral rather than the cumulative integral

bug: explicit-time-integral returns integral

---

CONTRIBUTING.md

The restructured text guide links have been failing in ReadTheDocs. I think our users can look up documentation on it without wikipedia or a direct guide, so it should be fine to remove this link

Remove failing link

---

src/pybamm/expression_tree/binary_operators.py
src/pybamm/expression_tree/operations/convert_to_casadi.py
src/pybamm/expression_tree/unary_operators.py
src/pybamm/spatial_methods/finite_volume.py
tests/__init__.py
tests/shared.py
tests/unit/test_expression_tree/test_operations/test_convert_to_casadi.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_spatial_methods/test_finite_volume/test_finite_volume.py
tests/unit/test_spatial_methods/test_finite_volume/test_grad_div_shapes.py

Allows for geometric input parameters with concatenation variables.

Allow geometric input parameters with concatenation variables

---

CHANGELOG.md
examples/scripts/drive_cycle.py
src/pybamm/experiment/step/base_step.py
tests/unit/test_experiments/test_experiment_steps.py
tests/unit/test_experiments/test_simulation_with_experiment.py

Passes a `t_eval` array to the `IDAKLUSolver` for drive cycles within experiments.

Drive cycle discontinuities in experiments

---

CHANGELOG.md
src/pybamm/spatial_methods/scikit_finite_element_3d.py

This PR resolves a non-deterministic `ShapeError` that occurred in the `ScikitFiniteElement3D` spatial method when simulating 3D thermal models.
The problem was when evaluating the gradient of a constant parameter, like thermal conductivity (lambda_eff), which PyBaMM simplifies to a pybamm.Scalar. The gradient method was not designed to handle a scalar input and would attempt an invalid matrix-scalar multiplication. 
Fixes #5142 

Fix non-deterministic ShapeError in 3D FEM gradient method

---

CHANGELOG.md
src/pybamm/models/full_battery_models/equivalent_circuit/__init__.py
src/pybamm/models/full_battery_models/equivalent_circuit/initial_state.py
src/pybamm/models/full_battery_models/lithium_ion/__init__.py
src/pybamm/models/full_battery_models/lithium_ion/initial_state.py
src/pybamm/parameters/parameter_values.py
src/pybamm/simulation.py
tests/unit/test_models/test_full_battery_models/test_equivalent_circuit/test_initial_state.py
tests/unit/test_parameters/test_parameter_values.py
tests/unit/test_simulation.py

Moves lithium ion-specific functionality out of the `ParameterValues` class into `pybamm.lithium_ion.set_initial_state` and adds an analogous `pybamm.equivalent_circuit.set_initial_state` function for the Thevenin model.
Fixes #5127 

Generalise initial state setting

---

CHANGELOG.md
src/pybamm/experiment/step/base_step.py
src/pybamm/solvers/base_solver.py
tests/integration/test_experiments.py
tests/unit/test_solvers/test_base_solver.py

Fixes a bug where the final duration of a drive cycle would not be inferred correctly.

Fix drive cycle duration bug

---

CHANGELOG.md
src/pybamm/models/submodels/interface/open_circuit_potential/base_hysteresis_ocp.py
src/pybamm/models/submodels/interface/open_circuit_potential/base_ocp.py
src/pybamm/models/submodels/interface/open_circuit_potential/one_state_differential_capacity_hysteresis_ocp.py
src/pybamm/models/submodels/interface/open_circuit_potential/one_state_hysteresis_ocp.py
src/pybamm/models/submodels/interface/open_circuit_potential/single_ocp.py

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

fix calculation of bulk ocp in hysteresis models

---

CHANGELOG.md
src/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_composite.py
src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py

Use the initial, not the reference, temperature when setting initial stoichiometries based on a target voltage so that $U(z_{\textrm{init}},T_{\textrm{init}}) = U_{\textrm{ref}}(z_{\textrm{init}}) + (T_{\textrm{init}} - T_{\textrm{ref}})dU/dT(z_{\textrm{init}}) = V_{\textrm{init}}$.

Use T_init in initial_state

---

CHANGELOG.md
src/pybamm/solvers/idaklu_solver.py
tests/unit/test_solvers/test_idaklu_solver.py

Companion PR to https://github.com/pybamm-team/pybammsolvers/pull/57
> Adds an optional method to fail the simulation if the solver is not making progress. This is useful when the parameters are ill-conditioned and the solver is making very slow progress, such as in optimization

Add options to terminate `IDAKLUSolver` early when there's little progress

---

CHANGELOG.md
src/pybamm/parameters/bpx.py
tests/unit/test_parameters/test_bpx.py

This PR fixes an issue where `pybamm.ParameterValues.create_from_bpx()` ignored the porosity specified in BPX files and used a hard-coded Bruggeman coefficient of 1.5 for all domains.  
The BPX importer now correctly reads the specified porosity and calculates the Bruggeman coefficient from the provided transport efficiency and porosity.
Fixes #5193
Bug fix:  BPX importer now uses correct porosity and Bruggeman coefficient.

Computing Bruggeman coefficient from BPX porosity instead of hardcoding

---

CHANGELOG.md
docs/source/user_guide/installation/index.rst

This PR adds an explicit warning to the installation documentation (`index.rst`) about the Conda recipe being unmaintained and several releases behind, as discussed in issue #5155. The warning advises users to install PyBaMM using pip for the latest features and solvers, following the guidance from the maintainers.
Documentation update
---

Added warning about installation through conda to docs and suggested installation via pip 

---

.github/workflows/run_periodic_tests.yml
.github/workflows/test_on_push.yml

See https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/ and https://pybamm.slack.com/archives/C04ARM97HAQ/p1758538737848599?thread_ts=1758538731.639099&cid=C04ARM97HAQ
cc @MarcBerliner, @agriyakhetarpal

[CI] Change MacOS runner from macos-13 to macos-15-intel
