pybamm-team/PyBaMM

- docs/source/expression_tree/independent_variable.rst
- docs/source/expression_tree/index.rst
- pybamm/__init__.py
- pybamm/expression_tree/independent_variable.py
- tests/test_expression_tree/test_independent_variable.py
Added independent variable to expression tree hierarchy
Fixes #25
> #25 add independent variable

- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/domain.py
- pybamm/expression_tree/matrix.py
- pybamm/expression_tree/parameter.py
- pybamm/expression_tree/scalar.py
- pybamm/expression_tree/symbol.py
- pybamm/expression_tree/unary_operators.py
- pybamm/expression_tree/variable.py
- pybamm/expression_tree/vector.py
> #28 update documentation format to numpy doc format

- pybamm/expression_tree/symbol.py
- tests/test_expression_tree/test_symbol.py
> #31 change __repr__ for symbol to __class__(id, name, parent expression)

- pybamm/discretisations/base_discretisation.py
- tests/test_discretisations/test_base_discretisations.py
> #42 modify model.initial_conditions in place

- docs/source/expression_tree/binary_operator.rst
- docs/source/expression_tree/unary_operator.rst
- pybamm/__init__.py
- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/unary_operators.py
- tests/test_expression_tree/test_binary_operators.py
- tests/test_expression_tree/test_unary_operators.py
> #36 add power binary operator, and unary negate and abs operators

- tests/test_timer.py
Copy test for timer from Pints
> add timer test from Pints (accidentally deleted previously)

- pybamm/expression_tree/concatenations.py
- pybamm/expression_tree/symbol.py
- setup.py
- tests/test_discretisations/test_base_discretisations.py
- tests/test_expression_tree/test_concatenations.py
- tests/test_expression_tree/test_symbol.py
> #85 constrain domains to be sorted according to KNOWN_DOMAINS

- tests/test_discretisations/test_base_discretisations.py
- tests/test_expression_tree/test_binary_operators.py
- tests/test_expression_tree/test_concatenations.py
- tests/test_expression_tree/test_symbol.py
- tests/test_parameters/test_parameter_values.py
Changes to testing functions only. 
Fixes #95
> #95 replace assertTrue(isinstance by assertIsInstance

- CONTRIBUTING.md
- examples/notebooks/DFN.ipynb
- examples/notebooks/README.md
- examples/notebooks/SPM.ipynb
- examples/notebooks/SPMe.ipynb
- examples/notebooks/add-discretisation.ipynb
- examples/notebooks/add-model.ipynb
- examples/notebooks/add-parameters.ipynb
- examples/notebooks/add-solver.ipynb
- examples/notebooks/change-settings.ipynb
- examples/notebooks/compare-models.ipynb
- examples/notebooks/discretisations/finite-volumes.ipynb
- examples/notebooks/expression-tree/discretisation.ipynb
- examples/notebooks/expression-tree/expression-tree.ipynb
- examples/notebooks/expression-tree/overview.ipynb
- examples/notebooks/expression-tree/parameters.ipynb
- examples/notebooks/expression-tree/solver.ipynb
- examples/notebooks/models/DFN.ipynb
- examples/notebooks/models/SPM.ipynb
- examples/notebooks/models/SPMe.ipynb
- examples/notebooks/models/lead-acid-composite.ipynb
- examples/notebooks/models/lead-acid-foqs.ipynb
- examples/notebooks/models/lead-acid-full.ipynb
- examples/notebooks/models/lead-acid-loqs.ipynb
- examples/notebooks/run-model.ipynb
- examples/notebooks/simple-diffusion.ipynb
- examples/notebooks/solvers/scipy-integrate.ipynb
- run-tests.py
Rewrite examples/notebooks/README.md and set up a possible structure for the example notebooks
Fixes #99
> Issue 99 examples structure

- pybamm/models/submodels/interface.py
- pybamm/parameters/parameter_values.py
- tests/test_models/test_interface.py
- tests/test_parameters/test_parameter_values.py
Fixes #51 
Just a simple case where the current is constant with a value of 1. Will need to change to a time-dependent current once we have a current function
> Issue 51 homogeneous reactions

- pybamm/__init__.py
- pybamm/discretisations/base_discretisation.py
- pybamm/discretisations/base_mesh.py
- pybamm/expression_tree/independent_variable.py
- tests/test_discretisations/test_base_discretisations.py
- tests/test_expression_tree/test_independent_variable.py
> Issue 104 time and space

- pybamm/expression_tree/array.py
- pybamm/expression_tree/matrix.py
- pybamm/expression_tree/symbol.py
- pybamm/expression_tree/vector.py
- tests/test_expression_tree/test_matrix.py
- tests/test_expression_tree/test_symbol.py
> Issue 112 symbol repr

- docs/source/solvers/index.rst
- docs/source/solvers/scikits_solvers.rst
> #116 add scikits.odes solvers to docs

- pybamm/discretisations/base_discretisation.py
> #127 split up disc.process_model

- pybamm/discretisations/base_discretisation.py
- pybamm/models/base_model.py
- tests/test_discretisations/test_base_discretisations.py
- tests/test_models/test_base_model.py
- tests/test_solvers/test_scikits_solvers.py
Change algebraic list to dict and update model well-posedness tests
Fixes #128
> Issue 128 algebraic list to dict

- tests/test_solvers/test_scipy_solver.py
Small change to for solver tests to call the discretisation from shared.py
> changed to use the mesh from shared

- README.md
> Issue 123 scikit instruct

- CONTRIBUTING.md
- README.md
Fixes #151 
Removed all `$` from README.md and CONTRIBUTING.md to make it easier to copy/past from
> Issue 151 dollar

- pybamm/models/base_model.py
> Updated the update model function so that it also works for algebraic equations

- .travis.yml
- CONTRIBUTING.md
- README.md
- requirements-dev.txt
- requirements-docs.txt
- requirements.txt
> #131 remove requirement files and update CONTRIBUTING and travis

- pybamm/expression_tree/concatenations.py
- tests/test_expression_tree/test_concatenations.py
@Scottmar93 I think this should fix it
Fixes #163
> #163 attempt broadcasting bug fix

- pybamm/discretisations/discretisation.py
- pybamm/models/base_model.py
- pybamm/models/lead_acid/loqs.py
- pybamm/models/li_ion/single_particle_model.py
- pybamm/models/reaction_diffusion.py
- pybamm/models/simple_ode_model.py
- pybamm/parameters/parameter_values.py
- pybamm/solvers/dae_solver.py
- pybamm/solvers/ode_solver.py
- pybamm/solvers/scikits_dae_solver.py
- pybamm/solvers/scikits_ode_solver.py
- pybamm/solvers/scipy_solver.py
- tests/test_discretisations/test_discretisation.py
- tests/test_models/standard_model_tests.py
- tests/test_models/test_lead_acid.py
- tests/test_solvers/test_scikits_solvers.py
- tests/test_solvers/test_scipy_solver.py
Implement cut-off events in solvers, add cut-off events to models.
Fixes #185
> Issue 185 cutoff event

- pybamm/expression_tree/binary_operators.py
- tests/test_expression_tree/test_symbol.py
reopen #228 , see https://github.com/pybamm-team/PyBaMM/pull/228#discussion_r269988444
> #203 add multiplication by one and division by one

- pybamm/models/base_models.py
- tests/test_models/test_base_model.py
Add a small extra check for well-posedness
Fixes #230
> #230 add new algebraic check

- input/parameters/lead-acid/default.csv
- input/parameters/lithium-ion/mcmb2528_lif6-in-ecdmc_lico2_parameters_Dualfoil.csv
- pybamm/parameters/standard_parameters_lead_acid.py
- pybamm/parameters/standard_parameters_lithium_ion.py
- tests/test_parameters/test_parameter_values.py
- tests/test_parameters/test_standard_parameters_lead_acid.py
Use scipy constants
Fixes #243
> #243 use scipy constants

- pybamm/discretisations/discretisation.py
- pybamm/models/lithium_ion/dfn.py
- pybamm/spatial_methods/finite_volume.py
fix dfn
Fixes dfn only working for 1 particle 
> added multiple particle support to boundary value

- pybamm/expression_tree/binary_operators.py
- tests/test_expression_tree/test_binary_operators.py
Overload sparse matrix multiplication to explicitly be elementwise (Hadamard product)
Fixes #260
> Issue 260 multiply

- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/broadcasts.py
- pybamm/expression_tree/concatenations.py
- pybamm/expression_tree/symbol.py
- pybamm/expression_tree/unary_operators.py
- pybamm/solvers/dae_solver.py
- tests/test_expression_tree/test_concatenations.py
- tests/test_expression_tree/test_matrix.py
- tests/test_expression_tree/test_symbol.py
- tests/test_models/standard_model_tests.py
Fixes #253 
See issue for description
> Issue 253 simplify bug

- pybamm/models/base_models.py
- pybamm/models/lithium_ion/dfn.py
- pybamm/models/lithium_ion/spm.py
- pybamm/models/lithium_ion/spme.py
- pybamm/models/submodels/electrode.py
- pybamm/models/submodels/electrolyte_current.py
- pybamm/models/submodels/electrolyte_diffusion.py
- pybamm/models/submodels/particle.py
> Add dimensional outputs to SPM, SPMe, DFN

- .requirements-docs.txt
- docs/index.rst
> #190 fix read the docs

- examples/notebooks/spatial_methods/finite-volumes.ipynb
- pybamm/spatial_methods/finite_volume.py
- tests/unit/test_spatial_methods/test_finite_volume.py
> #293 change 2*pi to 4*pi**2

- pybamm/expression_tree/binary_operators.py
- tests/unit/test_expression_tree/test_matrix.py
> #301 fix bug

- pybamm/models/lithium_ion/dfn.py
- pybamm/models/lithium_ion/spm.py
- pybamm/models/lithium_ion/spme.py
- pybamm/models/submodels/particle.py
- pybamm/parameters/electrical_parameters.py
- tests/unit/test_models/test_lead_acid/test_loqs.py
- tests/unit/test_models/test_lithium_ion/test_lithium_ion_spm.py
Change standard electrical variables to allow non-positive current
Fixes #312 
> Issue 312 non positive current

- docs/source/solvers/base_solver.rst
- docs/source/solvers/base_solvers.rst
- docs/source/solvers/index.rst
- docs/tutorials/add-solver.rst
- examples/notebooks/README.md
> add base solvers to docs and fix solver tutorial

- pybamm/expression_tree/binary_operators.py
- tests/unit/test_expression_tree/test_matrix.py
> Issue 341 simp

- pybamm/expression_tree/simplify.py
- tests/unit/test_expression_tree/test_simplify.py
Simplify now goes through a sequences of additions or subtractions, counting and combining identical terms
Fixes #323 
> #323 simplify identical terms in addition/subtraction

- .travis.yml
Fixes #365 
Not much here, just turns on notebook tests for the continuous builds on travis
> #354 turn on continuous notebook tests

- pybamm/models/base_models.py
> #390 update timescale

- CONTRIBUTING.md
- examples/scripts/compare_lead_acid.py
- pybamm/__init__.py
- pybamm/discretisations/discretisation.py
- pybamm/expression_tree/simplify.py
- pybamm/logger.py
- pybamm/models/base_models.py
- pybamm/parameters/parameter_values.py
- pybamm/solvers/dae_solver.py
- pybamm/solvers/ode_solver.py
- tests/unit/test_logger.py
Add very simple logger. Can add more functionality as needed
Fixes #398 
> #398 add basic logger

- pybamm/parameters/standard_parameters_lithium_ion.py
> #404 change s to 1-t_plus

- pybamm/models/base_models.py
- pybamm/models/lead_acid/composite_capacitance.py
- pybamm/models/lead_acid/loqs_capacitance.py
- pybamm/models/lead_acid/newman_tiedemann.py
- pybamm/models/lead_acid/newman_tiedemann_capacitance.py
- pybamm/models/lithium_ion/dfn.py
- pybamm/models/submodels/electrode.py
- pybamm/models/submodels/electrolyte_current.py
- tests/unit/test_models/test_base_model.py
- tests/unit/test_models/test_lead_acid/test_composite_capacitance.py
- tests/unit/test_models/test_lead_acid/test_loqs_capacitance.py
- tests/unit/test_models/test_lead_acid/test_newman_tiedemann.py
- tests/unit/test_models/test_lead_acid/test_newman_tiedemann_capacitance.py
- tests/unit/test_models/test_lithium_ion/test_lithium_ion_dfn.py
- tests/unit/test_models/test_submodels/test_electrode.py
- tests/unit/test_models/test_submodels/test_electrolyte_current.py
> #416 change default_solver to a property for base model class

- pybamm/discretisations/discretisation.py
- pybamm/models/base_models.py
- pybamm/models/lead_acid/loqs.py
- pybamm/models/lithium_ion/dfn.py
- pybamm/models/lithium_ion/spm.py
- pybamm/models/lithium_ion/spme.py
- pybamm/models/reaction_diffusion.py
- tests/integration/test_models/standard_model_tests.py
- tests/integration/test_models/standard_output_tests.py
- tests/unit/test_models/test_base_model.py
- tests/unit/test_models/test_lead_acid/test_composite_capacitance.py
- tests/unit/test_models/test_lead_acid/test_loqs.py
- tests/unit/test_models/test_lead_acid/test_loqs_capacitance.py
- tests/unit/test_models/test_lead_acid/test_newman_tiedemann.py
- tests/unit/test_models/test_lead_acid/test_newman_tiedemann_capacitance.py
- tests/unit/test_models/test_lithium_ion/test_lithium_ion_dfn.py
- tests/unit/test_models/test_lithium_ion/test_lithium_ion_spm.py
- tests/unit/test_models/test_lithium_ion/test_lithium_ion_spme.py
- tests/unit/test_models/test_reaction_diffusion.py
- tests/unit/test_models/test_submodels/test_electrode.py
- tests/unit/test_models/test_submodels/test_electrolyte_current.py
> Issue 428 refactor default properties

- pybamm/__init__.py
- pybamm/expression_tree/exceptions.py
- pybamm/models/submodels/electrolyte_current.py
- pybamm/spatial_methods/finite_volume.py
- pybamm/spatial_methods/spatial_method.py
- tests/unit/test_spatial_methods/test_finite_volume.py
- tests/unit/test_spatial_methods/test_spatial_methods.py
> Issue 421 shape test

- pybamm/expression_tree/symbol.py
- pybamm/spatial_methods/finite_volume.py
- tests/unit/test_expression_tree/test_unary_operators.py
> #444 implement __getitem__

- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/symbol.py
- pybamm/expression_tree/unary_operators.py
- tests/unit/test_expression_tree/test_symbolic_diff.py
> Issue 446 faster diff

- pybamm/models/base_models.py
- pybamm/solvers/dae_solver.py
- tests/integration/test_models/standard_output_tests.py
- tests/integration/test_models/test_reaction_diffusion.py
- tests/unit/test_discretisations/test_discretisation.py
- tests/unit/test_expression_tree/test_binary_operators.py
- tests/unit/test_expression_tree/test_simplify.py
- tests/unit/test_expression_tree/test_symbol.py
- tests/unit/test_models/test_base_model.py
- tests/unit/test_solvers/test_dae_solver.py
Fixes #468 
Also used this branch to remove some of the tests that sometimes fail (timer tests, tolerance test for consistent initial conditions)
> #468 add check for variables in list of variables, and remove some bad tests

- pybamm/discretisations/discretisation.py
- pybamm/spatial_methods/spatial_method.py
Mass matrix is csr format
Fixes #485
> #485 mass to csr

- pybamm/solvers/dae_solver.py
- tests/unit/test_solvers/test_scikits_solvers.py
> #496 multiply ydot by mass

- MANIFEST.in
- pybamm/models/full_battery_models/base_battery_model.py
- pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
- setup.py
- tests/unit/test_models/test_base_model.py
Fixes #498 
also minor fix with path issues in lead acid parameters
> Issue 498 find packages

- pybamm/models/full_battery_models/base_battery_model.py
- pybamm/models/full_battery_models/lead_acid/base_lead_acid_model.py
- tests/unit/test_models/test_base_model.py
> #494 change os.getcwd to pybamm.root_dir

- pybamm/expression_tree/symbol.py
- tests/unit/test_expression_tree/test_symbol.py
> Issue 511 evaluate for shape using domain

- pybamm/expression_tree/functions.py
- tests/unit/test_parameters/test_current_functions.py
simplify constant current to scalar
Fixes #518 
> #518 simplify const current

- pybamm/models/full_battery_models/base_battery_model.py
- pybamm/models/submodels/electrolyte/base_electrolyte_diffusion.py
- pybamm/models/submodels/electrolyte/stefan_maxwell/conductivity/surface_potential_form/leading_surface_form_stefan_maxwell_conductivity.py
- pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/constant_stefan_maxwell_diffusion.py
- pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/full_stefan_maxwell_diffusion.py
- pybamm/models/submodels/electrolyte/stefan_maxwell/diffusion/leading_stefan_maxwell_diffusion.py
- pybamm/models/submodels/interface/base_interface.py
- pybamm/models/submodels/interface/inverse_kinetics/inverse_butler_volmer.py
- pybamm/models/submodels/interface/kinetics/base_kinetics.py
- pybamm/models/submodels/thermal/base_thermal.py
- pybamm/models/submodels/thermal/full_thermal.py
- pybamm/models/submodels/thermal/isothermal.py
- pybamm/models/submodels/thermal/lumped_thermal.py
- tests/unit/test_models/test_submodels/test_electrolyte/test_stefan_maxwell/test_conductivity/test_surface_form/test_leading_surface_form_stefan_maxwell_conductivity.py
Sort out averages from #510 
Fixes #516 
> Issue 516 averages

- pybamm/spatial_methods/scikit_finite_element.py
- tests/shared.py
- tests/unit/test_expression_tree/test_binary_operators.py
- tests/unit/test_expression_tree/test_jac.py
- tests/unit/test_expression_tree/test_simplify.py
- tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_spm.py
- tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_spme.py
- tests/unit/test_parameters/test_current_functions.py
- tests/unit/test_processed_variable.py
Added some more tests 
Fixes #526 
> #526 add some more tests

- scripts/install_scikits_odes.sh
> #538 update sundials url

- README.md
- examples/scripts/compare_lithium_ion.py
added link to msm project meeting slides. cleaned up `compare_lithium_ion.py` a bit
> add link to msm project meeting slides

- pybamm/processed_variable.py
- tests/unit/test_processed_variable.py
Check that the right arguments are passed to `ProcessedVariable`
Fixes #541 
> Issue 541 processed variable errors

- pybamm/expression_tree/symbol.py
> #558 print out named scalar as name = value in Symbol.render()

- examples/notebooks/change-input-current.ipynb
- pybamm/parameters/parameter_values.py
- pybamm/parameters/standard_current_functions/get_current_data.py
- results/drive_cycles/discharge_rest.py
- tests/unit/test_parameters/test_update_parameters.py
The parameters in the current function are updated as part of `update_model`
Fixes #584 
> Issue 584 update current

- examples/notebooks/create-model.ipynb
- pybamm/geometry/geometry.py
- pybamm/processed_variable.py
- tests/unit/test_geometry/test_geometry.py
- tests/unit/test_processed_variable.py
> Issue 597 geometry

- pybamm/solvers/base_solver.py
adds the event description to solution.terminaton 
Fixes #640 
> #640 add termination event to solution

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
Add changelog and update PR template to try to keep it up to date
Fixes #659 
> #659 add changelog

- setup.py
Fixes #679, hopefully fixes binder
> #679 make jupyter install by default and add version to package data

- INSTALL-LINUX.md
- scripts/install_scikits_odes.sh
Fix installation issues with scikits-odes (increment sundials version).
We now use the same version in both scikits and idaklu, but I think it's worth keeping separate in case we want to update ida klu (note sundials 5.0.0 is now out)
Fixes #715
> #715 update sundials to 4.1.0

- examples/scripts/compare_comsol/compare_comsol_DFN.py
Fix bug in the compare_comsol script
Fixes #689 
> #689 fix quickplot bug

- pybamm/processed_variable.py
Tiny bug fix for input parameters
> fix bug in input parameter processed variable

- examples/notebooks/change-input-current.ipynb
- examples/scripts/compare_comsol/compare_comsol_DFN.py
Fixed bugs in examples
Fixes #763
> Issue 763 compare comsol

- LICENSE.txt
> update license year

- INSTALL-LINUX.md
- scripts/install_scikits_odes.sh
Update sundials version for scikits
Fixes #778
> update sundials for scikits odes

- pybamm/solvers/base_solver.py
- pybamm/solvers/casadi_solver.py
- pybamm/solvers/dae_solver.py
- pybamm/solvers/ode_solver.py
- tests/unit/test_solvers/test_casadi_solver.py
- tests/unit/test_solvers/test_ode_solver.py
- tests/unit/test_solvers/test_scikits_solvers.py
- tests/unit/test_solvers/test_scipy_solver.py
Fixes external variables with the casadi solver.
Will leave this issue open as there is more to do.
> Issue 775 casadi external

- pybamm/expression_tree/functions.py
- pybamm/processed_variable.py
- tests/unit/test_solvers/test_solution.py
> Fix issue 793 solution evaluation with Electrode height input

- pybamm/processed_variable.py
- pybamm/simulation.py
- pybamm/solvers/solution.py
- tests/unit/test_simulation.py
Fixes solution appending in the simulation
Fixes #793 
> #793 fix simulation stepping

- input/parameters/lithium-ion/anodes/graphite_mcmb2528_Marquis2019/parameters.csv
- input/parameters/lithium-ion/cathodes/lico2_Marquis2019/parameters.csv
> #805 remove params

- INSTALL-LINUX.md
Removes some repeated instructions and fixes some small typos. 
Fixes #814
> #814 edit install instructions

- pybamm/simulation.py
- pybamm/solvers/base_solver.py
- pybamm/solvers/casadi_solver.py
- tests/unit/test_simulation.py
- tests/unit/test_solvers/test_base_solver.py
- tests/unit/test_solvers/test_scikits_solvers.py
- tests/unit/test_solvers/test_scipy_solver.py
- Fix finding discontinuities when t is dimensional
- Don't add discontinuiities to ODE model
Fixes #837 
> Issue 837 car current

- examples/scripts/DFN.py
- pybamm/models/full_battery_models/base_battery_model.py
- pybamm/solvers/solution.py
- pybamm/util.py
- setup.py
Removes dependency that was causing problems
Fixes #833 
> #833 manual implementation of levenshtein

- CHANGELOG.md
- pybamm/parameters/parameter_values.py
- pybamm/util.py
- tests/unit/test_util.py
Adds a search functionailty to `pybamm.FuzzyDict` so that users can search `ParameterValues` and `model.variables`
Fixes #869 
> Issue 869 search

- CHANGELOG.md
- pybamm/models/submodels/external_circuit/base_external_circuit.py
- pybamm/models/submodels/external_circuit/function_control_external_circuit.py
- pybamm/parameters/parameter_values.py
- tests/integration/test_models/test_submodels/test_external_circuit/test_function_control.py
Reformat external circuit submodels to get rid of unnecessary abstraction
Fixes #878 
> #878 reformat external circuit

- pybamm/parameters/parameter_values.py
Added `_ipython_key_completions_()` function to parameter values.
Fixes #889 
- [] All tests pass: `$ python run-tests.py --unit`
- [] The documentation builds: `$ cd docs` and then `$ make clean; make html`
> Issue 889 tab complete parameter values

- pybamm/models/full_battery_models/base_battery_model.py
> #911 fix bug

- INSTALL-WINDOWS-WSL.md
- INSTALL-WINDOWS.md
- README.md
Added basic Windows installation instructions (very basic, just for the workshop). I kept the WSL instruction for more advanced users (maybe they can be removed, but I find WSL quite useful).
Fixes #892
Minor change in the documentation, so none of the points below applies.
> Issue 892 install windows

- pybamm/models/submodels/external_circuit/function_control_external_circuit.py
- tests/unit/test_models/test_submodels/test_external_circuit/test_function_control.py
Make time dimensional in the voltage and power models
Fixes #902
> #902 make time dimensional

- INSTALL-LINUX-MAC.md
> #969 add brew commands [ci skip]

- pybamm/solvers/casadi_solver.py
> #981 fix casadi solver documentation

- .github/workflows/test_on_push.yml
Adds missing CODECOV_TOKEN to the workflow. Will not work until CODECOV_TOKEN is configured as a Secret in GitHub Actions. 
Fixes # None
> Adds CODECOV_TOKEN

- .github/workflows/test_on_push.yml
Attempt to restore code coverage reports.
There was a typo in the code coverage step in the github workflow, causing the code coverage step to never happen.
> Fix codecov integration

- examples/faraday-tech/5-new-parameter-set.ipynb
Here is the notebook for the case study on how to define a new parameter set.
> #998 added case study new parameter set

- setup.py
change version number to 0.2.2.post2
> version number

- .github/workflows/build_wheels_and_publish.yml
- setup.py
Switch from test PyPI to regular PyPI
> Fix PyPI upload

- setup.py
Following fix of description in setup.py
> Bump post version number

- .github/workflows/build_wheels_and_publish.yml
- setup.py
> Fix description on PyPI

- pybamm/spatial_methods/scikit_finite_element.py
Update scikit fem method to get rid of deprecation warnings. Thanks to @kinnala for the tips
Fixes #857 
> Issue 857 scikit fem

- CHANGELOG.md
- examples/scripts/compare_spectral_volume.py
- pybamm/__init__.py
- pybamm/meshes/one_dimensional_submeshes.py
- pybamm/spatial_methods/spectral_volume.py
- pybamm/spatial_methods/spectral_volumes.py
- run-tests.py
- tests/integration/test_spatial_methods/test_spectral_volume.py
- tests/unit/test_meshes/test_one_dimensional_submesh.py
- tests/unit/test_spatial_methods/test_spectral_volume.py
Added the Spectral Volumes spatial method (as /pybamm/spatial_methods/spectral_volumes.py) and the specific submesh that it works with (added to /pybamm/meshes/one_dimensional_submeshes.py), called SpectralVolumes1DSubMesh, as described in #900 .
> Spectral volumes

- pybamm/models/submodels/interface/sei/base_sei.py
Fixes the units for a variable in the EC SEI submodel
Fixes #1140 
> #1140 fix EC SEI bug

- .all-contributorsrc
Trying to fix the json for all contributors
> attempting to fix json

- requirements.txt
- setup.py
Pin jax version for the develop branch
> fix jax version

- .github/release_checklist.md
- requirements.txt
- setup.py
Pin jax version for the release branch
> pin jax version

- .github/workflows/test_on_push.yml
- tox.ini
I fixed the issue of coverage not running (it was a typo in the if statement). Another issue appeared with `tox -e coverage` for which I got around, but not sure if I did in the most efficient way. However, the coverage is now ran but the report still not uploaded.
Fixes #1191
> Fix coverage

- docs/source/spatial_methods/index.rst
- docs/source/spatial_methods/spectral_volume.rst
- examples/notebooks/models/thermal-models.ipynb
- pybamm/spatial_methods/spectral_volume.py
Fix some typos in the thermal models notebook and add rst file for spectral volume docs
Fixes #1199 and #1189 
> #1189 #1199 fix typo and add spectral volumes rst

- setup.py
Add `python_requires` to `setup.py` to enforce using correct version of python
Fixes #1239 
> #1239 add python requires

- examples/scripts/compare_comsol/compare_comsol_DFN.py
- pybamm/solvers/solution.py
Make sure solution timescale and lengthscale are updated when the model is assigned as an attribute, instead of just in the init
> move length scale evaluation

- .github/workflows/test_on_push.yml
- pybamm/CITATIONS.txt
- pybamm/citations.py
- pybamm/solvers/jax_solver.py
- tests/unit/test_citations.py
Change version for graphviz for windows
also fixes #1243 
> Fix graphviz version for windows

- .github/workflows/test_on_push.yml
- CHANGELOG.md
- docs/conf.py
- pybamm/CITATIONS.txt
- pybamm/citations.py
- pybamm/solvers/jax_solver.py
- setup.py
- tests/unit/test_citations.py
Final release for 0.3.0, with some minor bug fixes from the beta
> Release 0.3.0

- .github/workflows/test_on_push.yml
> try CI fix

- .github/workflows/update_parameter_sets_doc.yml
- pybamm/parameters/parameter_sets.py
- pybamm/parameters/update_parameter_sets_doc.py
- tests/unit/test_parameters/test_update_parameter_sets_doc.py
Add 'develop' branch in the workflow
Add extra indentation in docstring
Fixes #1386
> Fix workflow and update_parameter_sets.py

- pybamm/simulation.py
- tests/unit/test_experiments/test_simulation_with_experiment.py
Small bug fix from previous PR
> copy cycles to avoid overwrite

- setup.py
Adds `pybamm.mplstyle` to `pybamm_data`
> add mplstyle to package data

- docs/requirements.txt
Update requirements so docs can build
> add pybtex to rtd requirements

- scripts/install_KLU_Sundials.py
The website for sundials changed, and the download url with it.
Thanks @brosaplanella for reporting the issue
> Fix sundials download link

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- docs/index.rst
- docs/tutorials/add-model.rst
- docs/tutorials/add-parameter-values.rst
- docs/tutorials/add-solver.rst
- docs/tutorials/add-spatial-method.rst
- examples/notebooks/Creating Models/5-a-simple-SEI-model.ipynb
- examples/notebooks/README.md
- examples/notebooks/change-settings.ipynb
- examples/notebooks/compare-comsol-discharge-curve.ipynb
- examples/notebooks/models/DFN.ipynb
- examples/notebooks/models/SPMe.ipynb
- examples/notebooks/rate-capability.ipynb
- examples/notebooks/spatial_methods/finite-volumes.ipynb
- pybamm/expression_tree/broadcasts.py
Fix documentation and links
Also fixes #1373 
> fix documentation and links

- .github/workflows/build_wheels.yml
- build_manylinux_wheels/install_sundials.sh
Add minimal build for windows ahead of the release (no sundials on windows yet until #1417  is merged.)
Fix a couple of mistakes
> Add minimal wheel build for windows

- pybamm/solvers/processed_variable.py
- pybamm/solvers/solution.py
- tests/unit/test_experiments/test_simulation_with_experiment.py
Fix a bug with saving a solution
Fixes #1440 
> #1440 fix sol.save bug

- pybamm/solvers/jax_bdf_solver.py
- setup.py
Fixes #1460
Question, does this need an addition in the `CHANGELOG.md`?
> #1460 update jax versions

- .github/workflows/build_wheels.yml
Fixes a couple of silly mistakes.
> Windows build

- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/broadcasts.py
- pybamm/expression_tree/concatenations.py
- pybamm/expression_tree/exceptions.py
- pybamm/expression_tree/functions.py
- pybamm/expression_tree/independent_variable.py
- pybamm/expression_tree/input_parameter.py
- pybamm/expression_tree/interpolant.py
- pybamm/expression_tree/matrix.py
- pybamm/expression_tree/state_vector.py
- pybamm/expression_tree/symbol.py
- pybamm/expression_tree/unary_operators.py
- pybamm/expression_tree/vector.py
Format code and docstring of expression tree
> Format docstring of expression tree

- pybamm/batch_study.py
Added missing arguments in the `solve` method of `BatchStudy`.
Doing something like this right now - 
```py
import pybamm
model = {'0': pybamm.lithium_ion.DFN(
options={
"particle mechanics": "swelling and cracking",
}
)
}
params = {'0': pybamm.ParameterValues(chemistry=pybamm.parameter_sets.Ai2020)}
experiment = {'0': pybamm.Experiment(
[
("Discharge at C/10 for 10 hours or until 3.3 V",
"Rest for 1 hour",
"Charge at 1 A until 4.1 V",
"Hold at 4.1 V until 50 mA",
"Rest for 1 hour")
]
* 3,
)
}
sim = pybamm.BatchStudy(model, parameter_values=params, experiments=experiment)
sim.solve(calc_esoh=False)
sim.plot()
```
gives an error - 
```bash
Traceback (most recent call last):
File "C:\Users\Saransh\Saransh_softwares\Learning Projects\python\PyBamm\Ai2020.py", line 26, in <module> …
```
> Add missing arguments in the solve method of BatchStudy class

- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/unary_operators.py
- tests/unit/test_expression_tree/test_binary_operators.py
- tests/unit/test_expression_tree/test_unary_operators.py
Add some special cases involving negation
> double negation case

- pybamm/expression_tree/broadcasts.py
- pybamm/expression_tree/concatenations.py
- pybamm/expression_tree/functions.py
- pybamm/expression_tree/independent_variable.py
- pybamm/expression_tree/printing/print_name.py
- pybamm/expression_tree/unary_operators.py
- pybamm/models/submodels/electrolyte_conductivity/composite_conductivity.py
- pybamm/models/submodels/electrolyte_conductivity/full_conductivity.py
- pybamm/models/submodels/electrolyte_diffusion/base_electrolyte_diffusion.py
- pybamm/models/submodels/electrolyte_diffusion/full_diffusion.py
- pybamm/models/submodels/interface/base_interface.py
- pybamm/models/submodels/tortuosity/base_tortuosity.py
- pybamm/parameters/lithium_ion_parameters.py
- tests/unit/test_expression_tree/test_broadcasts.py
- tests/unit/test_expression_tree/test_concatenations.py
- tests/unit/test_expression_tree/test_functions.py
- tests/unit/test_expression_tree/test_independent_variable.py
- tests/unit/test_expression_tree/test_printing/test_print_name.py
- tests/unit/test_expression_tree/test_unary_operators.py
- tests/unit/test_parameters/test_base_parameters.py
- Add to_equation in Broadcasts, Concatenation, Log, Sinh, Integral and Independent Variable
- Modify print_name
> Add to_equation for SPMe

- .github/workflows/update_parameter_sets_doc.yml
Update parameter_sets workflow
> Update parameter_sets workflow

- README.md
Add pypi and conda-forge badges in the readme for better tracking
> Add packages badge in readme

- .github/ISSUE_TEMPLATE/bug_report.md
It would be nice to know the version of `PyBaMM` and `Python` that a user is using beforehand (given the number of version issues we are getting).
> Ask about PyBaMM and Python version in bug reports

- pybamm/CITATIONS.txt
- pybamm/models/submodels/external_circuit/function_control_external_circuit.py
- tests/unit/test_citations.py
> #1614 reorder citations and add CCCV ref

- setup.py
Create 21.8.post1 release in setup.py
> Release 21.8.post1

- .github/workflows/build_sdist.yml
Remove .zip from sdist as only one sdist may be uploaded per release.
https://github.com/pybamm-team/PyBaMM/runs/3596099765?check_suite_focus=true
> Remove .zip sdist

- .github/workflows/build_sdist.yml
- vcpkg-configuration.json
Fix failing build wheels workflow
Tested on fork
https://github.com/priyanshuone6/PyBaMM/runs/3620734402?check_suite_focus=true
> Fix failing build wheels

- docs/requirements.txt
Fix the latest docs deployment
Fixes #1693 
> Pin `jax` and `jaxlib` versions - fix docs deployment

- CHANGELOG.md
- setup.py
> Drop support for Python 3.6

- vcpkg-configuration.json
Update baseline
Test workflow run
https://github.com/priyanshuone6/PyBaMM/runs/3799185566?check_suite_focus=true
> Fix failing workflow

- pybamm/solvers/casadi_solver.py
- pybamm/solvers/processed_variable.py
- pybamm/solvers/solution.py
Fixes a bug in the sensitivity extraction that occurs when an event is triggered
Fixes #1727 
> I1727 sensitivity event bug

- CITATION.cff
- vcpkg-configuration.json
Update baseline and CITATION.cff version
> Update baseline and CITATION version

- pybamm/models/submodels/interface/base_interface.py
Add dimensional versions of entropic change variables
> Add dimensional entropic change variables

- .github/workflows/test_on_push.yml
- CONTRIBUTING.md
- tox.ini
Separate unit and integration tests in Mac and Windows CI for faster failure
> try separating unit and integration tests on windows and mac

- pybamm/experiments/experiment.py
- pybamm/simulation.py
> #1818 fix voltage for batteries in series

- pybamm/experiments/experiment.py
Fixes typo in deprecation message
> fix deprecation message

- .github/workflows/build_sdist.yml
Fail the workflow if build_wheels fails
> Fix sdist workflow

- .github/workflows/test_on_push.yml
> switch coverage to python 3.7

- pybamm/models/submodels/interface/kinetics/base_kinetics.py
> Add print_name

- CHANGELOG.md
- pybamm/models/submodels/interface/sei/sei_growth.py
> fix initial conditions for EC SEI model

- docs/conf.py
- docs/install/windows-wsl.rst
The documentation build is failing (check [here](https://readthedocs.org/projects/pybamm/builds/15830361/)) + there was a broken link.
> Fix documentation

- .github/workflows/update_license.yml
- LICENSE.txt
- docs/conf.py
The action automatically updates the license every year
> update license year and add action

- .github/workflows/update_version.yml
- scripts/update_version.py
Update `update_version.py` to use the last day of month in changelog
> Use last day of month in the script

- CONTRIBUTING.md
Fixed numbering in `CONTRIBUTING.md`
Fixes #1941
> fix numbering issue in `CONTRIBUTING.md`

- CHANGELOG.md
- pybamm/parameters/parameter_values.py
- pybamm/solvers/solution.py
Fixes #1970 . Bug was introduced in #1805 but not caught because of the way this part of the code was being tested.
> #1970 fix bug

- .github/workflows/create_release.yml
Fix create_release workflow
Fixes #1953 
Tested on fork
https://github.com/priyanshuone6/PyBaMM/runs/5640467603?check_suite_focus=true
> Fix create_release workflow

- pybamm/models/full_battery_models/lithium_ion/dfn.py
Added doctests for `DFN` model in the docstring
#1994 
> Added doctests for DFN

- pybamm/models/full_battery_models/lithium_ion/mpm.py
- pybamm/models/full_battery_models/lithium_ion/spm.py
- pybamm/models/full_battery_models/lithium_ion/spme.py
Added doctests for `SPM`, `SPMe`, `MPM` models in the docstring.
#1994
> add doctests

- docs/requirements.txt
- requirements.txt
- setup.py
Update sympy version
Fixes #2059
> Update sympy version

- benchmarks/time_sims_experiments.py
Added benchmarks for `CCCV` and `GITT` experiments for `SPM` and `DFN` models with Chen2020 and Marquis2019 parameter sets
> add experiment benchmarks

- docs/requirements.txt
- requirements.txt
- setup.py
Attempts to fix scikits.odes error
Fixes #2122
> pin older numpy

- docs/source/models/lithium_ion/electrode_soh.rst
- pybamm/models/full_battery_models/lithium_ion/__init__.py
- pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
- pybamm/simulation.py
Rename `ElectrodeSOHFull` -> `ElectrodeSOH`
> fix breaking change

- .github/workflows/validation_benchmarks.yml
- .github/workflows/work_precision_sets.yml
Created a workflow that triggers the workflow in the pybamm-validation repository.
> add workflow for validation repo

- .github/workflows/publish_pypi.yml
See https://github.com/pypa/gh-action-pypi-publish#-master-branch-sunset-
---
The `master` branch version has been sunset. Please, change the GitHub Action version you use from `master` to `release/v1` or use an exact tag, or a full Git commit SHA.
---
> Use `pypa/gh-action-pypi-publish@release/v1`

- CHANGELOG.md
> (Edit changelog) drop support for Python 3.7

- pybamm/__init__.py
- pybamm/discretisations/discretisation.py
- pybamm/util.py
- tests/unit/test_solvers/test_idaklu_solver.py
> #2365 replace tree search

- pybamm/simulation.py
- pybamm/util.py
- tests/unit/test_simulation.py
- tests/unit/test_util.py
Remove old deprecation messages
> remove deprecations >1 year old

- pybamm/parameters/parameter_values.py
Add error message for the entry point error
> add error message for entry points

- CHANGELOG.md
Fixed a few issues with the CHANGELOG format
> Fix format CHANGELOG

- CHANGELOG.md
- pybamm/version.py
> merge main into develop

- .github/workflows/test_on_push.yml
- pybamm/solvers/scikits_dae_solver.py
- pybamm/solvers/scikits_ode_solver.py
> fix numpy 1.24 error

- .github/workflows/publish_pypi.yml
Publish worfklow threw a similar error to the test workflow (in macos).
Test publish running [here](https://github.com/pybamm-team/PyBaMM/actions/runs/3795132883)
> Fix publish workflow

- CHANGELOG.md
- pybamm/parameters/parameter_sets.py
> #2534 fix spyder entry points

- CHANGELOG.md
- pybamm/solvers/algebraic_solver.py
- pybamm/solvers/base_solver.py
- pybamm/solvers/casadi_algebraic_solver.py
- pybamm/solvers/solution.py
This enables using algebraic models with step currents. There might have been a good reason to have a different termination, but I don't remember it.
> change success to final time

- GOVERNANCE.md
- README.md
> If your project has no GOVERNANCE.md at the root, then create a stub GOVERNANCE.md and include a link to your governance documentation or the appropriate parties to contact for more information.
Should we move the governance model to `GOVERNANCE.md`?
Rendered README here - https://github.com/Saransh-cpp/PyBaMM/tree/numfocus#readme.
XRef #2611
> NumFOCUS onboarding GitHub requirements

- .github/workflows/url_checker.yml
> Get URL checker up again

- run-tests.py
Fixes #2679 
Done the changes and update the help
You can run all three at once, using `$ python run-tests.py --quick`
> Changes done in issue #2674

- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- CONTRIBUTING.md
- docs/source/user_guide/installation/GNU-linux.rst
- docs/source/user_guide/installation/install-from-source.rst
- run-tests.py
- setup.py
- tox.ini
> clean up some infra stuff

- .github/workflows/periodic_benchmarks.yml
- asv.conf.json
- Failing benchmark - https://github.com/pybamm-team/PyBaMM/actions/runs/4750150635/jobs/8438069959 (different failure from the ones running on push)
- Passing benchmarks - https://github.com/Saransh-cpp/PyBaMM/actions/runs/4758273365/jobs/8456109659
> Fix scheduled benchmarks

- .github/workflows/need_reply_remove.yml
- .github/workflows/needs_reply.yml
See https://github.com/marketplace/actions/close-issues-after-no-reply
> add needs-reply issue automation

- pybamm/solvers/processed_variable.py
replace interp2d in processed variable
Fixes #2670 
> Issue #2670 replace interp2d in processed variable

- .github/workflows/need_reply_remove.yml
- .github/workflows/needs_reply.yml
> Do not run `needs_reply.yml` and `needs_reply_remove.yml` on forks

- README.md
New status badge based on #2867 
> New status badge to reflect scheduled tests

- examples/notebooks/experiments-start-time.ipynb
The last changes I made to #2616 made the example notebook fail, sorry! I have now fixed it (and added a bit more detail).
> Fix failing notebook

- README.md
Fixed the README to explain the most recent versioning.
Fixes #3160
> #3160 update versioning in README

- .github/workflows/benchmark_on_push.yml
> Improve benchmark on push workflow

- docs/source/user_guide/installation/windows-wsl.rst
> Issue 3309 Fix doctests

- CHANGELOG.md
- pybamm/solvers/solution.py
> I3130-y-slice-bug

- .github/release_reminder.md
Minor update to the release workflow link.
Fixes #3384
No breaking change here, just documentation.
> fix: Update release workflow link

- docs/conf.py
Not sure if this will work because https://docs.pybamm.org and https://pybamm.org, i.e., subdomains and the main domain are regarded as different websites by Plausible, but we can revert this attempt if it doesn't work.
> Try adding Plausible analytics

- CHANGELOG.md
- pybamm/expression_tree/binary_operators.py
- pybamm/expression_tree/broadcasts.py
- pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
- pybamm/parameters/lithium_ion_parameters.py
- pybamm/parameters/thermal_parameters.py
- tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py
> #3506 vectorize theoretical energy

- CHANGELOG.md
- CITATION.cff
- pybamm/version.py
- vcpkg.json
> Bump to v23.9rc1 manually

- .github/workflows/run_periodic_tests.yml
- GOVERNANCE.md
- README.md
> Fix scheduled tests

- docs/conf.py
> Fix missing dark mode logo

- docs/conf.py
- pybamm/citations.py
- pybamm/expression_tree/symbol.py
- pybamm/models/full_battery_models/equivalent_circuit/thevenin.py
- pybamm/models/full_battery_models/lithium_ion/dfn.py
- pybamm/models/full_battery_models/lithium_ion/mpm.py
- pybamm/models/full_battery_models/lithium_ion/spm.py
- pybamm/models/full_battery_models/lithium_ion/spme.py
- pybamm/parameters/parameter_sets.py
- pybamm/parameters/parameter_values.py
> configure doctest so we don't have to import pybamm

- pybamm/solvers/base_solver.py
Removing initial conditions from the solver.
Fixes #3629
Minor fix for an unused variable.
> Remove initial conditions

- pybamm/experiment/experiment.py
I merged a PR which was not updated to the newest ruff-format changes. This PR fixes the formatting errors on develop.
> Fix pre-commit on develop

- pybamm/expression_tree/operations/evaluate_python.py
- pybamm/solvers/jax_bdf_solver.py
> Update JAX Imports

- CHANGELOG.md
I merged a PR before I saw a request for the changelog to be updated. This fixes it.
> Correct change log

- CHANGELOG.md
- pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
- pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
- pybamm/plotting/dynamic_plot.py
- pybamm/plotting/plot.py
- pybamm/plotting/plot2D.py
- pybamm/plotting/plot_summary_variables.py
- pybamm/plotting/plot_voltage_components.py
- pybamm/plotting/quick_plot.py
- pybamm/simulation.py
- pybamm/solvers/solution.py
- tests/unit/test_batch_study.py
- tests/unit/test_plotting/test_plot.py
- tests/unit/test_plotting/test_plot_summary_variables.py
- tests/unit/test_plotting/test_plot_voltage_components.py
- tests/unit/test_plotting/test_quick_plot.py
- tests/unit/test_serialisation/test_serialisation.py
- tests/unit/test_simulation.py
- tests/unit/test_solvers/test_solution.py
- Renamed "testing" to "show plot" which is a more obvious name for the user facing API
- Fixed voltage limits check, matching limits exactly should be allowed
> fix some minor annoyances

- CHANGELOG.md
> update changelog for #3862

- docs/source/user_guide/installation/gnu-linux-mac.rst
- docs/source/user_guide/installation/index.rst
- docs/source/user_guide/installation/install-from-source.rst
- docs/source/user_guide/installation/windows-wsl.rst
Install from source and other prerequisites dependency installation procedures lacked distribution specific steps. Common Linux package managers (`apt`, `dnf`, `pacman`) specific command tabs are added to the documentation.
Fixes #3898 
> Added more Linux distribution specific installation procedures

- CHANGELOG.md
- pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
- pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
- pybamm/parameters/electrical_parameters.py
- pybamm/parameters/lithium_ion_parameters.py
Remove `_dimensional` name that was still in the code 
> Fix name dimensional

- docs/source/user_guide/installation/install-from-source.rst
This PR adds a step to the installation from source instructions to install pandoc, so that the `nox -s docs` step can complete successfully.
This is specified as a system installation, i.e. via apt or homebrew.
Fixes #3984 
> Added pandoc installation instruction

- docs/source/examples/notebooks/models/loss_of_active_materials.ipynb
> quick fix for the slow test

- CODE-OF-CONDUCT.md
> Updated code of conduct to contributor covenant v2.1

- .all-contributorsrc
Update Valentin's github username
xref: [pybamm.org#169](https://github.com/pybamm-team/pybamm.org/pull/160)
> Update Valentin's github username

- pybamm/callbacks.py
- pybamm/experiment/experiment.py
- pybamm/simulation.py
> Make function for handling time or reuse an existing one

- .github/CODEOWNERS
Fix code owners after source code moved to the src folder
> Fix CODEOWNERS after src change

- .all-contributorsrc
Changes Alec's username to fix an issue with the website
> Fix Alec's username

- .all-contributorsrc
@kratman sorry, I should've reviewed more closely.
> Fix Alec's Username II

- src/pybamm/simulation.py
- src/pybamm/solvers/solution.py
- tests/integration/test_models/standard_output_tests.py
- tests/integration/test_models/test_full_battery_models/test_lithium_ion/base_lithium_ion_tests.py
- tests/unit/test_models/test_full_battery_models/test_base_battery_model.py
- tests/unit/test_parameters/test_parameter_values.py
- tests/unit/test_simulation.py
- tests/unit/test_solvers/test_algebraic_solver.py
I split these changes out of another branch to keep it cleaner. Most of the changes are to remove static analysis warnings.
Edit: Also fixed the broken tests on develop
> Misc. cleanup and fixes for broken tests

- conftest.py
- pyproject.toml
- tests/unit/test_solvers/test_idaklu_solver.py
Minor cleanup of dead code
Fixes #4782
Fixes #4780
> Cleanup dead code

- src/pybamm/solvers/base_solver.py
- src/pybamm/solvers/idaklu_solver.py
- tests/unit/test_solvers/test_base_solver.py
> bug: fix case where multiple inputs are passed, but no inputs in model

- CHANGELOG.md
- src/pybamm/solvers/idaklu_solver.py
- src/pybamm/solvers/processed_variable.py
Some performance improvements to `IDAKLUSolver` initialization and processed variables. 
> Misc performance improvements

- src/pybamm/models/base_model.py
- tests/unit/test_models/test_base_model.py
Adds a property for accessing the built status of the model.
> Adds property for `model._built`

- CHANGELOG.md
- CITATION.cff
- src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_half_cell.py
- src/pybamm/solvers/algebraic_solver.py
- tests/unit/test_solvers/test_algebraic_solver.py
- tests/unit/test_solvers/test_base_solver.py
Bug fix release
Note: Must be merged not squashed
> Release v25.4.2

- .readthedocs.yaml
This aims to stop the linkcheck failures
> Update link check timeout

- CODE-OF-CONDUCT.md
Update the Code of Conduct to the NumFOCUS one, as agreed in the past SC meeting.
> Update to NumFOCUS Code of Conduct

- pyproject.toml
This pins pytest temporarily until I find a fix for the coverage issue
> Temporary pin for pytest

- .github/workflows/run_benchmarks_over_history.yml
Fixes an issue with the environment variables in the benchmarks workflow
> Fix historical benchmarks workflow

- pyproject.toml
- tests/unit/test_pybamm_data.py
This should fix some CI issues in #5040 
> Assert instead of return in tests

- pyproject.toml
Coverage was silently failing. Hopefully this fixes it again.
Missed in #5048
> Fixing CodeCov errors

- docs/source/user_guide/installation/gnu-linux-mac.rst
- docs/source/user_guide/installation/index.rst
- pyproject.toml
Part of removing the IREE solver
Related: #5077
> Remove IREE from docs

- CHANGELOG.md
- src/pybamm/__init__.py
- src/pybamm/solvers/idaklu_solver.py
- tests/unit/test_solvers/test_idaklu_solver.py
Removing most of the IREE solver and Jax code inside pybammsolvers.
Related #5077 
> Remove most of IREE from the solvers

- .github/workflows/run_periodic_tests.yml
- .github/workflows/test_on_push.yml
- src/pybamm/solvers/base_solver.py
- src/pybamm/solvers/scipy_solver.py
- tests/unit/test_solvers/test_base_solver.py
Fixes the spawning issue from my attempts to update to numpy 2.0.0 and switches to macos-latest
Closes #3987
> Update spawn context for multiprocessing

- CHANGELOG.md
- docs/source/examples/notebooks/models/electrode-state-of-health.ipynb
- src/pybamm/models/full_battery_models/lithium_ion/electrode_soh.py
- src/pybamm/models/submodels/current_collector/potential_pair.py
- src/pybamm/models/submodels/external_circuit/explicit_control_external_circuit.py
- src/pybamm/models/submodels/external_circuit/function_control_external_circuit.py
- src/pybamm/parameters/electrical_parameters.py
- src/pybamm/parameters/geometric_parameters.py
- src/pybamm/parameters/lead_acid_parameters.py
- src/pybamm/parameters/lithium_ion_parameters.py
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes #4833 
> Make A_cc the full current collector area

- src/pybamm/spatial_methods/scikit_finite_element_3d.py
This PR is also an attempt to fix few failing non-deterministic CI issues occurring due to some race conditions. This PR seems logically sound & may fix this:
https://github.com/pybamm-team/PyBaMM/actions/runs/16821565739/job/47649497936
> Attempt to Patch few non-deterministic CI issues.

- CHANGELOG.md
- src/pybamm/models/full_battery_models/lithium_ion/__init__.py
- src/pybamm/models/full_battery_models/lithium_ion/electrode_soh_composite.py
- src/pybamm/models/full_battery_models/lithium_ion/initial_state.py
- src/pybamm/models/full_battery_models/lithium_ion/util.py
- tests/unit/test_models/test_full_battery_models/test_lithium_ion/test_electrode_soh.py
adds composite electrode soh model
> composite esoh

- src/pybamm/spatial_methods/finite_volume_2d.py
- tests/unit/test_spatial_methods/test_finite_volume_2d/test_finite_volume_2d.py
Fixes pybamm.Inner for 2D case
> fix 2d inner product

- docs/source/user_guide/installation/index.rst
- pyproject.toml
Bounds `pybammsolvers` between `>= 0.2.0, <0.3.0`
> Update `pybammsolvers` to `v0.2.0`
